package com.yeyamo_mobile.api.event_service.controller;
import java.time.Instant;import java.util.UUID;import org.springframework.data.domain.*;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import com.yeyamo_mobile.api.event_service.dto.*;import com.yeyamo_mobile.api.event_service.enums.EventStatus;import com.yeyamo_mobile.api.event_service.service.AdminEventService;import jakarta.validation.Valid;
@RestController@RequestMapping("/api/v1/admin/events")@PreAuthorize("hasAnyRole('EDITOR','ADMIN','SUPER_ADMIN')")
public class AdminEventController{
 private final AdminEventService service;public AdminEventController(AdminEventService service){this.service=service;}
 @GetMapping public Page<AdminEventResponse>list(@RequestParam(required=false)String search,@RequestParam(required=false)EventStatus status,@RequestParam(required=false)Long regionId,@RequestParam(required=false)Long cityId,@RequestParam(required=false)UUID organizerId,@RequestParam(required=false)UUID partnerId,@RequestParam(required=false)UUID placeId,@RequestParam(required=false)Long categoryId,@RequestParam(required=false)Instant startFrom,@RequestParam(required=false)Instant startTo,Pageable pageable){return service.search(search,status,regionId,cityId,organizerId,partnerId,placeId,categoryId,startFrom,startTo,pageable);}
 @GetMapping("/{id}")public AdminEventResponse get(@PathVariable UUID id){return service.get(id);}
 @PostMapping@ResponseStatus(HttpStatus.CREATED)public AdminEventResponse create(@Valid@RequestBody AdminEventRequest request,@RequestHeader(value="X-Correlation-ID",required=false)String correlation,Authentication auth){return service.create(request,correlation,auth.getName());}
 @PutMapping("/{id}")public AdminEventResponse update(@PathVariable UUID id,@Valid@RequestBody AdminEventRequest request,@RequestHeader(value="X-Correlation-ID",required=false)String correlation,Authentication auth){return service.update(id,request,correlation,auth.getName());}
 @PatchMapping("/{id}/status")public AdminEventResponse status(@PathVariable UUID id,@RequestParam EventStatus status,@Valid@RequestBody AdminEventActionRequest request,@RequestHeader(value="X-Correlation-ID",required=false)String correlation,Authentication auth){return service.transition(id,status,request.reason(),correlation,auth.getName());}
 @PostMapping("/{id}/publish")public AdminEventResponse publish(@PathVariable UUID id,@Valid@RequestBody AdminEventActionRequest r,@RequestHeader(value="X-Correlation-ID",required=false)String c,Authentication a){return service.transition(id,EventStatus.PUBLISHED,r.reason(),c,a.getName());}
 @PostMapping("/{id}/suspend")public AdminEventResponse suspend(@PathVariable UUID id,@Valid@RequestBody AdminEventActionRequest r,@RequestHeader(value="X-Correlation-ID",required=false)String c,Authentication a){return service.transition(id,EventStatus.SUSPENDED,r.reason(),c,a.getName());}
 @PostMapping("/{id}/reject")public AdminEventResponse reject(@PathVariable UUID id,@Valid@RequestBody AdminEventActionRequest r,@RequestHeader(value="X-Correlation-ID",required=false)String c,Authentication a){return service.transition(id,EventStatus.REJECTED,r.reason(),c,a.getName());}
 @PostMapping("/{id}/archive")public AdminEventResponse archive(@PathVariable UUID id,@Valid@RequestBody AdminEventActionRequest r,@RequestHeader(value="X-Correlation-ID",required=false)String c,Authentication a){return service.transition(id,EventStatus.ARCHIVED,r.reason(),c,a.getName());}
}
