package com.yeyamo_mobile.api.referral_service.infrastructure.web;import java.util.*;import org.springframework.http.HttpStatus;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import com.yeyamo_mobile.api.referral_service.application.*;import com.yeyamo_mobile.api.referral_service.application.ReferralDtos.*;import io.swagger.v3.oas.annotations.Operation;import io.swagger.v3.oas.annotations.security.SecurityRequirement;import jakarta.validation.Valid;
@RestController@SecurityRequirement(name="bearerAuth")public class ReferralController{private final ReferralApplicationService service;public ReferralController(ReferralApplicationService s){service=s;}
 @PostMapping("/api/v1/referrals/codes")@ResponseStatus(HttpStatus.CREATED)@Operation(summary="Create a referral code")public CodeView create(Authentication a,@Valid@RequestBody CreateCode body,@RequestHeader(value="X-Correlation-Id",required=false)String c){return service.createCode(a.getName(),body.maxUses(),body.expiresAt(),c);}
 @PostMapping("/api/v1/referrals/invitations")@ResponseStatus(HttpStatus.CREATED)public InvitationView invite(Authentication a,@Valid@RequestBody Invite body,@RequestHeader(value="X-Correlation-Id",required=false)String c){return service.invite(a.getName(),body.code(),body.email(),c);}
 @PostMapping("/api/v1/referrals/redeem")@ResponseStatus(HttpStatus.CREATED)public AttributionView redeem(Authentication a,@Valid@RequestBody Redeem body,@RequestHeader(value="X-Device-Fingerprint",required=false)String device,@RequestHeader(value="X-Correlation-Id",required=false)String c){return service.redeem(a.getName(),body.code(),device,c);}
 @PostMapping("/api/v1/referrals/codes/{id}/disable")@ResponseStatus(HttpStatus.NO_CONTENT)public void disable(Authentication a,@PathVariable UUID id,@RequestHeader(value="X-Correlation-Id",required=false)String c){service.disable(a.getName(),id,c);}
 @GetMapping("/api/v1/me/referrals/codes")public List<CodeView>codes(Authentication a){return service.codes(a.getName());}
 @GetMapping("/api/v1/me/referrals/invitations")public List<InvitationView>invitations(Authentication a){return service.invitations(a.getName());}
 @GetMapping("/api/v1/me/referrals/attributions")public List<AttributionView>attributions(Authentication a){return service.attributions(a.getName());}
 @GetMapping("/api/v1/me/referrals/rewards")public List<RewardView>rewards(Authentication a){return service.rewards(a.getName());}
 @GetMapping("/api/v1/me/referrals/attributions/{id}/history")public List<HistoryView>history(Authentication a,@PathVariable UUID id){return service.history(a.getName(),id);}
}
