package com.yeyamo_mobile.api.ticket_service.application;
import com.yeyamo_mobile.api.ticket_service.domain.model.*;import com.yeyamo_mobile.api.ticket_service.infrastructure.persistence.*;import org.springframework.stereotype.*;import org.springframework.transaction.annotation.*;import java.math.*;import java.time.*;import java.util.*;
@Service public class TicketManagementService{
 private final SpringTicketSaleConfigurationRepository configs;private final SpringTicketTypeRepository types;private final SpringEventStaffAssignmentRepository staff;
 public TicketManagementService(SpringTicketSaleConfigurationRepository c,SpringTicketTypeRepository t,SpringEventStaffAssignmentRepository s){configs=c;types=t;staff=s;}
 public record SaleConfig(String eventId,String partnerId,Instant salesStartAt,Instant salesEndAt,int maxTicketsPerBuyer,String currency){}
 public record TypeConfig(String code,String name,String description,BigDecimal price,int quantity,Instant salesStartAt,Instant salesEndAt,String accessZone,String gateInstructions){}
 @Transactional public TicketSaleConfigurationEntity configure(SaleConfig r){if(!r.salesStartAt().isBefore(r.salesEndAt())||r.maxTicketsPerBuyer()<1)throw new IllegalArgumentException("Invalid sales configuration");TicketSaleConfigurationEntity c=configs.findByEventId(r.eventId()).orElseGet(TicketSaleConfigurationEntity::new);if(c.getId()!=null&&!c.getPartnerId().equals(r.partnerId()))throw new SecurityException("Partner mismatch");c.setEventId(r.eventId());c.setPartnerId(r.partnerId());c.setSalesStartAt(r.salesStartAt());c.setSalesEndAt(r.salesEndAt());c.setMaxTicketsPerBuyer(r.maxTicketsPerBuyer());c.setCurrency(r.currency().toUpperCase(Locale.ROOT));c.setStatus("ACTIVE");return configs.save(c);}
 @Transactional public TicketTypeEntity type(UUID configId,String partner,TypeConfig r){TicketSaleConfigurationEntity c=configs.findById(configId).orElseThrow();if(!c.getPartnerId().equals(partner))throw new SecurityException("Partner mismatch");if(r.price().signum()<0||r.quantity()<0)throw new IllegalArgumentException("Invalid ticket type");TicketTypeEntity t=new TicketTypeEntity();t.setSaleConfigurationId(configId);t.setCode(r.code().toUpperCase(Locale.ROOT));t.setName(r.name());t.setDescription(r.description());t.setPrice(r.price());t.setQuantityTotal(r.quantity());t.setQuantityReserved(0);t.setQuantitySold(0);t.setSalesStartAt(r.salesStartAt());t.setSalesEndAt(r.salesEndAt());t.setAccessZone(r.accessZone());t.setGateInstructions(r.gateInstructions());t.setStatus("ACTIVE");return types.save(t);}
 @Transactional public EventStaffAssignmentEntity assign(String event,String partner,String user,StaffRole role,Instant from,Instant until){if(!from.isBefore(until))throw new IllegalArgumentException("Invalid validity period");EventStaffAssignmentEntity a=staff.findByEventIdAndUserId(event,user).orElseGet(EventStaffAssignmentEntity::new);if(a.getId()!=null&&!a.getPartnerId().equals(partner))throw new SecurityException("Partner mismatch");a.setEventId(event);a.setPartnerId(partner);a.setUserId(user);a.setRole(role);a.setStatus("ACTIVE");a.setValidFrom(from);a.setValidUntil(until);return staff.save(a);}
 @Transactional public void revokeStaff(UUID id,String partner){EventStaffAssignmentEntity a=staff.findById(id).orElseThrow();if(!a.getPartnerId().equals(partner))throw new SecurityException("Partner mismatch");a.setStatus("REVOKED");staff.save(a);}
 @Transactional(readOnly=true)public List<TicketTypeEntity>types(UUID config){return types.findBySaleConfigurationId(config);}@Transactional(readOnly=true)public List<EventStaffAssignmentEntity>staff(String event){return staff.findByEventIdOrderByCreatedAtDesc(event);}
}
