package com.yeyamo_mobile.api.payment_service.domain;
public enum PaymentStatus { AUTHORIZATION_PENDING, AUTHORIZED, FAILED, CANCELLATION_PENDING, CANCELLED, REFUND_PENDING, PARTIALLY_REFUNDED, REFUNDED }
