package com.yeyamo_mobile.api.admin_service.governance;
import static com.yeyamo_mobile.api.admin_service.governance.GovernanceDtos.*;
import java.time.Instant;import java.util.*;import com.yeyamo_mobile.api.admin_service.event.AdminEventOutbox;import com.yeyamo_mobile.api.admin_service.service.AuditService;import jakarta.servlet.http.HttpServletRequest;import org.springframework.cache.annotation.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service@Transactional public class GovernanceService{
 private final PlatformSettingRepository settings;private final PlatformSettingHistoryRepository settingHistory;private final FeatureFlagRepository flags;private final FeatureFlagHistoryRepository flagHistory;private final AuditService audit;private final AdminEventOutbox outbox;
 public GovernanceService(PlatformSettingRepository s,PlatformSettingHistoryRepository sh,FeatureFlagRepository f,FeatureFlagHistoryRepository fh,AuditService a,AdminEventOutbox o){settings=s;settingHistory=sh;flags=f;flagHistory=fh;audit=a;outbox=o;}
 @Transactional(readOnly=true)public List<SettingResponse>settings(){return settings.findAll().stream().map(this::setting).toList();}
 @Cacheable(cacheNames="platformSettings",key="#key")@Transactional(readOnly=true)public SettingResponse setting(String key){SettingDefinition.require(key);return setting(settings.findById(key.toUpperCase(Locale.ROOT)).orElseThrow(()->new NoSuchElementException("Setting not found")));}
 @CacheEvict(cacheNames="platformSettings",key="#key")public SettingResponse updateSetting(String key,SettingUpdateRequest r,HttpServletRequest request){var definition=SettingDefinition.require(key);definition.validate(r.value());var normalized=key.toUpperCase(Locale.ROOT);var e=settings.findById(normalized).orElseGet(PlatformSettingEntity::new);if(e.key!=null&&e.version!=r.expectedVersion())throw new IllegalStateException("SETTING_VERSION_CONFLICT");e.key=normalized;e.value=r.value().trim();e.type=definition.type;e.description=definition.description;e.version=e.key==null?1:e.version+1;e.updatedBy=audit.currentAdminId().toString();e.updatedAt=Instant.now();settings.save(e);history(e,r.reason());audit.record("PLATFORM_SETTING_CHANGED","PLATFORM_SETTING",uuid(normalized),Map.of("key",normalized,"version",e.version),request);outbox.domainEvent("PlatformSettingChanged",normalized,Map.of("key",normalized,"version",e.version),e.updatedBy,request.getHeader("X-Correlation-Id"));return setting(e);}
 public List<SettingResponse>settingHistory(){return settingHistory.findAll().stream().sorted(Comparator.comparing((PlatformSettingHistoryEntity h)->h.updatedAt).reversed()).map(h->new SettingResponse(h.key,h.value,h.type,SettingDefinition.require(h.key).description,h.version,h.updatedBy,h.updatedAt)).toList();}
 @CacheEvict(cacheNames="platformSettings",key="#key")public SettingResponse rollbackSetting(String key,long version,String reason,HttpServletRequest request){var old=settingHistory.findByKeyAndVersion(key.toUpperCase(Locale.ROOT),version).orElseThrow();var current=settings.findById(old.key).orElseThrow();return updateSetting(key,new SettingUpdateRequest(old.value,reason,current.version),request);}
 @Transactional(readOnly=true)public List<FeatureFlagResponse>flags(){return flags.findAll().stream().map(this::flag).toList();}@Cacheable(cacheNames="featureFlags",key="#key")@Transactional(readOnly=true)public FeatureFlagResponse flag(String key){return flag(flags.findById(key).orElseThrow(()->new NoSuchElementException("Feature flag not found")));}
 @CacheEvict(cacheNames="featureFlags",key="#r.key")public FeatureFlagResponse create(FeatureFlagRequest r,HttpServletRequest request){if(flags.existsById(r.key()))throw new IllegalStateException("FEATURE_FLAG_EXISTS");return saveFlag(new FeatureFlagEntity(),r,request);}
 @CacheEvict(cacheNames="featureFlags",key="#key")public FeatureFlagResponse updateFlag(String key,FeatureFlagRequest r,HttpServletRequest request){if(!key.equals(r.key()))throw new IllegalArgumentException("Feature flag key is immutable");var e=flags.findById(key).orElseThrow();if(e.version!=r.expectedVersion())throw new IllegalStateException("FEATURE_FLAG_VERSION_CONFLICT");return saveFlag(e,r,request);}
 public List<FeatureFlagResponse>flagHistory(String key){return flagHistory.findByKeyOrderByVersionDesc(key).stream().map(h->new FeatureFlagResponse(h.key,h.description,h.enabled,h.environment,h.rolloutPercentage,h.version,h.updatedBy,h.updatedAt)).toList();}
 @CacheEvict(cacheNames="featureFlags",key="#key")public FeatureFlagResponse rollbackFlag(String key,long version,String reason,HttpServletRequest request){var old=flagHistory.findByKeyAndVersion(key,version).orElseThrow();var current=flags.findById(key).orElseThrow();return updateFlag(key,new FeatureFlagRequest(key,old.description,old.enabled,old.environment,old.rolloutPercentage,reason,current.version),request);}
 private FeatureFlagResponse saveFlag(FeatureFlagEntity e,FeatureFlagRequest r,HttpServletRequest request){if(e.key==null)e.key=r.key();e.description=r.description().trim();e.enabled=r.enabled();e.environment=r.environment();e.rolloutPercentage=r.rolloutPercentage();e.version++;e.updatedBy=audit.currentAdminId().toString();e.updatedAt=Instant.now();flags.save(e);var h=new FeatureFlagHistoryEntity();h.id=UUID.randomUUID();h.key=e.key;h.description=e.description;h.enabled=e.enabled;h.environment=e.environment;h.rolloutPercentage=e.rolloutPercentage;h.version=e.version;h.updatedBy=e.updatedBy;h.updatedAt=e.updatedAt;h.reason=r.reason();flagHistory.save(h);audit.record("FEATURE_FLAG_CHANGED","FEATURE_FLAG",uuid(e.key),Map.of("key",e.key,"version",e.version),request);outbox.domainEvent("FeatureFlagChanged",e.key,Map.of("key",e.key,"version",e.version,"enabled",e.enabled),e.updatedBy,request.getHeader("X-Correlation-Id"));return flag(e);}
 private void history(PlatformSettingEntity e,String reason){var h=new PlatformSettingHistoryEntity();h.id=UUID.randomUUID();h.key=e.key;h.value=e.value;h.type=e.type;h.version=e.version;h.updatedBy=e.updatedBy;h.updatedAt=e.updatedAt;h.reason=reason;settingHistory.save(h);}private SettingResponse setting(PlatformSettingEntity e){return new SettingResponse(e.key,e.value,e.type,e.description,e.version,e.updatedBy,e.updatedAt);}private FeatureFlagResponse flag(FeatureFlagEntity e){return new FeatureFlagResponse(e.key,e.description,e.enabled,e.environment,e.rolloutPercentage,e.version,e.updatedBy,e.updatedAt);}private UUID uuid(String v){return UUID.nameUUIDFromBytes(v.getBytes(java.nio.charset.StandardCharsets.UTF_8));}
}
