package com.yeyamo_mobile.api.discovery_service.infrastructure.messaging;
import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
import java.util.*;import org.junit.jupiter.api.Test;import org.mockito.ArgumentCaptor;import com.fasterxml.jackson.databind.ObjectMapper;
import com.yeyamo_mobile.api.discovery_service.application.DiscoveryProjectionService;import com.yeyamo_mobile.api.discovery_service.domain.model.*;
class DiscoveryEventConsumerTest {
 @Test void projectsPublishedCatalogAsset() throws Exception {var projection=mock(DiscoveryProjectionService.class);var receipts=mock(ProcessedEventRepository.class);var consumer=new DiscoveryEventConsumer(new ObjectMapper(),projection,receipts);UUID id=UUID.randomUUID();consumer.catalog("{\"eventId\":\""+id+"\",\"eventType\":\"catalog.asset.status_changed\",\"eventVersion\":1,\"occurredAt\":\"2026-01-01T00:00:00Z\",\"payload\":{\"assetId\":\"42\",\"type\":\"PLACE\",\"name\":\"Plage\",\"status\":\"PUBLISHED\",\"latitude\":4.0,\"longitude\":9.0}}");var captor=ArgumentCaptor.forClass(DiscoveryDocument.class);verify(projection).project(captor.capture());assertTrue(captor.getValue().active());assertEquals("catalog:42",captor.getValue().sourceId());verify(receipts).save(any());}
 @Test void isIdempotent() throws Exception {var projection=mock(DiscoveryProjectionService.class);var receipts=mock(ProcessedEventRepository.class);UUID id=UUID.randomUUID();when(receipts.existsById(id)).thenReturn(true);new DiscoveryEventConsumer(new ObjectMapper(),projection,receipts).interaction("{\"eventId\":\""+id+"\",\"eventType\":\"interaction.like.added\",\"eventVersion\":1,\"payload\":{\"postId\":\"42\"}}");verifyNoInteractions(projection);verify(receipts,never()).save(any());}
 @Test void rejectsUnsupportedContract() {var consumer=new DiscoveryEventConsumer(new ObjectMapper(),mock(DiscoveryProjectionService.class),mock(ProcessedEventRepository.class));String raw="{\"eventId\":\""+UUID.randomUUID()+"\",\"eventType\":\"unknown\",\"eventVersion\":1,\"payload\":{}}";assertThrows(IllegalArgumentException.class,()->consumer.catalog(raw));}
}
