package com.yeyamo_mobile.api.discovery_service.infrastructure.searchadmin;
import static com.yeyamo_mobile.api.discovery_service.infrastructure.searchadmin.SearchAdminDtos.*;
import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.*;import java.util.*;import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.*;import org.springframework.core.task.TaskExecutor;import org.springframework.dao.DataIntegrityViolationException;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service @Transactional public class SearchAdminService {
 private final SearchSynonymRepository synonyms;private final SearchRankingRepository rankings;private final SearchReindexJobRepository jobs;private final SearchZeroResultRepository zero;private final OpenSearchAdminClient openSearch;private final ObjectMapper mapper;private final TaskExecutor executor;
 public SearchAdminService(SearchSynonymRepository s,SearchRankingRepository r,SearchReindexJobRepository j,SearchZeroResultRepository z,OpenSearchAdminClient o,ObjectMapper m,TaskExecutor e){synonyms=s;rankings=r;jobs=j;zero=z;openSearch=o;mapper=m;executor=e;}
 @Transactional(readOnly=true)public Overview overview(){long start=System.nanoTime();JsonNode h=openSearch.health();long latency=Duration.ofNanos(System.nanoTime()-start).toMillis();List<IndexInfo> indexes=indexes();long docs=indexes.stream().mapToLong(IndexInfo::documents).sum();long zeros=zero.count();return new Overview(h.path("status").asText("unknown"),indexes.size(),docs,null,latency,docs+zeros==0?0d:(double)zeros/(docs+zeros));}
 @Transactional(readOnly=true)public List<IndexInfo> indexes(){JsonNode data=openSearch.indexes();if(data==null||!data.isArray())return List.of();List<IndexInfo> out=new ArrayList<>();data.forEach(i->out.add(new IndexInfo(i.path("index").asText(),i.path("health").asText(),i.path("docs.count").asLong(),i.path("store.size").asLong())));return out;}
 public ReindexResponse reindex(String actor){if(jobs.existsByStatusIn(List.of("QUEUED","RUNNING")))throw new IllegalStateException("REINDEX_ALREADY_RUNNING");var j=new SearchReindexJobEntity();j.id=UUID.randomUUID();j.status="QUEUED";j.requestedBy=actor;j.createdAt=Instant.now();jobs.saveAndFlush(j);executor.execute(()->run(j.id));return new ReindexResponse(j.id,j.status);}
 void run(UUID id){var j=jobs.findById(id).orElseThrow();try{j.status="RUNNING";j.startedAt=Instant.now();jobs.save(j);openSearch.reindex();j.status="COMPLETED";}catch(Exception e){j.status="FAILED";j.errorCode="SEARCH_PROVIDER_UNAVAILABLE";}j.completedAt=Instant.now();jobs.save(j);}
 @Transactional(readOnly=true)public List<SynonymResponse> synonyms(){return synonyms.findAll(Sort.by("createdAt")).stream().map(this::synonym).toList();}
 public SynonymResponse createSynonym(String actor,SynonymRequest r){var e=new SearchSynonymEntity();e.id=UUID.randomUUID();e.termsJson=write(normalize(r.terms()));e.active=r.active();e.createdBy=actor;e.createdAt=Instant.now();e.updatedAt=e.createdAt;return synonym(synonyms.save(e));}
 public SynonymResponse updateSynonym(UUID id,SynonymRequest r){var e=synonyms.findById(id).orElseThrow();e.termsJson=write(normalize(r.terms()));e.active=r.active();e.updatedAt=Instant.now();return synonym(synonyms.save(e));}
 public void deleteSynonym(UUID id){synonyms.delete(synonyms.findById(id).orElseThrow());}
 @Transactional(readOnly=true)public RankingResponse ranking(){return rankings.findActive().map(this::ranking).orElse(null);}
 public RankingResponse ranking(String actor,RankingRequest request){rankings.findActive().ifPresent(r->{r.active=false;rankings.save(r);});var e=new SearchRankingEntity();e.id=UUID.randomUUID();e.version=rankings.maxVersion()+1;e.configJson=write(request.weights());e.active=true;e.createdBy=actor;e.createdAt=Instant.now();return ranking(rankings.save(e));}
 @Transactional(readOnly=true)public Page<ZeroResult> zeroResults(Pageable p){return zero.findAllByOrderByOccurrencesDesc(p).map(z->new ZeroResult(z.normalizedQuery,z.regionCode,z.occurrences,z.firstSeenAt,z.lastSeenAt));}
 public void recordZero(String query,String region){if(query==null||query.isBlank())return;String normalized=query.trim().toLowerCase(Locale.ROOT).replaceAll("\\s+"," ");String hash=hash(normalized+"|"+Objects.toString(region,""));var e=zero.findById(hash).orElseGet(()->{var n=new SearchZeroResultEntity();n.queryHash=hash;n.normalizedQuery=normalized;n.regionCode=region;n.firstSeenAt=Instant.now();n.occurrences=0;return n;});e.occurrences++;e.lastSeenAt=Instant.now();zero.save(e);}
 private SynonymResponse synonym(SearchSynonymEntity e){return new SynonymResponse(e.id,read(e.termsJson,new TypeReference<List<String>>(){}),e.active,e.createdBy,e.createdAt,e.updatedAt);}private RankingResponse ranking(SearchRankingEntity e){return new RankingResponse(e.id,e.version,read(e.configJson,new TypeReference<Map<String,Double>>(){}),e.active,e.createdBy,e.createdAt);}
 private List<String> normalize(List<String> terms){return terms.stream().map(s->s.trim().toLowerCase(Locale.ROOT)).distinct().toList();}private String write(Object o){try{return mapper.writeValueAsString(o);}catch(Exception e){throw new IllegalArgumentException(e);}}private<T>T read(String s,TypeReference<T> t){try{return mapper.readValue(s,t);}catch(Exception e){throw new IllegalStateException(e);}}private String hash(String s){try{return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
