package com.yeyamo_mobile.api.commerce_service.interfaces;
import com.yeyamo_mobile.api.commerce_service.persistence.*;import jakarta.validation.*;import jakarta.validation.constraints.*;import org.springframework.security.core.*;import org.springframework.web.bind.annotation.*;import java.math.*;import java.time.*;import java.util.*;import static com.yeyamo_mobile.api.commerce_service.domain.CommerceTypes.*;
@RestController @RequestMapping("/api/v1/commerce/admin")public class AdminCommerceController{
 private final PromotionRepository promotions;private final CommissionRepository commissions;private final CommerceAuditRepository audit;
 public AdminCommerceController(PromotionRepository p,CommissionRepository c,CommerceAuditRepository a){promotions=p;commissions=c;audit=a;}
 public record PromotionRequest(String partnerId,@NotBlank String code,@NotBlank String name,String description,@NotNull DiscountType discountType,@NotNull@DecimalMin("0")BigDecimal discountValue,BigDecimal maximumDiscount,@NotNull@DecimalMin("0")BigDecimal minimumOrderAmount,Long usageLimit,Long usageLimitPerUser,@NotNull Instant startsAt,@NotNull Instant endsAt,Set<ProductType>applicableProductTypes,Set<String>applicableEntityIds){}
 @PostMapping("/promotions")public Promotion promotion(@Valid@RequestBody PromotionRequest r,Authentication a){if(!r.startsAt().isBefore(r.endsAt()))throw new IllegalArgumentException("Invalid promotion period");Promotion p=new Promotion();p.id=UUID.randomUUID();p.partnerId=r.partnerId();p.code=r.code().trim().toUpperCase(Locale.ROOT);p.name=r.name();p.description=r.description();p.discountType=r.discountType();p.discountValue=r.discountValue();p.maximumDiscount=r.maximumDiscount();p.minimumOrderAmount=r.minimumOrderAmount();p.usageLimit=r.usageLimit();p.usageLimitPerUser=r.usageLimitPerUser();p.startsAt=r.startsAt();p.endsAt=r.endsAt();p.applicableProductTypes=r.applicableProductTypes()==null?"":String.join(",",r.applicableProductTypes().stream().map(Enum::name).toList());p.applicableEntityIds=r.applicableEntityIds()==null?"":String.join(",",r.applicableEntityIds());p.status=PromotionStatus.ACTIVE;p=promotions.save(p);log(a,"PROMOTION_CREATED","Promotion",p.id.toString(),p.code);return p;}
 public record CommissionRequest(String partnerId,@NotNull ProductType productType,@NotNull@DecimalMin("0")BigDecimal percentage,@NotNull@DecimalMin("0")BigDecimal fixedAmount,BigDecimal maximumAmount,@Pattern(regexp="[A-Z]{3}")String currency,@Min(1)int ruleVersion,@NotNull Instant effectiveFrom,Instant effectiveUntil){}
 @PostMapping("/commissions")public CommissionRule commission(@Valid@RequestBody CommissionRequest r,Authentication a){CommissionRule c=new CommissionRule();c.id=UUID.randomUUID();c.partnerId=r.partnerId();c.productType=r.productType();c.percentage=r.percentage();c.fixedAmount=r.fixedAmount();c.maximumAmount=r.maximumAmount();c.currency=r.currency();c.ruleVersion=r.ruleVersion();c.effectiveFrom=r.effectiveFrom();c.effectiveUntil=r.effectiveUntil();c.status="ACTIVE";c=commissions.save(c);log(a,"COMMISSION_CREATED","CommissionRule",c.id.toString(),"v"+c.ruleVersion);return c;}
 private void log(Authentication a,String action,String type,String id,String details){CommerceAudit x=new CommerceAudit();x.id=UUID.randomUUID();x.actorId=a.getName();x.action=action;x.entityType=type;x.entityId=id;x.details=details;x.occurredAt=Instant.now();audit.save(x);}}
