package com.yeyamo_mobile.api.booking_service.application;
import static com.yeyamo_mobile.api.booking_service.application.AdminBookingDtos.*;import java.math.BigDecimal;import java.time.Instant;import java.util.*;import org.springframework.data.domain.*;import org.springframework.data.jpa.domain.Specification;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import com.yeyamo_mobile.api.booking_service.application.BookingDtos.BookingView;import com.yeyamo_mobile.api.booking_service.application.port.BookingOutboxPort;import com.yeyamo_mobile.api.booking_service.domain.*;import com.yeyamo_mobile.api.booking_service.infrastructure.persistence.*;import jakarta.persistence.criteria.Predicate;
@Service public class AdminBookingService{private final BookingRepository bookings;private final BookingHistoryRepository history;private final BookingApplicationService commands;private final BookingOutboxPort outbox;public AdminBookingService(BookingRepository b,BookingHistoryRepository h,BookingApplicationService c,BookingOutboxPort o){bookings=b;history=h;commands=c;outbox=o;}
 @Transactional(readOnly=true)public Page<AdminBookingSummary>list(String search,BookingStatus status,String userId,String partnerId,String placeId,String eventId,PaymentStatus paymentStatus,Instant createdFrom,Instant createdTo,Instant bookingDateFrom,Instant bookingDateTo,Pageable pageable){Pageable safe=PageRequest.of(pageable.getPageNumber(),Math.min(pageable.getPageSize(),200),pageable.getSort());if(placeId!=null||eventId!=null)return Page.empty(safe);return bookings.findAll(spec(search,status,userId,partnerId,paymentStatus,createdFrom,createdTo,bookingDateFrom,bookingDateTo),safe).map(this::summary);}
 @Transactional(readOnly=true)public AdminBookingDetail detail(UUID id){BookingEntity b=bookings.findById(id).orElseThrow();var s=b.getSlot();var events=history.findByBookingIdOrderByOccurredAtAsc(id).stream().map(h->new BookingDtos.HistoryView(h.getId(),h.getAction(),h.getDetails(),h.getOccurredAt())).toList();return new AdminBookingDetail(summary(b),events,new SubjectSummary(b.getUserId(),null),new SubjectSummary(s.getOwnerUserId(),null),new ResourceSummary("ACTIVITY",b.getActivityId(),null,s.getId(),s.getStartsAt(),s.getEndsAt()),new PaymentSummary(b.getPaymentStatus(),b.getTotalAmount(),b.getCurrency()),List.of(),b.getConfirmedAt(),b.getCancelledAt(),b.getCompletedAt());}
 @Transactional public BookingView cancel(String actor,UUID id,String reason,String key,String correlation){BookingView v=commands.cancel(actor,id,reason,key,correlation,true);outbox.append("booking.events","BOOKING_ADMIN_CANCELLED",id.toString(),correlation,Map.of("bookingId",id,"actorId",actor,"reason",reason));return v;}
 @Transactional public BookingView complete(String actor,UUID id,String key,String correlation){BookingView v=commands.complete(actor,id,key,correlation,true);outbox.append("booking.events","BOOKING_ADMIN_COMPLETED",id.toString(),correlation,Map.of("bookingId",id,"actorId",actor));return v;}
 @Transactional(readOnly=true)public AdminBookingStats stats(Instant from,Instant to){Object[]r=bookings.adminStats(from,to);if(r.length==1&&r[0]instanceof Object[]nested)r=nested;return new AdminBookingStats(n(r[0]),n(r[1]),n(r[2]),n(r[3]),n(r[4]),(BigDecimal)r[5]);}
 private Specification<BookingEntity>spec(String search,BookingStatus status,String userId,String partnerId,PaymentStatus paymentStatus,Instant createdFrom,Instant createdTo,Instant bookingFrom,Instant bookingTo){return(root,q,b)->{List<Predicate>p=new ArrayList<>();if(text(search)){String l="%"+search.trim().toLowerCase()+"%";p.add(b.or(b.like(b.lower(root.get("reference")),l),b.like(b.lower(root.get("userId")),l),b.like(b.lower(root.get("activityId")),l)));}if(status!=null)p.add(b.equal(root.get("status"),status));if(text(userId))p.add(b.equal(root.get("userId"),userId));if(text(partnerId))p.add(b.equal(root.get("slot").get("ownerUserId"),partnerId));if(paymentStatus!=null)p.add(b.equal(root.get("paymentStatus"),paymentStatus));if(createdFrom!=null)p.add(b.greaterThanOrEqualTo(root.get("createdAt"),createdFrom));if(createdTo!=null)p.add(b.lessThanOrEqualTo(root.get("createdAt"),createdTo));if(bookingFrom!=null)p.add(b.greaterThanOrEqualTo(root.get("slot").get("startsAt"),bookingFrom));if(bookingTo!=null)p.add(b.lessThanOrEqualTo(root.get("slot").get("startsAt"),bookingTo));return b.and(p.toArray(Predicate[]::new));};}
 private AdminBookingSummary summary(BookingEntity b){var s=b.getSlot();return new AdminBookingSummary(b.getId(),b.getReference(),b.getUserId(),null,s.getOwnerUserId(),null,"ACTIVITY",b.getActivityId(),null,b.getTotalAmount(),b.getCurrency(),b.getPaymentStatus(),b.getStatus(),s.getStartsAt(),b.getCreatedAt());}private boolean text(String v){return v!=null&&!v.isBlank();}private long n(Object v){return((Number)v).longValue();}}
