spring.application.name=booking-service
spring.cloud.config.username=${CONFIG_SERVER_USERNAME}
spring.cloud.config.password=${CONFIG_SERVER_PASSWORD}
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8080}
spring.cloud.config.fail-fast=true
