package com.yeyamo_mobile.api.messaging_service.infrastructure.web;
import static com.yeyamo_mobile.api.messaging_service.application.MessagingDtos.*;import java.time.Instant;import java.util.*;import org.springframework.http.HttpStatus;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import com.yeyamo_mobile.api.messaging_service.application.MessagingApplicationService;import com.yeyamo_mobile.api.messaging_service.domain.*;import jakarta.validation.Valid;import jakarta.validation.constraints.*;
@RestController @RequestMapping("/api/v1/messaging")public class MessagingController{
 private final MessagingApplicationService service;public MessagingController(MessagingApplicationService service){this.service=service;}
 @PostMapping("/conversations")@ResponseStatus(HttpStatus.CREATED)public ConversationView create(@Valid@RequestBody CreateConversationRequest request,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,Authentication auth){return service.create(auth.getName(),new CreateConversation(request.type(),request.title(),request.participantIds()),correlation);}
 @PostMapping("/conversations/partner/{partnerId}")@ResponseStatus(HttpStatus.CREATED)public ConversationView createPartnerConversation(@PathVariable UUID partnerId,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,Authentication auth){return service.createPartnerConversation(auth.getName(),partnerId,correlation);}
 @GetMapping("/conversations")public List<ConversationSummary>list(Authentication auth){return service.list(auth.getName());}
 @GetMapping("/conversations/{id}")public ConversationView get(@PathVariable UUID id,Authentication auth){return service.get(auth.getName(),id);}
 @PostMapping("/conversations/{id}/members")public ConversationView add(@PathVariable UUID id,@Valid@RequestBody MemberRequest request,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,Authentication auth){return service.addMember(auth.getName(),id,request.userId(),correlation);}
 @DeleteMapping("/conversations/{id}/members/{userId}")@ResponseStatus(HttpStatus.NO_CONTENT)public void remove(@PathVariable UUID id,@PathVariable String userId,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,Authentication auth){service.removeMember(auth.getName(),id,userId,correlation);}
 @PostMapping("/conversations/{id}/leave")@ResponseStatus(HttpStatus.NO_CONTENT)public void leave(@PathVariable UUID id,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,Authentication auth){service.leave(auth.getName(),id,correlation);}
 @PostMapping("/conversations/{id}/messages")@ResponseStatus(HttpStatus.CREATED)public MessageView send(@PathVariable UUID id,@Valid@RequestBody SendMessageRequest request,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,Authentication auth){return service.send(auth.getName(),id,new SendMessage(request.clientMessageId(),request.type(),request.body(),request.attachmentIds(),request.replyToMessageId()),correlation);}
 @GetMapping("/conversations/{id}/messages")public MessageSlice messages(@PathVariable UUID id,@RequestParam(required=false)Instant before,@RequestParam(defaultValue="50")@Min(1)@Max(100)int limit,Authentication auth){return service.messages(auth.getName(),id,before,limit);}
 @PatchMapping("/messages/{messageId}")public MessageView edit(@PathVariable UUID messageId,@Valid@RequestBody EditMessageRequest request,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,Authentication auth){return service.edit(auth.getName(),messageId,request.body(),correlation);}
 @DeleteMapping("/messages/{messageId}")@ResponseStatus(HttpStatus.NO_CONTENT)public void delete(@PathVariable UUID messageId,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,Authentication auth){service.delete(auth.getName(),messageId,correlation);}
 @PostMapping("/conversations/{id}/read/{messageId}")@ResponseStatus(HttpStatus.NO_CONTENT)public void read(@PathVariable UUID id,@PathVariable UUID messageId,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,Authentication auth){service.read(auth.getName(),id,messageId,correlation);}
 public record CreateConversationRequest(@NotNull ConversationType type,@Size(max=120)String title,@NotEmpty@Size(max=100)Set<@NotBlank@Size(max=120)String>participantIds){}public record MemberRequest(@NotBlank@Size(max=120)String userId){}public record SendMessageRequest(@NotBlank@Size(max=120)String clientMessageId,@NotNull MessageType type,@Size(max=4000)String body,@Size(max=10)List<UUID>attachmentIds,UUID replyToMessageId){}public record EditMessageRequest(@NotBlank@Size(max=4000)String body){}
}
