package com.yeyamo_mobile.api.notification_service.admin;
import static com.yeyamo_mobile.api.notification_service.admin.AdminNotificationDtos.*;import java.time.*;import java.util.*;import jakarta.persistence.criteria.Predicate;import org.springframework.data.domain.*;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service@Transactional public class AdminNotificationService{
 private final AdminNotificationRepository notifications;private final AdminNotificationReadRepository reads;public AdminNotificationService(AdminNotificationRepository n,AdminNotificationReadRepository r){notifications=n;reads=r;}
 @Transactional(readOnly=true)public Page<Response>list(String admin,Set<String>roles,String type,Pageable p){Map<UUID,Instant>read=new HashMap<>();reads.findByAdminId(admin).forEach(r->read.put(r.notificationId,r.readAt));return notifications.findAll((root,q,cb)->{List<Predicate>x=new ArrayList<>();x.add(cb.or(cb.equal(root.get("adminId"),admin),root.get("targetRole").in(roles)));if(type!=null&&!type.isBlank())x.add(cb.equal(root.get("type"),type));return cb.and(x.toArray(Predicate[]::new));},p).map(n->response(n,read.get(n.id)));}
 @Transactional(readOnly=true)public long unread(String admin,Set<String>roles){return list(admin,roles,null,PageRequest.of(0,10000)).stream().filter(n->n.readAt()==null).count();}
 public Response read(String admin,Set<String>roles,UUID id){var n=authorized(admin,roles,id);var receipt=reads.findByNotificationIdAndAdminId(id,admin).orElseGet(AdminNotificationReadEntity::new);if(receipt.id==null){receipt.id=UUID.randomUUID();receipt.notificationId=id;receipt.adminId=admin;}receipt.readAt=Instant.now();reads.save(receipt);return response(n,receipt.readAt);}
 public Response unread(String admin,Set<String>roles,UUID id){var n=authorized(admin,roles,id);reads.deleteByNotificationIdAndAdminId(id,admin);return response(n,null);}
 public int readAll(String admin,Set<String>roles){var page=list(admin,roles,null,PageRequest.of(0,10000));int updated=0;for(Response n:page)if(n.readAt()==null){read(admin,roles,n.id());updated++;}return updated;}
 public void create(UUID eventId,String type,String title,String message,String resourceType,String resourceId,String adminId,String role){if(notifications.existsBySourceEventId(eventId))return;var n=new AdminNotificationEntity();n.id=UUID.randomUUID();n.sourceEventId=eventId;n.type=type;n.title=title;n.message=message;n.resourceType=resourceType;n.resourceId=resourceId;n.adminId=adminId;n.targetRole=role;n.createdAt=Instant.now();n.expiresAt=n.createdAt.plus(90,java.time.temporal.ChronoUnit.DAYS);notifications.save(n);}
 @Scheduled(cron="${admin.notifications.retention-cron:0 20 3 * * *}")public void purge(){notifications.deleteByExpiresAtBefore(Instant.now());}
 private AdminNotificationEntity authorized(String admin,Set<String>roles,UUID id){var n=notifications.findById(id).orElseThrow();if(!admin.equals(n.adminId)&&!roles.contains(n.targetRole))throw new NoSuchElementException("Notification not found");return n;}private Response response(AdminNotificationEntity n,Instant readAt){return new Response(n.id,n.type,n.title,n.message,n.resourceType,n.resourceId,readAt,n.createdAt);}
}
