package com.yeyamo_mobile.api.partner_service.interfaces.rest;
import java.io.IOException;import java.util.*;import org.springframework.data.domain.*;import org.springframework.http.*;import org.springframework.security.core.Authentication;import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import com.yeyamo_mobile.api.partner_service.application.PartnerService;import com.yeyamo_mobile.api.partner_service.domain.model.*;import jakarta.validation.Valid;
@RestController@RequestMapping("/api/v1/partners")public class PartnerController{private final PartnerService service;public PartnerController(PartnerService s){service=s;}
 @PostMapping public ResponseEntity<PartnerResponse>create(@Valid@RequestBody PartnerRequest r,JwtAuthenticationToken auth,@RequestHeader(value="X-Correlation-ID",required=false)String c){Partner p=service.create(auth.getName(),r.legalName(),r.tradeName(),r.businessType(),r.registrationNumber(),r.taxId(),r.contactEmail(),r.contactPhone(),r.websiteUrl(),r.description(),c);return ResponseEntity.status(HttpStatus.CREATED).body(PartnerResponse.from(p));}
 @GetMapping("/me")public PartnerResponse me(Authentication a){return PartnerResponse.from(service.me(a.getName()));}
 @PutMapping("/me")public PartnerResponse update(@Valid@RequestBody PartnerRequest r,Authentication a,@RequestHeader(value="X-Correlation-ID",required=false)String c){return PartnerResponse.from(service.update(a.getName(),r.legalName(),r.tradeName(),r.businessType(),r.registrationNumber(),r.taxId(),r.contactEmail(),r.contactPhone(),r.websiteUrl(),r.description(),c));}
 @GetMapping("/me/documents")public List<DocumentResponse>documents(Authentication a){return service.myDocuments(a.getName()).stream().map(DocumentResponse::from).toList();}
 @PostMapping(value="/me/documents",consumes=MediaType.MULTIPART_FORM_DATA_VALUE)public ResponseEntity<DocumentResponse>upload(@RequestParam DocumentType type,@RequestPart("file")MultipartFile file,Authentication a,@RequestHeader(value="X-Correlation-ID",required=false)String c)throws IOException{return ResponseEntity.status(HttpStatus.CREATED).body(DocumentResponse.from(service.addDocument(a.getName(),type,file.getOriginalFilename(),file.getContentType(),file.getSize(),file.getInputStream(),c)));}
 @DeleteMapping("/me/documents/{id}")public ResponseEntity<Void>remove(@PathVariable UUID id,Authentication a,@RequestHeader(value="X-Correlation-ID",required=false)String c)throws IOException{service.removeDocument(a.getName(),id,c);return ResponseEntity.noContent().build();}
 @PostMapping("/me/submit")public PartnerResponse submit(Authentication a,@RequestHeader(value="X-Correlation-ID",required=false)String c){return PartnerResponse.from(service.submit(a.getName(),c));}
 @GetMapping("/{id}")public PublicPartnerResponse byId(@PathVariable UUID id){return PublicPartnerResponse.from(service.publicPartner(id));}
 @GetMapping public Page<PublicPartnerResponse>search(@RequestParam(defaultValue="")String q,Pageable pageable){return service.search(q,pageable).map(PublicPartnerResponse::from);}}
