package com.yeyamo_mobile.api.partner_service.interfaces.rest;
import com.yeyamo_mobile.api.partner_service.infrastructure.staff.*;import jakarta.validation.*;import jakarta.validation.constraints.*;import org.springframework.beans.factory.annotation.*;import org.springframework.http.*;import org.springframework.security.core.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.client.*;import java.util.*;
@RestController @RequestMapping("/api/v1/partners/{partnerId}/operations")public class PartnerOperationsController{
 private final PartnerStaffService access;private final PartnerBillingRepository billing;private final RestClient commerce;private final RestClient campaign;
 public PartnerOperationsController(PartnerStaffService a,PartnerBillingRepository b,@Value("${yeyamo.services.commerce-url:http://commerce-service:8087}")String c,@Value("${yeyamo.services.campaign-url:http://campaign-service:8080}")String d){access=a;billing=b;commerce=RestClient.create(c);campaign=RestClient.create(d);}
 public record BillingRequest(@Email String invoiceEmail,String billingAddress,String taxIdentifier,boolean purchaseOrderRequired){}
 @PutMapping("/billing-preferences")public PartnerBillingPreferences billing(@PathVariable UUID partnerId,@Valid@RequestBody BillingRequest r,Authentication a){require(partnerId,a,"partner:finance-view");PartnerBillingPreferences p=billing.findById(partnerId).orElseGet(PartnerBillingPreferences::new);p.partnerId=partnerId;p.invoiceEmail=r.invoiceEmail();p.billingAddress=r.billingAddress();p.taxIdentifier=r.taxIdentifier();p.purchaseOrderRequired=r.purchaseOrderRequired();return billing.save(p);}
 @GetMapping("/billing-preferences")public PartnerBillingPreferences billing(@PathVariable UUID partnerId,Authentication a){require(partnerId,a,"partner:finance-view");return billing.findById(partnerId).orElseGet(()->{PartnerBillingPreferences p=new PartnerBillingPreferences();p.partnerId=partnerId;return p;});}
 @GetMapping("/commercial-statistics")public Object stats(@PathVariable UUID partnerId,@RequestHeader(HttpHeaders.AUTHORIZATION)String auth,Authentication a){require(partnerId,a,"partner:analytics-view");return commerce.get().uri("/api/v1/commerce/admin/ledger/{id}",partnerId).header(HttpHeaders.AUTHORIZATION,auth).retrieve().body(Object.class);}
 @GetMapping("/advertising-credits")public Object credits(@PathVariable UUID partnerId,@RequestHeader(HttpHeaders.AUTHORIZATION)String auth,Authentication a){require(partnerId,a,"partner:campaign-view");return campaign.get().uri("/api/v1/campaigns/partners/{id}/credits/summary",partnerId).header(HttpHeaders.AUTHORIZATION,auth).retrieve().body(Object.class);}
 private void require(UUID p,Authentication a,String permission){if(!access.allowed(p,a.getName(),permission))throw new SecurityException("Permission denied");}}
