package com.yeyamo_mobile.api.partner_service.interfaces.rest;
import com.yeyamo_mobile.api.partner_service.infrastructure.staff.*;import jakarta.validation.*;import jakarta.validation.constraints.*;import org.springframework.security.core.*;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/v1/partners/{partnerId}/staff")public class PartnerStaffController{private final PartnerStaffService service;public PartnerStaffController(PartnerStaffService s){service=s;}public record RoleRequest(@NotBlank String code,@NotBlank String name,@NotEmpty Set<String>permissions){}public record InviteRequest(@NotBlank String contact,@NotNull UUID roleId){}public record AcceptRequest(@NotBlank String token){}
 @PostMapping("/roles")public PartnerRoleEntity role(@PathVariable UUID partnerId,@Valid@RequestBody RoleRequest r,Authentication a){return service.role(partnerId,a.getName(),r.code(),r.name(),r.permissions());}
 @PostMapping("/invitations")public PartnerStaffService.InvitationResult invite(@PathVariable UUID partnerId,@Valid@RequestBody InviteRequest r,Authentication a){return service.invite(partnerId,a.getName(),r.contact(),r.roleId());}
 @PostMapping("/invitations/accept")public PartnerMembershipEntity accept(@PathVariable UUID partnerId,@Valid@RequestBody AcceptRequest r,Authentication a){return service.accept(partnerId,r.token(),a.getName());}
 @DeleteMapping("/{userId}")public void revoke(@PathVariable UUID partnerId,@PathVariable String userId,Authentication a){service.revoke(partnerId,a.getName(),userId);}
 @PutMapping("/{userId}/role/{roleId}")public void role(@PathVariable UUID partnerId,@PathVariable String userId,@PathVariable UUID roleId,Authentication a){service.changeRole(partnerId,a.getName(),userId,roleId);}
 @GetMapping("/audit")public List<PartnerStaffAuditEntity> audit(@PathVariable UUID partnerId,Authentication a){return service.audit(partnerId,a.getName());}
 @GetMapping("/permissions/{permission}")public Map<String,Boolean> permission(@PathVariable UUID partnerId,@PathVariable String permission,Authentication a){return Map.of("allowed",service.allowed(partnerId,a.getName(),permission));}}
