CREATE SEQUENCE IF NOT EXISTS users_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS roles_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS oauth_accounts_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS refresh_tokens_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS user_profiles_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE IF NOT EXISTS users (
 id BIGINT PRIMARY KEY, phone VARCHAR(255) UNIQUE, email VARCHAR(255) UNIQUE,
 password_hash VARCHAR(255) NOT NULL, status VARCHAR(30) NOT NULL,
 created_at TIMESTAMP NOT NULL, last_login_at TIMESTAMP WITH TIME ZONE,
 email_verified_at TIMESTAMP WITH TIME ZONE
);
CREATE TABLE IF NOT EXISTS roles (id BIGINT PRIMARY KEY, code VARCHAR(40) NOT NULL UNIQUE, label VARCHAR(80) NOT NULL);
CREATE TABLE IF NOT EXISTS user_roles (user_id BIGINT NOT NULL REFERENCES users(id), role_id BIGINT NOT NULL REFERENCES roles(id), PRIMARY KEY(user_id,role_id));
CREATE TABLE IF NOT EXISTS oauth_accounts (id BIGINT PRIMARY KEY, user_id BIGINT REFERENCES users(id), provider VARCHAR(255), provider_user_id VARCHAR(255), UNIQUE(provider,provider_user_id));
CREATE TABLE IF NOT EXISTS refresh_tokens (id BIGINT PRIMARY KEY, user_id BIGINT REFERENCES users(id), token_hash VARCHAR(255) NOT NULL UNIQUE, expires_at TIMESTAMP NOT NULL, revoked_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS user_profiles (id BIGINT PRIMARY KEY, display_name VARCHAR(255), avatar_url VARCHAR(255), bio VARCHAR(255), language VARCHAR(30), user_id BIGINT REFERENCES users(id));
CREATE TABLE IF NOT EXISTS auth_outbox_events (id UUID PRIMARY KEY, aggregate_id VARCHAR(100) NOT NULL, event_type VARCHAR(100) NOT NULL, payload TEXT NOT NULL, occurred_at TIMESTAMP WITH TIME ZONE NOT NULL, published_at TIMESTAMP WITH TIME ZONE, attempts INTEGER NOT NULL DEFAULT 0, last_error VARCHAR(1000));
CREATE INDEX IF NOT EXISTS idx_auth_outbox_unpublished ON auth_outbox_events(occurred_at) WHERE published_at IS NULL;
CREATE TABLE IF NOT EXISTS auth_processed_events (event_id UUID PRIMARY KEY, event_type VARCHAR(100) NOT NULL, processed_at TIMESTAMP WITH TIME ZONE NOT NULL);
