ALTER TABLE stories
    ADD COLUMN caption_font_family VARCHAR(24) NOT NULL DEFAULT 'SYSTEM',
    ADD COLUMN caption_bold BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN caption_italic BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN caption_underline BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN caption_strikethrough BOOLEAN NOT NULL DEFAULT FALSE;
