spring.application.name=partner-service
spring.cloud.config.username=${CONFIG_SERVER_USERNAME}
spring.cloud.config.password=${CONFIG_SERVER_PASSWORD}
spring.config.import=configserver:${CONFIG_SERVER_URL:http://config-server:8080}
spring.cloud.config.fail-fast=true
spring.cloud.config.request-connect-timeout=10000
spring.cloud.config.request-read-timeout=30000
spring.cloud.config.retry.max-attempts=6
spring.cloud.config.retry.initial-interval=2000
spring.cloud.config.retry.max-interval=3000
spring.cloud.config.retry.multiplier=1.2
