package com.yeyamo_mobile.api.booking_service.application;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;import java.math.BigDecimal;import java.time.*;import java.util.*;import org.junit.jupiter.api.*;import com.yeyamo_mobile.api.booking_service.application.BookingDtos.CreateBooking;import com.yeyamo_mobile.api.booking_service.application.port.BookingOutboxPort;import com.yeyamo_mobile.api.booking_service.domain.*;import com.yeyamo_mobile.api.booking_service.infrastructure.persistence.*;
class BookingApplicationServiceTest{ActivitySlotRepository slots=mock(ActivitySlotRepository.class);BookingRepository bookings=mock(BookingRepository.class);PaymentSagaRepository sagas=mock(PaymentSagaRepository.class);CommandReceiptRepository receipts=mock(CommandReceiptRepository.class);BookingHistoryRepository history=mock(BookingHistoryRepository.class);BookingOutboxPort outbox=mock(BookingOutboxPort.class);BookingReferenceGenerator references=mock(BookingReferenceGenerator.class);BookingApplicationService service;
 @BeforeEach void setUp(){service=new BookingApplicationService(slots,bookings,sagas,receipts,history,outbox,references);when(bookings.save(any())).thenAnswer(i->i.getArgument(0));when(slots.save(any())).thenAnswer(i->i.getArgument(0));when(sagas.save(any())).thenAnswer(i->i.getArgument(0));when(references.next()).thenReturn("YY-ABC");}
 @Test void paidBookingReservesCapacityAndStartsSaga(){var slot=slot();when(slots.findLocked(slot.getId())).thenReturn(Optional.of(slot));var view=service.create("u1",new CreateBooking(slot.getId(),2,"mtn","+237690123456"),"key-1","c1","CM");assertEquals(BookingStatus.PENDING,view.status());assertEquals(2,slot.getReservedCount());var payload=org.mockito.ArgumentCaptor.forClass(Map.class);verify(outbox).append(eq("payment.commands"),eq("payment.authorization.requested"),anyString(),eq("c1"),payload.capture());assertEquals("mtn",payload.getValue().get("operator"));assertEquals("+237690123456",payload.getValue().get("phoneNumber"));assertEquals("CM",payload.getValue().get("country"));}
 @Test void paidBookingWithoutMobileMoneyDetailsIsRejected(){var slot=slot();when(slots.findLocked(slot.getId())).thenReturn(Optional.of(slot));var error=assertThrows(BookingException.class,()->service.create("u1",new CreateBooking(slot.getId(),1),"key-1","c1","CM"));assertEquals("PAYMENT_OPERATOR_REQUIRED",error.code());verifyNoInteractions(sagas);}
 @Test void paidBookingWithLegacyTokenWithoutCountryRequestsRefresh(){var slot=slot();when(slots.findLocked(slot.getId())).thenReturn(Optional.of(slot));var error=assertThrows(BookingException.class,()->service.create("u1",new CreateBooking(slot.getId(),1,"mtn","+237690123456"),"key-1","c1",null));assertEquals("TOKEN_REFRESH_REQUIRED",error.code());verifyNoInteractions(sagas);}
 @Test void freeBookingIsConfirmedImmediately(){var slot=slot(BigDecimal.ZERO);when(slots.findLocked(slot.getId())).thenReturn(Optional.of(slot));var view=service.create("u1",new CreateBooking(slot.getId(),1),"key-1","c1");assertEquals(BookingStatus.CONFIRMED,view.status());verifyNoInteractions(sagas);verify(outbox).append(eq("booking.events"),eq("booking.confirmed"),anyString(),eq("c1"),anyMap());}
 @Test void paymentFailureCompensatesAvailability(){var slot=slot();slot.reserve(2);var booking=BookingEntity.pending("R","u1",slot,2);var saga=PaymentSagaEntity.authorization(booking);when(bookings.findLocked(booking.getId())).thenReturn(Optional.of(booking));when(slots.findLocked(slot.getId())).thenReturn(Optional.of(slot));when(sagas.findByBookingId(booking.getId())).thenReturn(Optional.of(saga));service.paymentFailed(UUID.randomUUID(),booking.getId(),"declined","c1");assertEquals(BookingStatus.CANCELLED,booking.getStatus());assertEquals(0,slot.getReservedCount());assertEquals(SagaStatus.FAILED,saga.getStatus());}
 @Test void authorizedCancellationRequestsRefund(){var slot=slot();slot.reserve(1);var booking=BookingEntity.pending("R","u1",slot,1);booking.confirm();var saga=PaymentSagaEntity.authorization(booking);saga.authorized("pay-1");when(bookings.findLocked(booking.getId())).thenReturn(Optional.of(booking));when(slots.findLocked(slot.getId())).thenReturn(Optional.of(slot));when(sagas.findByBookingId(booking.getId())).thenReturn(Optional.of(saga));var view=service.cancel("u1",booking.getId(),"changed mind","k2","c1",false);assertEquals(PaymentStatus.REFUND_PENDING,view.paymentStatus());verify(outbox).append(eq("payment.commands"),eq("payment.refund.requested"),anyString(),eq("c1"),anyMap());}
 @Test void pendingCancellationRequestsAuthorizationCancellation(){var slot=slot();slot.reserve(1);var booking=BookingEntity.pending("R","u1",slot,1);var saga=PaymentSagaEntity.authorization(booking);when(bookings.findLocked(booking.getId())).thenReturn(Optional.of(booking));when(slots.findLocked(slot.getId())).thenReturn(Optional.of(slot));when(sagas.findByBookingId(booking.getId())).thenReturn(Optional.of(saga));service.cancel("u1",booking.getId(),"changed mind","k2","c1",false);assertEquals(SagaStatus.CANCELLATION_REQUESTED,saga.getStatus());verify(outbox).append(eq("payment.commands"),eq("payment.authorization.cancel.requested"),anyString(),eq("c1"),anyMap());}
 @Test void lateAuthorizationAfterCancellationTriggersCompensatingRefund(){var slot=slot();var booking=BookingEntity.pending("R","u1",slot,1);booking.cancel("changed mind");var saga=PaymentSagaEntity.authorization(booking);saga.cancellationRequested();when(bookings.findLocked(booking.getId())).thenReturn(Optional.of(booking));when(sagas.findByBookingId(booking.getId())).thenReturn(Optional.of(saga));service.paymentAuthorized(UUID.randomUUID(),booking.getId(),"pay-late","c1");assertEquals(PaymentStatus.REFUND_PENDING,booking.getPaymentStatus());assertEquals(SagaStatus.REFUND_REQUESTED,saga.getStatus());verify(outbox).append(eq("payment.commands"),eq("payment.refund.requested"),anyString(),eq("c1"),anyMap());}
 @Test void partnerCannotCloseAnotherPartnersSlot(){var slot=slot();when(slots.findLocked(slot.getId())).thenReturn(Optional.of(slot));assertEquals("BOOKING_FORBIDDEN",assertThrows(BookingException.class,()->service.closeSlot(slot.getId(),"partner-2","c1",false)).code());}
 @Test void partnerCanReadOwnBookingButNotAnotherPartnersBooking(){var slot=slot();var booking=BookingEntity.pending("R","customer",slot,1);when(bookings.findById(booking.getId())).thenReturn(Optional.of(booking));assertEquals(booking.getId(),service.get("partner-1",booking.getId(),false).id());assertEquals("BOOKING_FORBIDDEN",assertThrows(BookingException.class,()->service.get("partner-2",booking.getId(),false)).code());}
 @Test void partnerListIsConstrainedByAuthenticatedOwner(){var pageable=org.springframework.data.domain.PageRequest.of(0,20);when(bookings.findBySlotOwnerUserIdOrderByCreatedAtDesc(eq("partner-1"),any())).thenReturn(org.springframework.data.domain.Page.empty(pageable));service.partnerMine("partner-1",pageable);verify(bookings).findBySlotOwnerUserIdOrderByCreatedAtDesc(eq("partner-1"),any());}
 private ActivitySlotEntity slot(){return slot(new BigDecimal("10.00"));}private ActivitySlotEntity slot(BigDecimal price){return ActivitySlotEntity.create("a","partner-1",Instant.now().plusSeconds(3600),Instant.now().plusSeconds(7200),5,price,"EUR");}
}
