package com.yeyamo_mobile.api.moderation_trust_service.application;
import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import com.fasterxml.jackson.databind.ObjectMapper;
import com.yeyamo_mobile.api.moderation_trust_service.application.port.*;import com.yeyamo_mobile.api.moderation_trust_service.domain.model.*;import com.yeyamo_mobile.api.moderation_trust_service.domain.port.*;
@Service
public class ModerationService{
 private final ModerationReportRepository reports;private final TrustScoreRepository scores;private final ModerationAuditPort audit;private final ModerationOutboxPort outbox;private final ObjectMapper mapper;
 public ModerationService(ModerationReportRepository r,TrustScoreRepository s,ModerationAuditPort a,ModerationOutboxPort o,ObjectMapper m){reports=r;scores=s;audit=a;outbox=o;mapper=m;}
 @Transactional public ModerationReport report(TargetType type,String target,String owner,String reporter,ReportReason reason,String details,String correlation){
  if(reports.existsOpen(type,target,reporter))throw new ModerationException("REPORT_ALREADY_OPEN","An open report already exists for this target");
  ModerationReport saved=reports.save(ModerationReport.create(type,target,owner,reporter,reason,details));
  audit("REPORT_CREATED",saved.getId().toString(),reporter,correlation,Map.of("targetType",type,"targetId",target,"reason",reason));event("moderation.report.created",saved,reporter,correlation);return saved;}
 @Transactional public ModerationReport review(UUID id,String moderator,String correlation){ModerationReport r=required(id);r.startReview(moderator);r=reports.save(r);audit("REPORT_REVIEW_STARTED",id.toString(),moderator,correlation,Map.of());event("moderation.report.review_started",r,moderator,correlation);return r;}
 @Transactional public ModerationReport decide(UUID id,ReportStatus decision,String moderator,String resolution,String correlation){ModerationReport r=required(id);r.decide(decision,moderator,resolution);r=reports.save(r);
  if(decision==ReportStatus.APPROVED){String targetSubject=r.getTargetOwnerId()!=null?r.getTargetOwnerId():(r.getTargetType()==TargetType.USER?r.getTargetId():null);if(targetSubject!=null){TrustScore s=score(targetSubject);s.approvedAgainst();saveScore(s,moderator,correlation,"APPROVED_REPORT");}TrustScore reporter=score(r.getReporterId());reporter.validReporter();saveScore(reporter,moderator,correlation,"VALID_REPORTER");}
  else{TrustScore reporter=score(r.getReporterId());reporter.rejectedReporter();saveScore(reporter,moderator,correlation,"REJECTED_REPORTER");}
  audit("REPORT_"+decision,id.toString(),moderator,correlation,Map.of("resolution",resolution));event("moderation.report."+decision.name().toLowerCase(Locale.ROOT),r,moderator,correlation);return r;}
 @Transactional(readOnly=true)public ModerationReport get(UUID id){return required(id);}@Transactional(readOnly=true)public List<ModerationReport>list(ReportStatus status,String reporter,int limit){return reports.find(status,reporter,cap(limit));}
 @Transactional(readOnly=true)public TrustScore trust(String subject){return scores.findById(subject).orElseGet(()->TrustScore.initial(subject));}@Transactional(readOnly=true)public List<AuditEntry>audits(int limit){return audit.latest(cap(limit));}
 @Transactional public void recordExternal(String eventId,String type,String aggregate,String actor,String correlation,String producer){audit("EXTERNAL_EVENT_CONSUMED",aggregate,actor,correlation,Map.of("eventId",eventId,"eventType",type,"producer",producer));}
 private void saveScore(TrustScore s,String actor,String correlation,String reason){scores.save(s);audit("TRUST_SCORE_CHANGED",s.getSubjectId(),actor,correlation,Map.of("score",s.getScore(),"reason",reason));outbox.append("trust.score.changed","trust-score",s.getSubjectId(),actor,correlation,Map.of("subjectId",s.getSubjectId(),"score",s.getScore(),"reason",reason));}
 private TrustScore score(String id){return scores.findById(id).orElseGet(()->TrustScore.initial(id));}private ModerationReport required(UUID id){return reports.findById(id).orElseThrow(()->new ModerationException("REPORT_NOT_FOUND","Moderation report not found"));}
 private void event(String type,ModerationReport r,String actor,String correlation){Map<String,Object>p=new LinkedHashMap<>();p.put("reportId",r.getId());p.put("targetType",r.getTargetType());p.put("targetId",r.getTargetId());p.put("targetOwnerId",r.getTargetOwnerId());p.put("reporterId",r.getReporterId());p.put("status",r.getStatus());p.put("reason",r.getReason());p.put("resolution",r.getResolution());outbox.append(type,"moderation-report",r.getId().toString(),actor,correlation,p);}
 private void audit(String action,String id,String actor,String correlation,Map<String,Object> details){try{audit.append(AuditEntry.create(action,"MODERATION",id,actor,correlation,mapper.writeValueAsString(details)));}catch(Exception e){throw new IllegalStateException("Cannot serialize audit entry",e);}}private int cap(int n){return Math.max(1,Math.min(200,n));}
}
