package com.yeyamo_mobile.api.analytics_service.controller;
import java.time.*;import java.util.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.format.annotation.DateTimeFormat;import org.springframework.web.bind.annotation.*;import com.yeyamo_mobile.api.analytics_service.business.TerritorialAnalyticsService;
@RestController @RequestMapping("/api/v1/analytics/countries") public class TerritorialAnalyticsController {
 private final TerritorialAnalyticsService analytics;private final TerritorialAnalyticsAccess access;public TerritorialAnalyticsController(TerritorialAnalyticsService a,TerritorialAnalyticsAccess s){analytics=a;access=s;}
 @GetMapping @PreAuthorize("hasAnyRole('ADMIN','SUPER_ADMIN')") public List<TerritorialAnalyticsService.Activity> countries(@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate from,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate to,Authentication auth){var range=range(from,to);if(access.global(auth))return analytics.countries(range.from,range.to);return access.countries(auth).stream().flatMap(c->analytics.country(c,range.from,range.to).stream()).toList();}
 @GetMapping("/{countryCode}") @PreAuthorize("hasAnyRole('ADMIN','SUPER_ADMIN')") public List<TerritorialAnalyticsService.Activity> country(@PathVariable String countryCode,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate from,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate to,Authentication auth){access.requireCountry(auth,countryCode);var r=range(from,to);return analytics.country(countryCode,r.from,r.to);}
 @GetMapping("/{countryCode}/cities") @PreAuthorize("hasAnyRole('ADMIN','SUPER_ADMIN')") public List<TerritorialAnalyticsService.CityActivity> cities(@PathVariable String countryCode,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate from,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate to,Authentication auth){access.requireCountry(auth,countryCode);var r=range(from,to);return analytics.cities(countryCode,r.from,r.to);}
 @GetMapping("/{countryCode}/culture") @PreAuthorize("hasAnyRole('ADMIN','SUPER_ADMIN')") public List<TerritorialAnalyticsService.CultureActivity> culture(@PathVariable String countryCode,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate from,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate to,Authentication auth){access.requireCountry(auth,countryCode);var r=range(from,to);return analytics.culture(countryCode,r.from,r.to);}
 @GetMapping("/{countryCode}/artisans") @PreAuthorize("hasAnyRole('ADMIN','SUPER_ADMIN')") public List<TerritorialAnalyticsService.ArtisanActivity> artisans(@PathVariable String countryCode,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate from,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate to,Authentication auth){access.requireCountry(auth,countryCode);var r=range(from,to);return analytics.artisans(countryCode,r.from,r.to);}
 @GetMapping("/{countryCode}/revenue") @PreAuthorize("hasAnyRole('ADMIN','SUPER_ADMIN')") public List<TerritorialAnalyticsService.Revenue> revenue(@PathVariable String countryCode,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate from,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate to,Authentication auth){access.requireCountry(auth,countryCode);var r=range(from,to);return analytics.revenue(countryCode,r.from,r.to);}
 private Range range(LocalDate from,LocalDate to){LocalDate end=to==null?LocalDate.now(ZoneOffset.UTC):to;LocalDate start=from==null?end.minusDays(30):from;if(start.isAfter(end)||start.plusDays(366).isBefore(end))throw new IllegalArgumentException("Invalid date range");return new Range(start,end);}private record Range(LocalDate from,LocalDate to){}
}
