package com.yeyamo_mobile.api.partner_service.infrastructure.persistence;
import java.util.*;import org.springframework.data.domain.*;import org.springframework.stereotype.Repository;import com.yeyamo_mobile.api.partner_service.domain.model.*;import com.yeyamo_mobile.api.partner_service.domain.port.*;
@Repository public class JpaPartnerAdapter implements PartnerRepository,PartnerDocumentRepository{
 private final SpringPartnerRepository partners;private final SpringPartnerDocumentRepository documents;public JpaPartnerAdapter(SpringPartnerRepository p,SpringPartnerDocumentRepository d){partners=p;documents=d;}
 public Partner save(Partner p){return domain(partners.save(entity(p)));}public Optional<Partner>findById(UUID id){return partners.findById(id).map(this::domain);}public Optional<Partner>findByOwnerUserId(String id){return partners.findByOwnerUserId(id).map(this::domain);}public boolean existsByOwnerUserId(String id){return partners.existsByOwnerUserId(id);}public Page<Partner>searchApproved(String q,Pageable p){return partners.search(q==null?"":q.trim(),PartnerStatus.APPROVED,p).map(this::domain);}
 public PartnerDocument save(PartnerDocument d){return domain(documents.save(entity(d)));}public List<PartnerDocument>findByPartnerId(UUID id){return documents.findByPartnerIdOrderByUploadedAtDesc(id).stream().map(this::domain).toList();}public Optional<PartnerDocument>findDocumentById(UUID id){return documents.findById(id).map(this::domain);}public void delete(PartnerDocument d){documents.deleteById(d.id());}
 private PartnerEntity entity(Partner p){PartnerEntity e=new PartnerEntity();e.setId(p.getId());e.setOwnerUserId(p.getOwnerUserId());e.setLegalName(p.getLegalName());e.setTradeName(p.getTradeName());e.setBusinessType(p.getBusinessType());e.setRegistrationNumber(p.getRegistrationNumber());e.setTaxId(p.getTaxId());e.setContactEmail(p.getContactEmail());e.setContactPhone(p.getContactPhone());e.setWebsiteUrl(p.getWebsiteUrl());e.setDescription(p.getDescription());e.setStatus(p.getStatus());e.setReviewComment(p.getReviewComment());e.setRiskScore(p.getRiskScore());e.setPrimaryCountryCode(p.getPrimaryCountryCode());e.setOperatingCountries(new java.util.LinkedHashSet<>(p.getOperatingCountries()));e.setSubmittedAt(p.getSubmittedAt());e.setVerifiedAt(p.getVerifiedAt());e.setCreatedAt(p.getCreatedAt());e.setUpdatedAt(p.getUpdatedAt());e.setDeletedAt(p.getDeletedAt());e.setVersion(p.getVersion());return e;}
 private Partner domain(PartnerEntity e){Partner p=new Partner();p.setId(e.getId());p.setOwnerUserId(e.getOwnerUserId());p.setLegalName(e.getLegalName());p.setTradeName(e.getTradeName());p.setBusinessType(e.getBusinessType());p.setRegistrationNumber(e.getRegistrationNumber());p.setTaxId(e.getTaxId());p.setContactEmail(e.getContactEmail());p.setContactPhone(e.getContactPhone());p.setWebsiteUrl(e.getWebsiteUrl());p.setDescription(e.getDescription());p.setStatus(e.getStatus());p.setReviewComment(e.getReviewComment());p.setRiskScore(e.getRiskScore());p.setPrimaryCountryCode(e.getPrimaryCountryCode());p.setOperatingCountries(e.getOperatingCountries());p.setSubmittedAt(e.getSubmittedAt());p.setVerifiedAt(e.getVerifiedAt());p.setCreatedAt(e.getCreatedAt());p.setUpdatedAt(e.getUpdatedAt());p.setDeletedAt(e.getDeletedAt());p.setVersion(e.getVersion());return p;}
 private PartnerDocumentEntity entity(PartnerDocument d){PartnerDocumentEntity e=new PartnerDocumentEntity();e.setId(d.id());e.setPartnerId(d.partnerId());e.setDocumentType(d.documentType());e.setStorageKey(d.storageKey());e.setOriginalFilename(d.originalFilename());e.setContentType(d.contentType());e.setSizeBytes(d.sizeBytes());e.setUploadedAt(d.uploadedAt());return e;}private PartnerDocument domain(PartnerDocumentEntity e){return new PartnerDocument(e.getId(),e.getPartnerId(),e.getDocumentType(),e.getStorageKey(),e.getOriginalFilename(),e.getContentType(),e.getSizeBytes(),e.getUploadedAt());}
}
