spring.application.name=payment-service
spring.cloud.config.username=${CONFIG_SERVER_USERNAME}
spring.cloud.config.password=${CONFIG_SERVER_PASSWORD}
spring.config.import=configserver:${CONFIG_SERVER_URL:http://config-server:8080}
spring.cloud.config.fail-fast=true
