package com.yeyamo_mobile.api.partner_service.infrastructure.staff;
import com.yeyamo_mobile.api.partner_service.application.port.*;import com.yeyamo_mobile.api.partner_service.infrastructure.persistence.*;import org.springframework.data.redis.core.*;import org.springframework.stereotype.*;import org.springframework.transaction.annotation.*;import java.nio.charset.*;import java.security.*;import java.time.*;import java.time.temporal.*;import java.util.*;import java.util.concurrent.*;
@Service public class PartnerStaffService{
 public static final Set<String> ALLOWED=Set.of("partner:profile-manage","partner:place-manage","partner:event-manage","partner:campaign-manage","partner:campaign-view","partner:ticket-manage","partner:ticket-view","partner:ticket-scan","partner:staff-manage","partner:analytics-view","partner:finance-view");
 private final SpringPartnerRepository partners;private final PartnerRoleRepository roles;private final PartnerMembershipRepository memberships;private final PartnerInvitationRepository invitations;private final PartnerStaffAuditRepository audits;private final PartnerOutboxPort outbox;private final StringRedisTemplate redis;
 public PartnerStaffService(SpringPartnerRepository p,PartnerRoleRepository r,PartnerMembershipRepository m,PartnerInvitationRepository i,PartnerStaffAuditRepository a,PartnerOutboxPort o,StringRedisTemplate x){partners=p;roles=r;memberships=m;invitations=i;audits=a;outbox=o;redis=x;}
 public record InvitationResult(UUID id,String token,Instant expiresAt){}
 @Transactional public PartnerRoleEntity role(UUID partner,String actor,String code,String name,Set<String> permissions){owner(partner,actor);if(!ALLOWED.containsAll(permissions))throw new IllegalArgumentException("Unknown permission");PartnerRoleEntity r=new PartnerRoleEntity();r.partnerId=partner;r.code=code.toUpperCase(Locale.ROOT);r.name=name;r.permissions=String.join(",",new TreeSet<>(permissions));r=roles.save(r);audit(partner,actor,null,"ROLE_CREATED",r.code);return r;}
 @Transactional public InvitationResult invite(UUID partner,String actor,String contact,UUID roleId){ownerOrPermission(partner,actor,"partner:staff-manage");PartnerRoleEntity role=roles.findById(roleId).filter(r->r.partnerId.equals(partner)).orElseThrow();String token=UUID.randomUUID()+"."+UUID.randomUUID();PartnerInvitationEntity i=new PartnerInvitationEntity();i.id=UUID.randomUUID();i.partnerId=partner;i.contact=contact.trim().toLowerCase(Locale.ROOT);i.roleId=role.id;i.tokenHash=hash(token);i.expiresAt=Instant.now().plus(48,ChronoUnit.HOURS);i.status="PENDING";i.invitedBy=actor;i.createdAt=Instant.now();invitations.save(i);audit(partner,actor,null,"INVITED",i.contact);outbox.append("partner.staff.invited",partner,actor,i.id.toString(),Map.of("invitationId",i.id,"contact",i.contact,"roleId",role.id,"expiresAt",i.expiresAt));return new InvitationResult(i.id,token,i.expiresAt);}
 @Transactional public PartnerMembershipEntity accept(UUID expectedPartner,String token,String user){PartnerInvitationEntity i=invitations.findByTokenHash(hash(token)).orElseThrow();if(!i.partnerId.equals(expectedPartner))throw new SecurityException("Wrong partner");if(!"PENDING".equals(i.status)||!Instant.now().isBefore(i.expiresAt))throw new IllegalStateException("Invitation expired");PartnerMembershipEntity m=memberships.findByPartnerIdAndUserId(i.partnerId,user).orElseGet(PartnerMembershipEntity::new);m.id=m.id==null?UUID.randomUUID():m.id;m.partnerId=i.partnerId;m.userId=user;m.roleId=i.roleId;m.status="ACTIVE";m.invitedBy=i.invitedBy;m.invitedAt=i.createdAt;m.acceptedAt=Instant.now();memberships.save(m);i.status="ACCEPTED";i.acceptedAt=m.acceptedAt;invitations.save(i);invalidate(i.partnerId,user);audit(i.partnerId,user,user,"ACCEPTED",null);outbox.append("partner.staff.accepted",i.partnerId,user,i.id.toString(),Map.of("membershipId",m.id,"userId",user,"roleId",m.roleId));return m;}
 @Transactional public void changeRole(UUID partner,String actor,String user,UUID roleId){ownerOrPermission(partner,actor,"partner:staff-manage");PartnerRoleEntity r=roles.findById(roleId).filter(x->x.partnerId.equals(partner)).orElseThrow();PartnerMembershipEntity m=memberships.findByPartnerIdAndUserId(partner,user).filter(x->"ACTIVE".equals(x.status)).orElseThrow();m.roleId=r.id;memberships.save(m);invalidate(partner,user);audit(partner,actor,user,"ROLE_CHANGED",r.code);outbox.append("partner.staff.role.changed",partner,actor,m.id.toString(),Map.of("membershipId",m.id,"userId",user,"roleId",r.id));}
 @Transactional public void revoke(UUID partner,String actor,String user){ownerOrPermission(partner,actor,"partner:staff-manage");if(partners.findById(partner).orElseThrow().getOwnerUserId().equals(user))throw new IllegalStateException("Owner transfer required");PartnerMembershipEntity m=memberships.findByPartnerIdAndUserId(partner,user).orElseThrow();m.status="REVOKED";m.revokedAt=Instant.now();memberships.save(m);invalidate(partner,user);audit(partner,actor,user,"REVOKED",null);outbox.append("partner.staff.revoked",partner,actor,m.id.toString(),Map.of("membershipId",m.id,"userId",user));}
 @Transactional(readOnly=true)public boolean allowed(UUID partner,String user,String permission){if(!ALLOWED.contains(permission))return false;if(partners.findById(partner).map(p->p.getOwnerUserId().equals(user)).orElse(false))return true;String key="partner:perm:"+partner+":"+user+":"+permission;try{String cached=redis.opsForValue().get(key);if(cached!=null)return Boolean.parseBoolean(cached);}catch(RuntimeException ignored){}boolean value=memberships.findByPartnerIdAndUserId(partner,user).filter(m->"ACTIVE".equals(m.status)).flatMap(m->roles.findById(m.roleId)).map(r->r.permissionSet().contains(permission)).orElse(false);try{redis.opsForValue().set(key,String.valueOf(value),30,TimeUnit.SECONDS);}catch(RuntimeException ignored){}return value;}
 @Transactional(readOnly=true)public List<PartnerStaffAuditEntity> audit(UUID p,String actor){ownerOrPermission(p,actor,"partner:staff-manage");return audits.findByPartnerIdOrderByOccurredAtDesc(p);}private void audit(UUID p,String a,String t,String action,String details){PartnerStaffAuditEntity e=new PartnerStaffAuditEntity();e.id=UUID.randomUUID();e.partnerId=p;e.actorUserId=a;e.targetUserId=t;e.action=action;e.details=details;e.occurredAt=Instant.now();audits.save(e);}private void owner(UUID p,String a){if(!partners.findById(p).orElseThrow().getOwnerUserId().equals(a))throw new SecurityException("Owner required");}private void ownerOrPermission(UUID p,String a,String x){if(!allowed(p,a,x))throw new SecurityException("Permission denied");}private void invalidate(UUID p,String u){try{Set<String>keys=redis.keys("partner:perm:"+p+":"+u+":*");if(keys!=null&&!keys.isEmpty())redis.delete(keys);}catch(RuntimeException ignored){}}private String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
