package com.yeyamo_mobile.api.culture_service.application;
import static com.yeyamo_mobile.api.culture_service.domain.CultureEnums.*;import com.yeyamo_mobile.api.culture_service.domain.*;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.time.*;import java.util.*;
public final class CultureDtos {private CultureDtos(){}
 public record TranslationRequest(@NotBlank String languageCode,@NotBlank String title,String summary,String body){}
 public record ProverbDetailsRequest(@NotBlank String literalTranslation,@NotBlank String meaning,@NotBlank String originLanguageCode,@Size(max=2048) String audioUrl){}
 public record RecipeIngredientRequest(@NotBlank@Size(max=255) String name,@Size(max=80) String quantity,@Size(max=80) String unit){}
 public record RecipeStepRequest(@NotBlank String instruction){}
 public record RecipeDetailsRequest(@NotEmpty@Valid List<RecipeIngredientRequest> ingredients,@NotEmpty@Valid List<RecipeStepRequest> steps,@Positive Integer prepTimeMinutes,@Positive Integer servings){}
 public record ContentRequest(@NotNull ContentType type,@NotBlank String slug,@NotBlank String primaryLanguageCode,@NotBlank@Size(min=2,max=2)String countryCode,String adminLevel1Id,String adminLevel2Id,String cityId,String localityId,String communityName,@NotNull ContributorType contributorType,@NotNull SourceType sourceType,@NotNull SensitivityLevel sensitivityLevel,@NotNull Visibility visibility,@NotNull@Valid TranslationRequest translation,@Valid ProverbDetailsRequest proverbDetails,@Valid RecipeDetailsRequest recipeDetails){}
 public record ProverbDetailsResponse(String literalTranslation,String meaning,String originLanguageCode,String audioUrl){public static ProverbDetailsResponse from(ProverbDetailsEntity d){return d==null?null:new ProverbDetailsResponse(d.getLiteralTranslation(),d.getMeaning(),d.getOriginLanguage().getCode(),d.getAudioUrl());}}
 public record RecipeIngredientResponse(String name,String quantity,String unit){public static RecipeIngredientResponse from(RecipeDetailsEntity.RecipeIngredient i){return new RecipeIngredientResponse(i.getName(),i.getQuantity(),i.getUnit());}}
 public record RecipeStepResponse(String instruction){public static RecipeStepResponse from(RecipeDetailsEntity.RecipeStep s){return new RecipeStepResponse(s.getInstruction());}}
 public record RecipeDetailsResponse(List<RecipeIngredientResponse> ingredients,List<RecipeStepResponse> steps,Integer prepTimeMinutes,Integer servings){public static RecipeDetailsResponse from(RecipeDetailsEntity d){return d==null?null:new RecipeDetailsResponse(d.getIngredients().stream().map(RecipeIngredientResponse::from).toList(),d.getSteps().stream().map(RecipeStepResponse::from).toList(),d.getPrepTimeMinutes(),d.getServings());}}
 public record ContentResponse(UUID id,ContentType type,String slug,ContentStatus status,Visibility visibility,String primaryLanguageCode,String countryCode,String adminLevel1Id,String adminLevel2Id,String cityId,String localityId,String communityName,String createdBy,ContributorType contributorType,SourceType sourceType,VerificationStatus verificationStatus,SensitivityLevel sensitivityLevel,Instant createdAt,Instant updatedAt,Instant publishedAt,long version,ProverbDetailsResponse proverbDetails,RecipeDetailsResponse recipeDetails){public static ContentResponse from(CultureContent c){return new ContentResponse(c.getId(),c.getType(),c.getSlug(),c.getStatus(),c.getVisibility(),c.getPrimaryLanguageCode(),c.getCountryCode(),c.getAdminLevel1Id(),c.getAdminLevel2Id(),c.getCityId(),c.getLocalityId(),c.getCommunityName(),c.getCreatedBy(),c.getContributorType(),c.getSourceType(),c.getVerificationStatus(),c.getSensitivityLevel(),c.getCreatedAt(),c.getUpdatedAt(),c.getPublishedAt(),c.getVersion(),ProverbDetailsResponse.from(c.getProverbDetails()),RecipeDetailsResponse.from(c.getRecipeDetails()));}}
 public record TranslationResponse(UUID id,String languageCode,String title,String summary,String body,String translatorId,TranslationStatus status,Instant createdAt){public static TranslationResponse from(CultureTranslation t){return new TranslationResponse(t.getId(),t.getLanguageCode(),t.getTitle(),t.getSummary(),t.getBody(),t.getTranslatorId(),t.getStatus(),t.getCreatedAt());}}
 public record StatusRequest(@NotNull ContentStatus status,boolean verified,String reason){}
 public record ReviewRequest(@NotNull ContentStatus decision,boolean verified,@NotBlank String reason){}
 public record LanguageResponse(String code,String name,String nativeName,List<String> countryCodes,String writingSystem,LanguageStatus status,String description,Long speakerEstimate,boolean verified){public static LanguageResponse from(Language l){return new LanguageResponse(l.getCode(),l.getName(),l.getNativeName(),l.getCountryCodes(),l.getWritingSystem(),l.getStatus(),l.getDescription(),l.getSpeakerEstimate(),l.isVerified());}}
 public record LessonSummary(UUID id,String languageCode,UUID topicId,String title,String description,int difficulty,int estimatedMinutes,LessonStatus status,int displayOrder){public static LessonSummary from(LanguageLesson l){return new LessonSummary(l.getId(),l.getLanguageCode(),l.getTopicId(),l.getTitle(),l.getDescription(),l.getDifficulty(),l.getEstimatedMinutes(),l.getStatus(),l.getDisplayOrder());}}
 public record LessonItemResponse(UUID id,String phrase,String translation,String transcription,String phonetic,UUID audioMediaId,UUID imageMediaId,String culturalContext,int difficulty,String examples,int displayOrder){public static LessonItemResponse from(LanguageLessonItem i){return new LessonItemResponse(i.getId(),i.getPhrase(),i.getTranslation(),i.getTranscription(),i.getPhonetic(),i.getAudioMediaId(),i.getImageMediaId(),i.getCulturalContext(),i.getDifficulty(),i.getExamples(),i.getDisplayOrder());}}
 public record ExerciseResponse(UUID id,ExerciseType type,String prompt,String optionsJson,int displayOrder){public static ExerciseResponse from(LanguageExercise e){return new ExerciseResponse(e.getId(),e.getType(),e.getPrompt(),e.getOptionsJson(),e.getDisplayOrder());}}
 public record LessonDetail(LessonSummary lesson,List<LessonItemResponse> items,List<ExerciseResponse> exercises){}
 public record AttemptRequest(@NotNull UUID exerciseId,String answerText,UUID mediaId){}
 public record AttemptResponse(UUID attemptId,Boolean correct,boolean manualReviewRequired){}
 public record CompleteRequest(@Min(0)@Max(100)int score,@NotBlank String idempotencyKey){}
 public record ProgressResponse(UUID id,String userId,String languageCode,UUID lessonId,Instant startedAt,Instant completedAt,Integer score,int attemptCount){public static ProgressResponse from(LanguageProgress p){return new ProgressResponse(p.getId(),p.getUserId(),p.getLanguageCode(),p.getLessonId(),p.getStartedAt(),p.getCompletedAt(),p.getScore(),p.getAttemptCount());}}
}
