package com.yeyamo_mobile.api.culture_service.application;
import static com.yeyamo_mobile.api.culture_service.application.CultureDtos.*;import static com.yeyamo_mobile.api.culture_service.domain.CultureEnums.*;import com.yeyamo.foundation.domain.*;import com.yeyamo_mobile.api.culture_service.domain.*;import com.yeyamo_mobile.api.culture_service.infrastructure.persistence.CultureRepositories.*;import jakarta.persistence.criteria.Predicate;import java.time.*;import java.util.*;import org.springframework.data.domain.*;import org.springframework.data.jpa.domain.Specification;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service @Transactional public class CultureContentService{
 private final Contents contents;private final Translations translations;private final CultureEventPublisher events;
 public CultureContentService(Contents c,Translations t,CultureEventPublisher e){contents=c;translations=t;events=e;}
 @Transactional(readOnly=true) public Page<ContentResponse> publicList(ContentType type,String country,String area,String city,String language,String community,Boolean verified,String search,Pageable pageable){Specification<CultureContent> spec=(root,q,cb)->{List<Predicate> p=new ArrayList<>();p.add(cb.equal(root.get("status"),ContentStatus.PUBLISHED));p.add(cb.equal(root.get("visibility"),Visibility.PUBLIC));p.add(root.get("sensitivityLevel").in(SensitivityLevel.PUBLIC,SensitivityLevel.CONTEXT_REQUIRED));if(type!=null)p.add(cb.equal(root.get("type"),type));if(text(country)!=null)p.add(cb.equal(root.get("countryCode"),country.toUpperCase()));if(text(area)!=null)p.add(cb.equal(root.get("adminLevel1Id"),area));if(text(city)!=null)p.add(cb.equal(root.get("cityId"),city));if(text(language)!=null)p.add(cb.equal(root.get("primaryLanguageCode"),new LanguageReference(language).languageCode()));if(text(community)!=null)p.add(cb.equal(root.get("communityName"),community));if(Boolean.TRUE.equals(verified))p.add(cb.equal(root.get("verificationStatus"),VerificationStatus.VERIFIED));if(text(search)!=null){String like="%"+search.trim().toLowerCase()+"%";p.add(cb.or(cb.like(cb.lower(root.get("slug")),like),cb.like(cb.lower(root.get("communityName")),like)));}return cb.and(p.toArray(Predicate[]::new));};return contents.findAll(spec,pageable).map(ContentResponse::from);}
 @Transactional(readOnly=true) public ContentResponse publicGet(UUID id){return ContentResponse.from(contents.findByIdAndStatusAndVisibility(id,ContentStatus.PUBLISHED,Visibility.PUBLIC).filter(c->c.getSensitivityLevel()!=SensitivityLevel.SACRED&&c.getSensitivityLevel()!=SensitivityLevel.COMMUNITY_RESTRICTED).orElseThrow(()->notFound()));}
 @Transactional(readOnly=true) public List<TranslationResponse> publicTranslations(UUID id){publicGet(id);return translations.findByContentIdOrderByLanguageCode(id).stream().filter(t->t.getStatus()==TranslationStatus.VERIFIED).map(TranslationResponse::from).toList();}
 public ContentResponse create(ContentRequest request,String actor,boolean admin){validate(request);if(contents.existsBySlug(request.slug()))throw new CultureException("CULTURE_SLUG_EXISTS","Ce slug existe déjà",HttpStatus.CONFLICT);CultureContent content=CultureContent.create(request.type(),request.slug().trim(),new LanguageReference(request.primaryLanguageCode()).languageCode(),new CountryReference(request.countryCode()).countryCode(),actor,admin?ContributorType.ADMIN:request.contributorType(),request.sourceType(),request.sensitivityLevel(),request.visibility());content.updateLocation(request.adminLevel1Id(),request.adminLevel2Id(),request.cityId(),request.localityId(),request.communityName());contents.save(content);TranslationRequest tr=request.translation();translations.save(CultureTranslation.create(content.getId(),new LanguageReference(tr.languageCode()).languageCode(),tr.title(),tr.summary(),tr.body(),actor));events.publish("CultureContentCreated",content.getId(),Map.of("contentId",content.getId(),"type",content.getType(),"countryCode",content.getCountryCode()));events.publish("CultureTranslationAdded",content.getId(),Map.of("contentId",content.getId(),"languageCode",tr.languageCode()));return ContentResponse.from(content);}
 public ContentResponse update(UUID id,ContentRequest request,String actor,boolean admin){CultureContent content=require(id);if(!admin&&!content.getCreatedBy().equals(actor))throw new CultureException("FORBIDDEN","Contribution inaccessible",HttpStatus.FORBIDDEN);content.updateLocation(request.adminLevel1Id(),request.adminLevel2Id(),request.cityId(),request.localityId(),request.communityName());events.publish("CultureContentUpdated",id,Map.of("contentId",id));return ContentResponse.from(content);}
 public ContentResponse submit(UUID id,String actor){CultureContent c=require(id);try{c.submit(actor);}catch(SecurityException e){throw new CultureException("FORBIDDEN",e.getMessage(),HttpStatus.FORBIDDEN);}events.publish("CultureContributionSubmitted",id,Map.of("contentId",id,"contributorId",actor));return ContentResponse.from(c);}
 public ContentResponse status(UUID id,StatusRequest request){CultureContent c=require(id);if(request.verified())c.markVerified();c.changeStatus(request.status());String event=switch(request.status()){case PUBLISHED->"CultureContentPublished";case ARCHIVED->"CultureContentArchived";default->"CultureContentUpdated";};events.publish(event,id,Map.of("contentId",id,"status",request.status()));return ContentResponse.from(c);}
 public ContentResponse review(UUID id,ReviewRequest request){CultureContent c=require(id);if(c.getStatus()==ContentStatus.SUBMITTED)c.changeStatus(ContentStatus.UNDER_REVIEW);if(request.verified())c.markVerified();if(!Set.of(ContentStatus.APPROVED,ContentStatus.CORRECTIONS_REQUIRED,ContentStatus.REJECTED).contains(request.decision()))throw new CultureException("INVALID_REVIEW_DECISION","Décision invalide",HttpStatus.BAD_REQUEST);c.changeStatus(request.decision());if(request.decision()==ContentStatus.APPROVED)events.publish("CultureContributionApproved",id,Map.of("contentId",id));return ContentResponse.from(c);}
 @Transactional(readOnly=true) public Page<ContentResponse> mine(String actor,Pageable p){return contents.findByCreatedBy(actor,p).map(ContentResponse::from);}@Transactional(readOnly=true)public ContentResponse owned(UUID id,String actor){CultureContent c=require(id);if(!c.getCreatedBy().equals(actor))throw new CultureException("FORBIDDEN","Contribution inaccessible",HttpStatus.FORBIDDEN);return ContentResponse.from(c);}public void deleteDraft(UUID id,String actor){CultureContent c=require(id);if(!c.getCreatedBy().equals(actor))throw new CultureException("FORBIDDEN","Contribution inaccessible",HttpStatus.FORBIDDEN);if(c.getStatus()!=ContentStatus.DRAFT)throw new CultureException("INVALID_STATE","Seul un brouillon peut être supprimé",HttpStatus.CONFLICT);contents.delete(c);}
 @Transactional(readOnly=true)public Page<ContentResponse> adminList(Pageable p){return contents.findAll(p).map(ContentResponse::from);}@Transactional(readOnly=true)public ContentResponse adminGet(UUID id){return ContentResponse.from(require(id));}
 @Transactional(readOnly=true)public Page<ContentResponse> adminContributions(Pageable p){return contents.findByContributorTypeNot(ContributorType.ADMIN,p).map(ContentResponse::from);}public TranslationResponse verifyTranslation(UUID id){CultureTranslation translation=translations.findById(id).orElseThrow(()->new CultureException("TRANSLATION_NOT_FOUND","Traduction introuvable",HttpStatus.NOT_FOUND));translation.verify();events.publish("CultureTranslationVerified",translation.getContentId(),Map.of("contentId",translation.getContentId(),"translationId",id,"languageCode",translation.getLanguageCode()));return TranslationResponse.from(translation);}
 private CultureContent require(UUID id){return contents.findById(id).orElseThrow(this::notFound);}private CultureException notFound(){return new CultureException("CULTURE_CONTENT_NOT_FOUND","Contenu culturel introuvable",HttpStatus.NOT_FOUND);}private void validate(ContentRequest r){new CountryReference(r.countryCode());new LanguageReference(r.primaryLanguageCode());if(r.sensitivityLevel()==SensitivityLevel.SACRED&&r.visibility()==Visibility.PUBLIC){throw new CultureException("SENSITIVE_VISIBILITY_INVALID","Un contenu sacré ne peut pas être public avant validation",HttpStatus.BAD_REQUEST);}}private static String text(String s){return s==null||s.isBlank()?null:s;}
}
