package com.yeyamo_mobile.api.culture_service.application;
import static com.yeyamo_mobile.api.culture_service.application.CultureDtos.*;import static com.yeyamo_mobile.api.culture_service.domain.CultureEnums.*;import com.yeyamo.foundation.domain.*;import com.yeyamo_mobile.api.culture_service.domain.*;import com.yeyamo_mobile.api.culture_service.infrastructure.persistence.CultureRepositories.*;import java.time.*;import java.util.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service @Transactional public class LanguageLearningService{
 private final Languages languages;private final Lessons lessons;private final Items items;private final Exercises exercises;private final Progress progress;private final Attempts attempts;private final DailyWords dailyWords;private final Contents contents;private final CultureEventPublisher events;
 public LanguageLearningService(Languages l,Lessons ls,Items i,Exercises e,Progress p,Attempts a,DailyWords d,Contents c,CultureEventPublisher ev){languages=l;lessons=ls;items=i;exercises=e;progress=p;attempts=a;dailyWords=d;contents=c;events=ev;}
 @Transactional(readOnly=true)public List<LanguageResponse> languages(){return languages.findByStatusInOrderByName(List.of(LanguageStatus.ACTIVE,LanguageStatus.BETA)).stream().map(LanguageResponse::from).toList();}@Transactional(readOnly=true)public LanguageResponse language(String code){return LanguageResponse.from(requireLanguage(code));}@Transactional(readOnly=true)public List<LessonSummary> lessons(String code){Language l=requireLanguage(code);return lessons.findByLanguageCodeAndStatusOrderByDisplayOrder(l.getCode(),LessonStatus.PUBLISHED).stream().map(LessonSummary::from).toList();}
 @Transactional(readOnly=true)public LessonDetail lesson(UUID id){LanguageLesson l=requireLesson(id);return new LessonDetail(LessonSummary.from(l),items.findByLessonIdOrderByDisplayOrder(id).stream().map(LessonItemResponse::from).toList(),exercises.findByLessonIdOrderByDisplayOrder(id).stream().map(ExerciseResponse::from).toList());}
 public ProgressResponse start(UUID lessonId,String actor){LanguageLesson lesson=requireLesson(lessonId);LanguageProgress p=progress.findByUserIdAndLessonId(actor,lessonId).orElseGet(()->progress.save(LanguageProgress.start(actor,lesson.getLanguageCode(),lessonId)));events.publish("LanguageLessonStarted",lessonId,Map.of("lessonId",lessonId,"userId",actor));return ProgressResponse.from(p);}
 public AttemptResponse attempt(UUID lessonId,AttemptRequest request,String actor){requireLesson(lessonId);LanguageExercise exercise=exercises.findById(request.exerciseId()).filter(e->e.getLessonId().equals(lessonId)).orElseThrow(()->new CultureException("EXERCISE_NOT_FOUND","Exercice introuvable",HttpStatus.NOT_FOUND));boolean pronunciation=exercise.getType()==ExerciseType.PRONUNCIATION_SUBMISSION;if(pronunciation&&request.mediaId()==null)throw new CultureException("MEDIA_REQUIRED","La prononciation doit référencer un mediaId",HttpStatus.BAD_REQUEST);Boolean correct=pronunciation?null:exercise.correct(request.answerText());LanguageAttempt saved=attempts.save(LanguageAttempt.create(actor,lessonId,exercise.getId(),request.answerText(),request.mediaId(),correct));LanguageProgress p=progress.findByUserIdAndLessonId(actor,lessonId).orElseGet(()->progress.save(LanguageProgress.start(actor,requireLesson(lessonId).getLanguageCode(),lessonId)));p.attempted();events.publish(pronunciation?"PronunciationSubmitted":"LanguageExerciseCompleted",lessonId,Map.of("lessonId",lessonId,"exerciseId",exercise.getId(),"userId",actor));return new AttemptResponse(saved.getId(),correct,pronunciation);}
 public ProgressResponse complete(UUID lessonId,CompleteRequest request,String actor){requireLesson(lessonId);LanguageProgress p=progress.findByUserIdAndLessonId(actor,lessonId).orElseThrow(()->new CultureException("LESSON_NOT_STARTED","La leçon doit être démarrée",HttpStatus.CONFLICT));if(p.complete(request.score()))events.publish("LanguageLessonCompleted",lessonId,Map.of("lessonId",lessonId,"userId",actor,"score",request.score(),"idempotencyKey",request.idempotencyKey()));return ProgressResponse.from(p);}
 @Transactional(readOnly=true)public List<ProgressResponse> progress(String actor,String language){return (language==null?progress.findByUserIdOrderByStartedAtDesc(actor):progress.findByUserIdAndLanguageCodeOrderByStartedAtDesc(actor,new LanguageReference(language).languageCode())).stream().map(ProgressResponse::from).toList();}
 public CultureDtos.ContentResponse dailyWord(String country,String language,String actor){String cc=new CountryReference(country).countryCode();String lc=language==null?null:new LanguageReference(language).languageCode();DailyWordSelection selection=(lc==null?dailyWords.findFirstBySelectionDateAndCountryCodeAndLanguageCodeIsNull(LocalDate.now(ZoneOffset.UTC),cc):dailyWords.findBySelectionDateAndCountryCodeAndLanguageCode(LocalDate.now(ZoneOffset.UTC),cc,lc)).orElseThrow(()->new CultureException("DAILY_WORD_NOT_CONFIGURED","Mot du jour non configuré",HttpStatus.NOT_FOUND));CultureContent content=contents.findByIdAndStatusAndVisibility(selection.getContentId(),ContentStatus.PUBLISHED,Visibility.PUBLIC).orElseThrow(()->new CultureException("DAILY_WORD_NOT_AVAILABLE","Mot du jour indisponible",HttpStatus.NOT_FOUND));events.publish("DailyWordViewed",content.getId(),Map.of("contentId",content.getId(),"countryCode",cc,"viewerId",actor==null?"anonymous":actor));return CultureDtos.ContentResponse.from(content);}
 private Language requireLanguage(String code){String normalized=new LanguageReference(code).languageCode();return languages.findById(normalized).filter(Language::available).orElseThrow(()->new CultureException("LANGUAGE_NOT_AVAILABLE","Langue indisponible",HttpStatus.NOT_FOUND));}private LanguageLesson requireLesson(UUID id){LanguageLesson l=lessons.findById(id).filter(v->v.getStatus()==LessonStatus.PUBLISHED).orElseThrow(()->new CultureException("LESSON_NOT_FOUND","Leçon introuvable",HttpStatus.NOT_FOUND));requireLanguage(l.getLanguageCode());return l;}
}
