package com.yeyamo_mobile.api.referral_service.application;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;import java.util.*;import org.junit.jupiter.api.*;import com.yeyamo_mobile.api.referral_service.application.port.*;import com.yeyamo_mobile.api.referral_service.domain.*;import com.yeyamo_mobile.api.referral_service.infrastructure.persistence.*;
class ReferralApplicationServiceTest{
 ReferralCodeRepository codes=mock(ReferralCodeRepository.class);ReferralInvitationRepository invitations=mock(ReferralInvitationRepository.class);ReferralAttributionRepository attributions=mock(ReferralAttributionRepository.class);ReferralRewardRepository rewards=mock(ReferralRewardRepository.class);ReferralHistoryRepository history=mock(ReferralHistoryRepository.class);ReferralCodeGenerator generator=mock(ReferralCodeGenerator.class);HashingService hashing=new HashingService();AntiFraudService fraud=mock(AntiFraudService.class);FraudCounterPort counter=mock(FraudCounterPort.class);ReferralOutboxPort outbox=mock(ReferralOutboxPort.class);ReferralApplicationService service;
 @BeforeEach void setUp(){service=new ReferralApplicationService(codes,invitations,attributions,rewards,history,generator,hashing,fraud,counter,outbox,100,50);}
 @Test void createsUniqueCode(){when(generator.next()).thenReturn("ABC123");when(codes.findByCodeIgnoreCase("ABC123")).thenReturn(Optional.empty());when(codes.save(any())).thenAnswer(i->i.getArgument(0));var view=service.createCode("owner",5,null,"c1");assertEquals("ABC123",view.code());verify(outbox).append(eq("referral.code.created"),anyString(),eq("c1"),anyMap());}
 @Test void directCodeCreatesPendingAttribution(){var code=ReferralCodeEntity.create("ABC","owner",2,null);when(codes.findLockedByCode("ABC")).thenReturn(Optional.of(code));when(codes.save(any())).thenAnswer(i->i.getArgument(0));when(attributions.save(any())).thenAnswer(i->i.getArgument(0));var result=service.redeem("friend","ABC","device","c1");assertEquals(AttributionStatus.PENDING_QUALIFICATION,result.status());assertEquals(1,code.getUsageCount());verify(fraud).validate(eq(code),eq("friend"),anyString());}
 @Test void missionCompletionRewardsBothParties(){var code=ReferralCodeEntity.create("ABC","owner",2,null);var attribution=ReferralAttributionEntity.create(code,null,"friend",AttributionSource.DIRECT_CODE,null);when(attributions.findByReferredUserIdAndStatus("friend",AttributionStatus.PENDING_QUALIFICATION)).thenReturn(List.of(attribution));when(rewards.existsByAttributionIdAndBeneficiaryType(any(),any())).thenReturn(false);when(rewards.save(any())).thenAnswer(i->i.getArgument(0));service.onMissionCompleted(UUID.randomUUID(),"friend","c1");assertEquals(AttributionStatus.REWARDED,attribution.getStatus());verify(rewards,times(2)).save(any());verify(outbox,times(2)).append(eq("referral.reward.granted"),anyString(),eq("c1"),anyMap());verify(outbox).append(eq("referral.completed"),anyString(),eq("c1"),anyMap());}
 @Test void invitationDoesNotStoreRawEmail(){var code=ReferralCodeEntity.create("ABC","owner",2,null);when(codes.findLockedByCode("ABC")).thenReturn(Optional.of(code));when(invitations.save(any())).thenAnswer(i->i.getArgument(0));var view=service.invite("owner","ABC","Alice@Example.com","c1");assertEquals(InvitationStatus.PENDING,view.status());verify(invitations).existsByInviterUserIdAndEmailHash(eq("owner"),argThat(v->v.length()==64&&!v.contains("@")));}
}
