spring.application.name=registry-service
spring.cloud.config.username=${CONFIG_SERVER_USERNAME}
spring.cloud.config.password=${CONFIG_SERVER_PASSWORD}
spring.config.import=configserver:${CONFIG_SERVER_URL:http://config-server:8080}
spring.cloud.config.fail-fast=true
spring.cloud.config.request-connect-timeout=5000
spring.cloud.config.request-read-timeout=10000

# Désactiver security-hardening-starter pour registry-service (utilise Basic Auth, pas JWT)
yeyamo.security.enabled=false
