package com.yeyamo_mobile.api.commerce_service.application;

import java.math.BigDecimal;import java.time.Instant;import java.util.*;
import org.springframework.data.domain.*;import org.springframework.data.jpa.domain.Specification;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import com.yeyamo_mobile.api.commerce_service.messaging.OutboxService;import com.yeyamo_mobile.api.commerce_service.persistence.*;
import static com.yeyamo_mobile.api.commerce_service.domain.CommerceTypes.*;

@Service
public class AdminCommerceService {
 private final PromotionRepository promotions;private final CommissionRepository commissions;private final CommerceAuditRepository audits;private final OutboxService outbox;
 public AdminCommerceService(PromotionRepository promotions,CommissionRepository commissions,CommerceAuditRepository audits,OutboxService outbox){this.promotions=promotions;this.commissions=commissions;this.audits=audits;this.outbox=outbox;}
 @Transactional(readOnly=true)public Page<Promotion>promotions(String search,String partnerId,PromotionStatus status,DiscountType type,Instant from,Instant to,Pageable page){Specification<Promotion>spec=(r,q,b)->b.conjunction();if(has(search))spec=spec.and((r,q,b)->b.or(b.like(b.lower(r.get("name")),"%"+search.toLowerCase(Locale.ROOT)+"%"),b.like(b.lower(r.get("code")),"%"+search.toLowerCase(Locale.ROOT)+"%")));if(has(partnerId))spec=spec.and((r,q,b)->b.equal(r.get("partnerId"),partnerId));if(status!=null)spec=spec.and((r,q,b)->b.equal(r.get("status"),status));if(type!=null)spec=spec.and((r,q,b)->b.equal(r.get("discountType"),type));if(from!=null)spec=spec.and((r,q,b)->b.greaterThanOrEqualTo(r.get("startsAt"),from));if(to!=null)spec=spec.and((r,q,b)->b.lessThanOrEqualTo(r.get("endsAt"),to));return promotions.findAll(spec,page);}
 @Transactional(readOnly=true)public Promotion promotion(UUID id){return promotions.findById(id).orElseThrow();}
 @Transactional public Promotion createPromotion(PromotionCommand c,String key,String actor){return promotions.findByIdempotencyKey(key).orElseGet(()->{validate(c);Promotion p=apply(new Promotion(),c);p.idempotencyKey=required(key,"Idempotency-Key");p.status=c.status()==null?PromotionStatus.DRAFT:c.status();p=promotions.save(p);audit(actor,"PromotionCreated","Promotion",p.id.toString(),p.code);event("promotion.created",p.id,key,Map.of("promotionId",p.id,"partnerId",String.valueOf(p.partnerId),"code",p.code));return p;});}
 @Transactional public Promotion updatePromotion(UUID id,PromotionCommand c,String key,String actor){required(key,"Idempotency-Key");validate(c);Promotion p=apply(promotion(id),c);p=promotions.save(p);audit(actor,"PromotionUpdated","Promotion",p.id.toString(),p.code);event("promotion.updated",p.id,key,Map.of("promotionId",p.id));return p;}
 @Transactional public Promotion disablePromotion(UUID id,String key,String actor){required(key,"Idempotency-Key");Promotion p=promotion(id);if(p.status!=PromotionStatus.INACTIVE){p.status=PromotionStatus.INACTIVE;p=promotions.save(p);audit(actor,"PromotionDisabled","Promotion",p.id.toString(),p.code);event("promotion.disabled",p.id,key,Map.of("promotionId",p.id));}return p;}
 @Transactional(readOnly=true)public Page<CommissionRule>commissions(String partnerId,ProductType type,String status,Instant from,Instant to,Pageable page){Specification<CommissionRule>spec=(r,q,b)->b.conjunction();if(has(partnerId))spec=spec.and((r,q,b)->b.equal(r.get("partnerId"),partnerId));if(type!=null)spec=spec.and((r,q,b)->b.equal(r.get("productType"),type));if(has(status))spec=spec.and((r,q,b)->b.equal(r.get("status"),status));if(from!=null)spec=spec.and((r,q,b)->b.greaterThanOrEqualTo(r.get("effectiveFrom"),from));if(to!=null)spec=spec.and((r,q,b)->b.lessThanOrEqualTo(r.get("effectiveFrom"),to));return commissions.findAll(spec,page);}
 @Transactional(readOnly=true)public CommissionRule commission(UUID id){return commissions.findById(id).orElseThrow();}
 @Transactional public CommissionRule createCommission(CommissionCommand c,String key,String actor){return commissions.findByIdempotencyKey(key).orElseGet(()->{validate(c);CommissionRule r=new CommissionRule();r.idempotencyKey=required(key,"Idempotency-Key");r.partnerId=c.partnerId();r.productType=Objects.requireNonNull(c.productType());r.percentage=c.rate();r.fixedAmount=c.fixedAmount();r.maximumAmount=c.maximumAmount();r.currency=c.currency().toUpperCase(Locale.ROOT);r.ruleVersion=c.ruleVersion();r.effectiveFrom=c.effectiveFrom();r.effectiveUntil=c.effectiveUntil();r.status="ACTIVE";r=commissions.save(r);audit(actor,"CommissionRuleCreated","CommissionRule",r.id.toString(),"v"+r.ruleVersion);event("commission.rule.created",r.id,key,Map.of("commissionRuleId",r.id,"partnerId",String.valueOf(r.partnerId)));return r;});}
 private Promotion apply(Promotion p,PromotionCommand c){p.partnerId=c.partnerId();p.code=required(c.code(),"code").toUpperCase(Locale.ROOT);p.name=required(c.name(),"name");p.description=c.description();p.discountType=c.type();p.discountValue=c.value();p.currency=c.currency()==null?null:c.currency().toUpperCase(Locale.ROOT);p.maximumDiscount=c.maxDiscount();p.minimumOrderAmount=c.minimumAmount();p.usageLimit=c.usageLimit();p.usageLimitPerUser=c.usagePerUser();p.startsAt=c.startAt();p.endsAt=c.endAt();p.status=c.status()==null?p.status:c.status();return p;}
 private void validate(PromotionCommand c){if(c.type()==null||c.value()==null||c.value().signum()<0||c.minimumAmount()==null||c.minimumAmount().signum()<0||c.startAt()==null||c.endAt()==null||!c.startAt().isBefore(c.endAt()))throw new IllegalArgumentException("Invalid promotion");if(c.type()==DiscountType.PERCENTAGE&&c.value().compareTo(new BigDecimal("100"))>0)throw new IllegalArgumentException("Percentage cannot exceed 100");if(c.type()==DiscountType.FIXED_AMOUNT&&!has(c.currency()))throw new IllegalArgumentException("Currency is required for fixed discounts");if(c.usageLimit()!=null&&c.usageLimit()<=0||c.usagePerUser()!=null&&c.usagePerUser()<=0)throw new IllegalArgumentException("Usage limits must be positive");}
 private void validate(CommissionCommand c){if(c.productType()==null||c.rate()==null||c.fixedAmount()==null||c.rate().signum()<0||c.rate().compareTo(new BigDecimal("100"))>0||c.fixedAmount().signum()<0||!has(c.currency())||c.ruleVersion()<=0||c.effectiveFrom()==null||c.effectiveUntil()!=null&&!c.effectiveUntil().isAfter(c.effectiveFrom()))throw new IllegalArgumentException("Invalid commission rule");}
 private void audit(String actor,String action,String type,String id,String detail){CommerceAudit row=new CommerceAudit();row.id=UUID.randomUUID();row.actorId=actor;row.action=action;row.entityType=type;row.entityId=id;row.details=detail;row.occurredAt=Instant.now();audits.save(row);}
 private void event(String type,UUID id,String correlation,Map<String,Object>payload){outbox.append("commerce.events",type,id.toString(),correlation,payload);}private boolean has(String v){return v!=null&&!v.isBlank();}private String required(String v,String field){if(!has(v))throw new IllegalArgumentException(field+" is required");return v.trim();}
 public record PromotionCommand(String partnerId,String code,String name,String description,DiscountType type,BigDecimal value,String currency,BigDecimal minimumAmount,BigDecimal maxDiscount,Instant startAt,Instant endAt,Long usageLimit,Long usagePerUser,PromotionStatus status){}
 public record CommissionCommand(String partnerId,ProductType productType,BigDecimal rate,BigDecimal fixedAmount,BigDecimal maximumAmount,String currency,int ruleVersion,Instant effectiveFrom,Instant effectiveUntil){}
}
