package com.yeyamo_mobile.api.catalog_service.interfaces.rest;
import com.yeyamo_mobile.api.catalog_service.infrastructure.persistence.*;import jakarta.validation.constraints.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController@RequestMapping("/api/v1")public class ArtworkReferenceController{private final ArtworkRepositories.Materials materials;private final ArtworkRepositories.MaterialTranslations materialTexts;private final ArtworkRepositories.Techniques techniques;private final ArtworkRepositories.TechniqueTranslations techniqueTexts;public ArtworkReferenceController(ArtworkRepositories.Materials m,ArtworkRepositories.MaterialTranslations mt,ArtworkRepositories.Techniques t,ArtworkRepositories.TechniqueTranslations tt){materials=m;materialTexts=mt;techniques=t;techniqueTexts=tt;}
 public record ReferenceRequest(@NotBlank@Pattern(regexp="^[a-z0-9-]+$")String code,boolean active,@NotBlank String languageCode,@NotBlank String name,String description){}
 @GetMapping("/artwork-materials")public List<ArtworkReferenceEntities.Material>materials(){return materials.findAll();}@GetMapping("/artwork-techniques")public List<ArtworkReferenceEntities.Technique>techniques(){return techniques.findAll();}
 @GetMapping("/artwork-materials/{id}/translations")public List<ArtworkReferenceEntities.MaterialTranslation>materialTranslations(@PathVariable UUID id){return materialTexts.findByMaterialId(id);}@GetMapping("/artwork-techniques/{id}/translations")public List<ArtworkReferenceEntities.TechniqueTranslation>techniqueTranslations(@PathVariable UUID id){return techniqueTexts.findByTechniqueId(id);}
 @PostMapping("/admin/artwork-materials")@PreAuthorize("hasAnyRole('ADMIN','SUPER_ADMIN','EDITOR')")@Transactional public ArtworkReferenceEntities.Material material(@RequestBody ReferenceRequest r){if(materials.existsByCode(r.code()))throw new IllegalArgumentException("Material code exists");var x=new ArtworkReferenceEntities.Material();x.id=UUID.randomUUID();x.code=r.code();x.active=r.active();materials.save(x);var t=new ArtworkReferenceEntities.MaterialTranslation();t.materialId=x.id;t.languageCode=r.languageCode();t.name=r.name();t.description=r.description();materialTexts.save(t);return x;}
 @PostMapping("/admin/artwork-techniques")@PreAuthorize("hasAnyRole('ADMIN','SUPER_ADMIN','EDITOR')")@Transactional public ArtworkReferenceEntities.Technique technique(@RequestBody ReferenceRequest r){if(techniques.existsByCode(r.code()))throw new IllegalArgumentException("Technique code exists");var x=new ArtworkReferenceEntities.Technique();x.id=UUID.randomUUID();x.code=r.code();x.active=r.active();techniques.save(x);var t=new ArtworkReferenceEntities.TechniqueTranslation();t.techniqueId=x.id;t.languageCode=r.languageCode();t.name=r.name();t.description=r.description();techniqueTexts.save(t);return x;}
}
