package com.yeyamo_mobile.api.catalog_service.interfaces.rest;
import com.yeyamo_mobile.api.catalog_service.application.ArtworkService;import com.yeyamo_mobile.api.catalog_service.infrastructure.persistence.*;import jakarta.validation.Valid;import org.springframework.data.domain.*;import org.springframework.http.*;import org.springframework.security.oauth2.jwt.Jwt;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/v1") public class ArtworkController {private final ArtworkService service;public ArtworkController(ArtworkService service){this.service=service;}
 @GetMapping("/artworks")public Page<ArtworkDtos.PublicSummary>list(@RequestParam(required=false)String countryCode,@RequestParam(required=false)UUID artisanId,@RequestParam(required=false)ArtworkEntity.AvailabilityStatus availability,@RequestParam(required=false)String search,Pageable pageable){return service.publicSearch(countryCode,artisanId,availability,search,pageable);}
 @GetMapping("/artworks/{id}")public ArtworkDtos.PublicDetail detail(@PathVariable UUID id){return service.publicDetail(id);}
 @GetMapping("/artworks/{id}/history")public List<ArtworkDetails.History>history(@PathVariable UUID id){service.publicDetail(id);return service.history(id);}
 @GetMapping("/artworks/{id}/media")public List<ArtworkDtos.PublicMedia>media(@PathVariable UUID id){return service.publicDetail(id).media();}
 @GetMapping("/artworks/{id}/related")public Page<ArtworkDtos.PublicSummary>related(@PathVariable UUID id,Pageable pageable){ArtworkDtos.PublicDetail a=service.publicDetail(id);return service.publicSearch(a.countryCode(),null,null,a.culturalCommunity(),pageable);}
 @GetMapping("/artisans/{artisanId}/artworks")public Page<ArtworkDtos.PublicSummary>artisan(@PathVariable UUID artisanId,Pageable pageable){return service.publicSearch(null,artisanId,null,null,pageable);}
 @GetMapping("/artworks/partner/me")public Page<ArtworkDtos.PublicSummary>mine(@AuthenticationPrincipal Jwt jwt,Pageable pageable){return service.mine(jwt.getSubject(),pageable);}
 @PostMapping("/artworks")@ResponseStatus(HttpStatus.CREATED)public ArtworkDtos.Response create(@Valid@RequestBody ArtworkDtos.Request r,@AuthenticationPrincipal Jwt jwt,@RequestHeader(value="X-Correlation-Id",required=false)String c){return service.create(r,jwt,c);}
 @PutMapping("/artworks/{id}")public ArtworkDtos.Response update(@PathVariable UUID id,@Valid@RequestBody ArtworkDtos.Request r,@AuthenticationPrincipal Jwt jwt,@RequestHeader(value="X-Correlation-Id",required=false)String c){return service.update(id,r,jwt,c);}
 @DeleteMapping("/artworks/{id}")@ResponseStatus(HttpStatus.NO_CONTENT)public void delete(@PathVariable UUID id,@AuthenticationPrincipal Jwt jwt,@RequestHeader(value="X-Correlation-Id",required=false)String c){service.delete(id,jwt,c);}
 @PatchMapping("/artworks/{id}/availability")public ArtworkEntity availability(@PathVariable UUID id,@Valid@RequestBody ArtworkDtos.AvailabilityRequest r,@AuthenticationPrincipal Jwt jwt,@RequestHeader(value="X-Correlation-Id",required=false)String c){return service.availability(id,r.status(),jwt,c);}
 @PostMapping("/artworks/{id}/history")public ArtworkDetails.History addHistory(@PathVariable UUID id,@Valid@RequestBody ArtworkDtos.HistoryRequest r,@AuthenticationPrincipal Jwt jwt,@RequestHeader(value="X-Correlation-Id",required=false)String c){return service.addHistory(id,r,jwt,c);}
 @PutMapping("/artworks/{id}/history/{entryId}")public ArtworkDetails.History updateHistory(@PathVariable UUID id,@PathVariable UUID entryId,@Valid@RequestBody ArtworkDtos.HistoryRequest r,@AuthenticationPrincipal Jwt jwt){return service.updateHistory(id,entryId,r,jwt);}
}
