package com.yeyamo_mobile.api.ticket_service.interfaces.rest;
import java.math.BigDecimal;import java.time.Instant;import java.util.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;import com.yeyamo_mobile.api.ticket_service.domain.model.TicketStatus;import com.yeyamo_mobile.api.ticket_service.infrastructure.persistence.*;
@RestController@RequestMapping("/api/v1/admin/events")@PreAuthorize("hasAnyRole('ADMIN','SUPER_ADMIN')")
public class AdminEventTicketController{
 private final SpringTicketSaleConfigurationRepository configurations;private final SpringTicketTypeRepository types;private final SpringTicketRepository tickets;private final SpringTicketScanRepository scans;
 public AdminEventTicketController(SpringTicketSaleConfigurationRepository configurations,SpringTicketTypeRepository types,SpringTicketRepository tickets,SpringTicketScanRepository scans){this.configurations=configurations;this.types=types;this.tickets=tickets;this.scans=scans;}
 public record TicketTypeView(UUID id,String code,String name,String description,BigDecimal price,int total,int reserved,int sold,int available,String status,Instant salesStartAt,Instant salesEndAt){}
 public record ParticipantView(UUID ticketId,String userId,String serialNumber,String ticketStatus,Instant issuedAt,Instant usedAt){}
 public record TicketingStats(long total,long valid,long used,long cancelled,long refunded,long failedScans,long successfulScans,int inventoryTotal,int inventorySold,int inventoryAvailable){}
 @GetMapping("/{eventId}/tickets")public List<TicketTypeView>ticketTypes(@PathVariable String eventId){return configurations.findByEventId(eventId).map(c->types.findBySaleConfigurationId(c.getId()).stream().map(t->new TicketTypeView(t.getId(),t.getCode(),t.getName(),t.getDescription(),t.getPrice(),t.getQuantityTotal(),t.getQuantityReserved(),t.getQuantitySold(),t.getAvailableQuantity(),t.getStatus(),t.getSalesStartAt(),t.getSalesEndAt())).toList()).orElse(List.of());}
 @GetMapping("/{eventId}/participants")public List<ParticipantView>participants(@PathVariable String eventId){return tickets.findByEventIdOrderByCreatedAtDesc(eventId).stream().map(t->new ParticipantView(t.getId(),t.getOwnerUserId(),t.getSerialNumber(),t.getStatus().name(),t.getIssuedAt(),t.getUsedAt())).toList();}
 @GetMapping("/{eventId}/ticketing-stats")public TicketingStats stats(@PathVariable String eventId){List<TicketTypeView>typeViews=ticketTypes(eventId);List<TicketEntity>all=tickets.findByEventIdOrderByCreatedAtDesc(eventId);return new TicketingStats(all.size(),tickets.countByEventIdAndStatus(eventId,TicketStatus.VALID),tickets.countByEventIdAndStatus(eventId,TicketStatus.USED),tickets.countByEventIdAndStatus(eventId,TicketStatus.CANCELLED),tickets.countByEventIdAndStatus(eventId,TicketStatus.REFUNDED),scans.findByEventIdOrderByScannedAtDesc(eventId).stream().filter(s->s.getResult()!=com.yeyamo_mobile.api.ticket_service.domain.model.ScanResult.VALID).count(),scans.countByEventIdAndResult(eventId,com.yeyamo_mobile.api.ticket_service.domain.model.ScanResult.VALID),typeViews.stream().mapToInt(TicketTypeView::total).sum(),typeViews.stream().mapToInt(TicketTypeView::sold).sum(),typeViews.stream().mapToInt(TicketTypeView::available).sum());}
}
