package com.yeyamo_mobile.api.ticket_service.interfaces.rest;
import com.yeyamo_mobile.api.ticket_service.application.*;import com.yeyamo_mobile.api.ticket_service.domain.model.*;import com.yeyamo_mobile.api.ticket_service.infrastructure.persistence.*;import jakarta.validation.*;import jakarta.validation.constraints.*;import org.springframework.beans.factory.annotation.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.client.*;import java.math.*;import java.time.*;import java.util.*;
@RestController @RequestMapping("/api/v1/partners/{partnerId}/tickets")public class PartnerTicketController{
 private final TicketManagementService service;private final RestClient partners;private final RestClient users;public PartnerTicketController(TicketManagementService s,@Value("${yeyamo.services.partner-url:http://partner-service:8080}")String url,@Value("${yeyamo.services.user-url:http://user-service:8080}")String userUrl){service=s;partners=RestClient.create(url);users=RestClient.create(userUrl);}
 public record SaleRequest(@NotBlank String eventId,@NotNull Instant salesStartAt,@NotNull Instant salesEndAt,@Min(1)int maxTicketsPerBuyer,@Pattern(regexp="[A-Z]{3}")String currency){}
 public record TypeRequest(@NotBlank String code,@NotBlank String name,String description,@NotNull@DecimalMin("0")BigDecimal price,@Min(0)int quantity,Instant salesStartAt,Instant salesEndAt,String accessZone,String gateInstructions){}
 public record StaffRequest(@NotBlank String eventId,@NotBlank String userId,@NotNull StaffRole role,@NotNull Instant validFrom,@NotNull Instant validUntil){}
 @PutMapping("/configuration")public TicketSaleConfigurationEntity config(@PathVariable String partnerId,@RequestHeader(HttpHeaders.AUTHORIZATION)String auth,@Valid@RequestBody SaleRequest r){allow(partnerId,"partner:ticket-manage",auth);return service.configure(new TicketManagementService.SaleConfig(r.eventId(),partnerId,r.salesStartAt(),r.salesEndAt(),r.maxTicketsPerBuyer(),r.currency()));}
 @PostMapping("/configurations/{id}/types")public TicketTypeEntity type(@PathVariable String partnerId,@PathVariable UUID id,@RequestHeader(HttpHeaders.AUTHORIZATION)String auth,@Valid@RequestBody TypeRequest r){allow(partnerId,"partner:ticket-manage",auth);return service.type(id,partnerId,new TicketManagementService.TypeConfig(r.code(),r.name(),r.description(),r.price(),r.quantity(),r.salesStartAt(),r.salesEndAt(),r.accessZone(),r.gateInstructions()));}
 @GetMapping("/events/{eventId}/types")public List<TicketTypeEntity>types(@PathVariable String partnerId,@PathVariable String eventId,@RequestHeader(HttpHeaders.AUTHORIZATION)String auth){allow(partnerId,"partner:ticket-view",auth);return service.typesForPartnerEvent(eventId,partnerId);}
 @PostMapping("/staff")public EventStaffAssignmentEntity staff(@PathVariable String partnerId,@RequestHeader(HttpHeaders.AUTHORIZATION)String auth,@Valid@RequestBody StaffRequest r){allow(partnerId,"partner:staff-manage",auth);return service.assign(r.eventId(),partnerId,r.userId(),r.role(),r.validFrom(),r.validUntil());}
 public record StaffResponse(UUID id,String eventId,String partnerId,String userId,String displayName,String avatarUrl,StaffRole role,String status,Instant validFrom,Instant validUntil,Instant createdAt,Instant updatedAt){}
 @GetMapping("/events/{eventId}/staff")public List<StaffResponse>staff(@PathVariable String partnerId,@PathVariable String eventId,@RequestHeader(HttpHeaders.AUTHORIZATION)String auth){allow(partnerId,"partner:staff-manage",auth);return service.staffForPartnerEvent(eventId,partnerId).stream().map(x->staffResponse(x,auth)).toList();}
 public record StaffRoleRequest(@NotNull StaffRole role){}
 @PutMapping("/events/{eventId}/staff/{assignmentId}/role")public EventStaffAssignmentEntity staffRole(@PathVariable String partnerId,@PathVariable String eventId,@PathVariable UUID assignmentId,@RequestHeader(HttpHeaders.AUTHORIZATION)String auth,@Valid@RequestBody StaffRoleRequest r){allow(partnerId,"partner:staff-manage",auth);return service.changeStaffRole(assignmentId,eventId,partnerId,r.role());}
 @DeleteMapping("/events/{eventId}/staff/{assignmentId}")public void revokeEventStaff(@PathVariable String partnerId,@PathVariable String eventId,@PathVariable UUID assignmentId,@RequestHeader(HttpHeaders.AUTHORIZATION)String auth){allow(partnerId,"partner:staff-manage",auth);service.revokeStaff(assignmentId,partnerId);}
 @DeleteMapping("/staff/{id}")public void revoke(@PathVariable String partnerId,@PathVariable UUID id,@RequestHeader(HttpHeaders.AUTHORIZATION)String auth){allow(partnerId,"partner:staff-manage",auth);service.revokeStaff(id,partnerId);}
 private StaffResponse staffResponse(EventStaffAssignmentEntity x,String auth){String name=x.getUserId(),avatar=null;try{Map<?,?>p=users.get().uri("/api/v1/users/{id}",UUID.fromString(x.getUserId())).header(HttpHeaders.AUTHORIZATION,auth).retrieve().body(Map.class);if(p!=null){name=Objects.toString(p.get("displayName"),name);avatar=p.get("avatarUrl")==null?null:p.get("avatarUrl").toString();}}catch(RuntimeException ignored){}return new StaffResponse(x.getId(),x.getEventId(),x.getPartnerId(),x.getUserId(),name,avatar,x.getRole(),x.getStatus(),x.getValidFrom(),x.getValidUntil(),x.getCreatedAt(),x.getUpdatedAt());}
 private void allow(String partner,String permission,String auth){Map<?,?>r=partners.get().uri("/api/v1/partners/{p}/staff/permissions/{x}",partner,permission).header(HttpHeaders.AUTHORIZATION,auth).retrieve().body(Map.class);if(r==null||!Boolean.TRUE.equals(r.get("allowed")))throw new SecurityException("Partner permission denied");}}
