package com.yeyamo_mobile.api.gamification_service.application;
import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;import java.time.Instant;import java.util.*;import org.junit.jupiter.api.Test;import com.yeyamo_mobile.api.gamification_service.application.badge.BadgeRule;import com.yeyamo_mobile.api.gamification_service.application.port.*;import com.yeyamo_mobile.api.gamification_service.domain.*;
class GamificationServiceTest{
 @Test void awardsXpStampBadgeAndRewardAtomically(){
  var repo=mock(GamificationRepositoryPort.class);var cache=mock(GamificationCachePort.class);var outbox=mock(GamificationOutboxPort.class);var rule=mock(BadgeRule.class);
  Progress before=progress(0,1);Progress after=progress(30,1);var activity=new XpActivity(UUID.randomUUID(),"u",30,"CHECKIN","check-1","CHECKIN","asset-1",Instant.now());
  when(repo.award(activity)).thenReturn(new AwardResult(true,before,after));when(repo.counters("u")).thenReturn(Map.of("CHECKIN",1L));var badge=new BadgeDefinition("EXPLORER","Explorateur","Premier check-in");when(rule.evaluate(after,Map.of("CHECKIN",1L))).thenReturn(List.of(badge));when(repo.grantBadge("u",badge,activity.eventId())).thenReturn(true);when(repo.stamp("u","asset-1",activity.eventId())).thenReturn(true);when(repo.grantReward(eq("u"),eq("BADGE_EXPLORER"),anyString(),eq("badge:EXPLORER"))).thenReturn(Optional.of(new Reward(UUID.randomUUID(),"u","BADGE_EXPLORER","Reward",RewardStatus.AVAILABLE,Instant.now(),null,"badge:EXPLORER")));
  new GamificationService(repo,cache,outbox,List.of(rule)).apply(activity,"c1");verify(repo).incrementCounter("u","CHECKIN");verify(repo).stamp("u","asset-1",activity.eventId());verify(repo).grantBadge("u",badge,activity.eventId());verify(outbox).append(eq("gamification.xp.awarded"),eq("u"),eq("c1"),anyMap());verify(outbox).append(eq("gamification.badge.earned"),eq("u"),eq("c1"),anyMap());verify(cache).evict("u");
 }
 @Test void duplicateAwardProducesNoSideEffects(){var repo=mock(GamificationRepositoryPort.class);var cache=mock(GamificationCachePort.class);var outbox=mock(GamificationOutboxPort.class);var activity=new XpActivity(UUID.randomUUID(),"u",2,"LIKE","p1","SOCIAL",null,Instant.now());var p=progress(2,1);when(repo.award(activity)).thenReturn(new AwardResult(false,p,p));new GamificationService(repo,cache,outbox,List.of()).apply(activity,null);verifyNoInteractions(cache,outbox);verify(repo,never()).incrementCounter(any(),any());}
 @Test void viewUsesCache(){var repo=mock(GamificationRepositoryPort.class);var cache=mock(GamificationCachePort.class);var view=new GamificationView(progress(0,1),List.of(),List.of(),List.of());when(cache.get("u")).thenReturn(Optional.of(view));assertSame(view,new GamificationService(repo,cache,mock(GamificationOutboxPort.class),List.of()).view("u"));verifyNoInteractions(repo);}
 @Test void catalogStatsAndLeaderboardExposeEarnedStateAndRanks(){var repo=mock(GamificationRepositoryPort.class);var service=new GamificationService(repo,mock(GamificationCachePort.class),mock(GamificationOutboxPort.class),List.of());var earned=new Badge(UUID.randomUUID(),"u","EXPLORER","Explorateur","Effectuer un premier check-in",Instant.now());when(repo.badges("u")).thenReturn(List.of(earned));when(repo.progress("u")).thenReturn(progress(250,2));when(repo.rank("u")).thenReturn(3L);when(repo.leaderboard(10)).thenReturn(List.of(progress(500,3),progress(250,2)));var catalog=service.catalog("u");assertEquals(13,catalog.size());assertTrue(catalog.stream().filter(b->b.code().equals("EXPLORER")).findFirst().orElseThrow().earned());assertEquals(3,service.stats("u").rank());assertEquals(List.of(1L,2L),service.leaderboard(10).stream().map(LeaderboardEntry::rank).toList());}
 @Test void passportSummaryUsesBackendThresholdsAndRealCounts(){var repo=mock(GamificationRepositoryPort.class);var cache=mock(GamificationCachePort.class);var service=new GamificationService(repo,cache,mock(GamificationOutboxPort.class),List.of());var view=new GamificationView(progress(250,2),List.of(new Badge(UUID.randomUUID(),"u","B","Badge","Description",Instant.now())),List.of(new PassportStamp(UUID.randomUUID(),"u","place",Instant.now())),List.of(new Reward(UUID.randomUUID(),"u","R","Reward",RewardStatus.AVAILABLE,Instant.now(),null,"level:2")));when(cache.get("u")).thenReturn(Optional.of(view));PassportSummary summary=service.passportSummary("u");assertEquals(2,summary.level());assertEquals(100,summary.currentLevelThreshold());assertEquals(400,summary.nextLevelThreshold());assertEquals(150,summary.currentLevelXp());assertEquals(150,summary.xpToNextLevel());assertEquals(1,summary.earnedBadgesCount());assertEquals(1,summary.availableRewardsCount());}
 private Progress progress(long xp,int level){return new Progress("u",xp,level,1,1,null,Instant.now());}
}
