spring.application.name=feed-service
yeyamo.feed.mix.weights.SOCIAL=${FEED_WEIGHT_SOCIAL:1.0}
yeyamo.feed.mix.weights.PLACE=${FEED_WEIGHT_PLACE:1.0}
yeyamo.feed.mix.weights.EVENT=${FEED_WEIGHT_EVENT:1.0}
yeyamo.feed.mix.weights.CULTURE_CONTENT=${FEED_WEIGHT_CULTURE:1.0}
yeyamo.feed.mix.weights.LANGUAGE_LESSON=${FEED_WEIGHT_LANGUAGE:1.0}
yeyamo.feed.mix.weights.ARTWORK=${FEED_WEIGHT_ARTWORK:1.0}
yeyamo.feed.mix.weights.CULTURE_CHALLENGE=${FEED_WEIGHT_CHALLENGE:1.0}
yeyamo.feed.mix.weights.ARTISAN=${FEED_WEIGHT_ARTISAN:1.0}
spring.cloud.config.username=${CONFIG_SERVER_USERNAME}
spring.cloud.config.password=${CONFIG_SERVER_PASSWORD}
spring.config.import=configserver:${CONFIG_SERVER_URL:http://config-server:8080}
spring.cloud.config.fail-fast=true
