package com.yeyamo_mobile.api.catalog_service.application;
import com.yeyamo_mobile.api.catalog_service.application.port.OutboxPort;import com.yeyamo_mobile.api.catalog_service.domain.model.*;import com.yeyamo_mobile.api.catalog_service.infrastructure.persistence.*;import com.yeyamo_mobile.api.catalog_service.interfaces.rest.ArtworkDtos;import org.junit.jupiter.api.*;import org.mockito.*;import org.springframework.data.domain.*;import org.springframework.security.oauth2.jwt.Jwt;import java.time.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
class ArtworkServiceTest{
 @Mock ArtworkRepositories.Artworks artworks;@Mock SpringDataCatalogAssetRepository assets;@Mock ArtworkRepositories.Translations translations;@Mock ArtworkRepositories.Histories histories;@Mock ArtworkRepositories.Media media;@Mock OutboxPort outbox;@Mock com.yeyamo_mobile.api.catalog_service.application.port.PartnerArtworkAuthorizationPort authorization;ArtworkService service;AutoCloseable mocks;
 @BeforeEach void setup(){mocks=MockitoAnnotations.openMocks(this);service=new ArtworkService(artworks,assets,translations,histories,media,outbox,null,authorization);}@AfterEach void close()throws Exception{mocks.close();}
 @Test void rejectsAnotherPartner(){UUID owner=UUID.randomUUID();ArtworkEntity a=new ArtworkEntity();a.assetId=UUID.randomUUID();a.artisanPartnerId=owner;when(artworks.locked(a.assetId)).thenReturn(Optional.of(a));doThrow(new SecurityException()).when(authorization).requireCanManage("user",owner);Jwt jwt=Jwt.withTokenValue("x").header("alg","none").subject("user").issuedAt(Instant.now()).expiresAt(Instant.now().plusSeconds(60)).build();assertThrows(SecurityException.class,()->service.delete(a.assetId,jwt,"c"));}
 @Test void softDeleteKeepsRecord(){UUID owner=UUID.randomUUID();ArtworkEntity a=new ArtworkEntity();a.assetId=UUID.randomUUID();a.artisanPartnerId=owner;a.availabilityStatus=ArtworkEntity.AvailabilityStatus.AVAILABLE;a.countryCode="CM";when(artworks.locked(a.assetId)).thenReturn(Optional.of(a));when(artworks.save(any())).thenAnswer(i->i.getArgument(0));Jwt jwt=Jwt.withTokenValue("x").header("alg","none").subject("user").issuedAt(Instant.now()).expiresAt(Instant.now().plusSeconds(60)).build();service.delete(a.assetId,jwt,"c");verify(authorization).requireCanManage("user",owner);assertNotNull(a.deletedAt);assertEquals(ArtworkEntity.AvailabilityStatus.UNAVAILABLE,a.availabilityStatus);verify(artworks).save(a);}
 @Test void publicDetailRequiresPublishedAssetAndMapsCanonicalMedia(){UUID id=UUID.randomUUID();UUID mediaId=UUID.randomUUID();ArtworkEntity artwork=new ArtworkEntity();artwork.assetId=id;artwork.artisanPartnerId=UUID.randomUUID();artwork.title="Masque";artwork.slug="masque";artwork.countryCode="CM";artwork.editionType=ArtworkEntity.EditionType.UNIQUE;artwork.availabilityStatus=ArtworkEntity.AvailabilityStatus.DISPLAY_ONLY;artwork.authenticityStatus=ArtworkEntity.AuthenticityStatus.DECLARED;artwork.createdAt=Instant.now();artwork.updatedAt=artwork.createdAt;CatalogAssetEntity asset=new CatalogAssetEntity();asset.setId(id);asset.setType(AssetType.ARTWORK);asset.setStatus(AssetStatus.PUBLISHED);ArtworkDetails.Media image=new ArtworkDetails.Media();image.artworkId=id;image.mediaId=mediaId;image.mediaType=ArtworkDetails.MediaType.PRIMARY_IMAGE;when(assets.findById(id)).thenReturn(Optional.of(asset));when(artworks.findByAssetIdAndDeletedAtIsNull(id)).thenReturn(Optional.of(artwork));when(media.findByArtworkIdOrderByDisplayOrderAsc(id)).thenReturn(List.of(image));ArtworkDtos.PublicDetail detail=service.publicDetail(id);assertEquals(id,detail.id());assertEquals("/api/v1/media/"+mediaId+"/content",detail.media().getFirst().contentUrl());}
 @Test void ownListUsesCanonicalPartnerSet(){UUID owner=UUID.randomUUID();when(authorization.manageablePartners("user")).thenReturn(Set.of(owner));when(artworks.findAll(any(org.springframework.data.jpa.domain.Specification.class),any(Pageable.class))).thenReturn(Page.empty());service.mine("user",PageRequest.of(0,20));verify(authorization).manageablePartners("user");verify(artworks).findAll(any(org.springframework.data.jpa.domain.Specification.class),any(Pageable.class));}
 @Test void publicDetailRejectsDraftAsset(){UUID id=UUID.randomUUID();CatalogAssetEntity asset=new CatalogAssetEntity();asset.setId(id);asset.setType(AssetType.ARTWORK);asset.setStatus(AssetStatus.DRAFT);when(assets.findById(id)).thenReturn(Optional.of(asset));CatalogException error=assertThrows(CatalogException.class,()->service.publicDetail(id));assertEquals("ARTWORK_NOT_FOUND",error.getCode());verifyNoInteractions(media);}
}
