package com.yeyamo_mobile.api.culture_service.interfaces.rest;
import static com.yeyamo_mobile.api.culture_service.application.CultureDtos.*;import com.yeyamo_mobile.api.culture_service.application.*;import com.yeyamo_mobile.api.culture_service.domain.CultureEnums.*;import io.swagger.v3.oas.annotations.Operation;import java.security.Principal;import java.util.*;import org.springframework.data.domain.*;import org.springframework.data.web.PageableDefault;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/culture") public class PublicCultureController{private final CultureContentService culture;private final LanguageLearningService learning;public PublicCultureController(CultureContentService c,LanguageLearningService l){culture=c;learning=l;}
 @GetMapping("/contents")@Operation(summary="Lister les contenus culturels publiés")public Page<ContentResponse> contents(@RequestParam(required=false)ContentType type,@RequestParam(required=false)String countryCode,@RequestParam(required=false)String adminLevel1Id,@RequestParam(required=false)String cityId,@RequestParam(required=false)String languageCode,@RequestParam(required=false)String community,@RequestParam(required=false)Boolean verified,@RequestParam(required=false)String search,@PageableDefault(size=20,sort="publishedAt",direction=Sort.Direction.DESC)Pageable p){return culture.publicList(type,countryCode,adminLevel1Id,cityId,languageCode,community,verified,search,p);}
 @GetMapping("/contents/{id}")public ContentResponse content(@PathVariable UUID id){return culture.publicGet(id);}@GetMapping("/contents/{id}/translations")public List<TranslationResponse> translations(@PathVariable UUID id){return culture.publicTranslations(id);}
 @GetMapping("/languages")public List<LanguageResponse> languages(){return learning.languages();}@GetMapping("/languages/{code}")public LanguageResponse language(@PathVariable String code){return learning.language(code);}@GetMapping("/languages/{code}/content")public Page<ContentResponse> languageContent(@PathVariable String code,@PageableDefault(size=20)Pageable p){return culture.publicList(null,null,null,null,code,null,null,null,p);}@GetMapping("/languages/{code}/lessons")public List<LessonSummary> lessons(@PathVariable String code){return learning.lessons(code);}
 @GetMapping("/language-lessons/{id}")public LessonDetail lesson(@PathVariable UUID id){return learning.lesson(id);}@PostMapping("/language-lessons/{id}/start")public ProgressResponse start(@PathVariable UUID id,Principal actor){return learning.start(id,actor.getName());}@PostMapping("/language-lessons/{id}/attempts")public AttemptResponse attempt(@PathVariable UUID id,@RequestBody@jakarta.validation.Valid AttemptRequest r,Principal actor){return learning.attempt(id,r,actor.getName());}@PostMapping("/language-lessons/{id}/complete")public ProgressResponse complete(@PathVariable UUID id,@RequestBody@jakarta.validation.Valid CompleteRequest r,Principal actor){return learning.complete(id,r,actor.getName());}
 @GetMapping("/language-progress/me")public List<ProgressResponse> progress(Principal actor){return learning.progress(actor.getName(),null);}@GetMapping("/language-progress/me/{languageCode}")public List<ProgressResponse> progress(@PathVariable String languageCode,Principal actor){return learning.progress(actor.getName(),languageCode);}
 @GetMapping("/daily-word")public ContentResponse dailyWord(@RequestParam String countryCode,@RequestParam(required=false)String languageCode,Principal actor){return learning.dailyWord(countryCode,languageCode,actor==null?null:actor.getName());}@GetMapping("/daily")public Page<ContentResponse> daily(@PageableDefault(size=10,sort="publishedAt",direction=Sort.Direction.DESC)Pageable p){return culture.publicList(null,null,null,null,null,null,true,null,p);}@GetMapping("/trending")public Page<ContentResponse> trending(@PageableDefault(size=20,sort="publishedAt",direction=Sort.Direction.DESC)Pageable p){return culture.publicList(null,null,null,null,null,null,null,null,p);}@GetMapping("/categories")public List<ContentType> categories(){return List.of(ContentType.values());}
}
