package com.yeyamo_mobile.api.mission_reward_service.application;
import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;import java.time.Instant;import java.util.*;import java.util.concurrent.atomic.AtomicReference;import org.junit.jupiter.api.*;import org.mockito.*;
import com.yeyamo_mobile.api.mission_reward_service.application.MissionDtos.*;import com.yeyamo_mobile.api.mission_reward_service.application.port.MissionOutboxPort;import com.yeyamo_mobile.api.mission_reward_service.domain.*;import com.yeyamo_mobile.api.mission_reward_service.infrastructure.persistence.*;
class MissionApplicationServiceTest{
 MissionDefinitionRepository missions=mock(MissionDefinitionRepository.class);MissionObjectiveRepository objectives=mock(MissionObjectiveRepository.class);UserMissionRepository users=mock(UserMissionRepository.class);MissionProgressRepository progress=mock(MissionProgressRepository.class);RewardGrantRepository rewards=mock(RewardGrantRepository.class);MissionOutboxPort outbox=mock(MissionOutboxPort.class);MissionApplicationService service;
 @BeforeEach void setUp(){service=new MissionApplicationService(missions,objectives,users,progress,rewards,outbox);}
 @Test void createsDraftWithObjectives(){when(missions.save(any())).thenAnswer(i->i.getArgument(0));AtomicReference<MissionObjectiveEntity>saved=new AtomicReference<>();when(objectives.save(any())).thenAnswer(i->{MissionObjectiveEntity o=i.getArgument(0);saved.set(o);return o;});when(objectives.findByMissionIdOrderByPositionAsc(any())).thenAnswer(i->saved.get()==null?List.of():List.of(saved.get()));var command=new CreateMission("EXPLORE_3","Explorer","Visiter trois lieux",null,null,"COUPON","Coupon",1,List.of(new ObjectiveInput("Check-ins","interaction.checkin.created",ObjectiveMetric.COUNT,3,null,null,null)));var view=service.create(command,"c1");assertEquals(MissionStatus.DRAFT,view.status());assertEquals(1,view.objectives().size());verify(outbox).append(eq("mission.created"),anyString(),eq("c1"),anyMap());}
 @Test void eventCompletesMissionAndStartsRewardSaga(){var mission=activeMission();var objective=MissionObjectiveEntity.create(mission,"Un check-in","interaction.checkin.created",new ObjectiveRule(ObjectiveMetric.COUNT,1,null,null,null),0);when(objectives.findByEventTypeOrderByPositionAsc(anyString())).thenReturn(List.of(objective));when(objectives.findByMissionIdOrderByPositionAsc(mission.getId())).thenReturn(List.of(objective));when(users.findByUserIdAndMissionId("u1",mission.getId())).thenReturn(Optional.empty());when(users.save(any())).thenAnswer(i->i.getArgument(0));AtomicReference<MissionProgressEntity>saved=new AtomicReference<>();when(progress.findByUserMissionIdAndObjectiveId(any(),any())).thenReturn(Optional.empty());when(progress.save(any())).thenAnswer(i->{MissionProgressEntity p=i.getArgument(0);saved.set(p);return p;});when(progress.findByUserMissionId(any())).thenAnswer(i->List.of(saved.get()));when(rewards.findByUserMissionId(any())).thenReturn(Optional.empty());when(rewards.save(any())).thenAnswer(i->i.getArgument(0));service.apply(new MissionEvent(UUID.randomUUID(),"interaction.checkin.created","u1",Map.of("userId","u1"),Instant.now(),"c1"));verify(outbox).append(eq("mission.completed"),anyString(),eq("c1"),anyMap());verify(outbox).append(eq("mission.reward.granted"),anyString(),eq("c1"),anyMap());}
 @Test void nonMatchingRuleDoesNotEnroll(){var mission=activeMission();var objective=MissionObjectiveEntity.create(mission,"Cameroun","interaction.checkin.created",new ObjectiveRule(ObjectiveMetric.COUNT,1,null,"country","CM"),0);when(objectives.findByEventTypeOrderByPositionAsc(anyString())).thenReturn(List.of(objective));service.apply(new MissionEvent(UUID.randomUUID(),"interaction.checkin.created","u1",Map.of("country","FR"),Instant.now(),"c1"));verifyNoInteractions(users);}
 @Test void successfulReplayRecoversFailedRewardSaga(){var userMission=UserMissionEntity.enroll("u1",activeMission());userMission.complete();var grant=RewardGrantEntity.pending(userMission);grant.fail("Kafka unavailable");when(rewards.findById(grant.getId())).thenReturn(Optional.of(grant));service.confirmGrant(grant.getId());assertEquals(RewardGrantStatus.GRANTED,grant.getStatus());assertEquals(UserMissionStatus.REWARDED,userMission.getStatus());verify(rewards).save(grant);}
 private MissionDefinitionEntity activeMission(){var m=MissionDefinitionEntity.draft(UUID.randomUUID(),"M1","Mission","Description",null,null,"R1","Reward",1);m.activate();return m;}
}
