package com.yeyamo_mobile.api.payment_service.application;
import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;import java.math.BigDecimal;import java.util.*;import org.junit.jupiter.api.*;import com.yeyamo_mobile.api.payment_service.application.PaymentCommands.*;import com.yeyamo_mobile.api.payment_service.application.port.*;import com.yeyamo_mobile.api.payment_service.application.port.PaymentProviderPort.*;import com.yeyamo_mobile.api.payment_service.domain.*;import com.yeyamo_mobile.api.payment_service.infrastructure.persistence.*;
class PaymentApplicationServiceTests{
 PaymentRepository payments=mock(PaymentRepository.class);RefundRepository refunds=mock(RefundRepository.class);PaymentProviderPort provider=mock(PaymentProviderPort.class);PaymentOutboxPort outbox=mock(PaymentOutboxPort.class);PaymentApplicationService service;
 @BeforeEach void setUp(){service=new PaymentApplicationService(payments,refunds,provider,outbox);when(provider.name()).thenReturn("simulated");when(payments.save(any())).thenAnswer(i->i.getArgument(0));when(refunds.save(any())).thenAnswer(i->i.getArgument(0));}
 @Test void authorizationPublishesBookingCompatibleEvent(){UUID booking=UUID.randomUUID();when(payments.findByIdempotencyKey("key")).thenReturn(Optional.empty());when(payments.findByBookingId(booking)).thenReturn(Optional.empty());when(provider.authorize(any())).thenReturn(new ProviderResult(Outcome.SUCCEEDED,"pay-1",null));var payment=service.authorize(new Authorize(UUID.randomUUID(),booking,"user-1",new BigDecimal("20.00"),"EUR","key","corr"));assertEquals(PaymentStatus.AUTHORIZED,payment.getStatus());verify(outbox).append(eq("payment.authorized"),eq(payment.getId().toString()),eq("corr"),argThat(p->booking.equals(p.get("bookingId"))&&"pay-1".equals(p.get("paymentId"))));}
 @Test void repeatedIdempotencyKeyDoesNotCallProvider(){var existing=payment();when(payments.findByIdempotencyKey("key")).thenReturn(Optional.of(existing));assertSame(existing,service.authorize(new Authorize(null,existing.getBookingId(),"user-1",BigDecimal.TEN,"EUR","key",null)));verifyNoInteractions(provider);verifyNoInteractions(outbox);}
 @Test void providerDeclinePublishesFailure(){UUID booking=UUID.randomUUID();when(payments.findByIdempotencyKey("key")).thenReturn(Optional.empty());when(payments.findByBookingId(booking)).thenReturn(Optional.empty());when(provider.authorize(any())).thenReturn(new ProviderResult(Outcome.FAILED,null,"declined"));var payment=service.authorize(new Authorize(null,booking,"user-1",BigDecimal.TEN,"EUR","key","corr"));assertEquals(PaymentStatus.FAILED,payment.getStatus());verify(outbox).append(eq("payment.failed"),anyString(),eq("corr"),argThat(p->"declined".equals(p.get("reason"))));}
 @Test void refundPublishesCompletion(){var payment=payment();payment.authorized("pay-1");when(refunds.findByIdempotencyKey("refund-key")).thenReturn(Optional.empty());when(payments.findByBookingIdLocked(payment.getBookingId())).thenReturn(Optional.of(payment));when(provider.refund(any())).thenReturn(new ProviderResult(Outcome.SUCCEEDED,"refund-1",null));var refund=service.refund(new Refund(null,payment.getBookingId(),"pay-1",BigDecimal.TEN,"EUR","refund-key","corr"));assertEquals(RefundStatus.SUCCEEDED,refund.getStatus());assertEquals(PaymentStatus.REFUNDED,payment.getStatus());verify(outbox).append(eq("payment.refunded"),anyString(),eq("corr"),anyMap());}
 @Test void reusedRefundKeyWithDifferentAmountIsRejected(){var payment=payment();payment.authorized("pay-1");var existing=RefundEntity.pending(payment,new BigDecimal("5.00"),"refund-key");when(refunds.findByIdempotencyKey("refund-key")).thenReturn(Optional.of(existing));assertEquals("IDEMPOTENCY_CONFLICT",assertThrows(PaymentException.class,()->service.refund(new Refund(null,payment.getBookingId(),"pay-1",BigDecimal.TEN,"EUR","refund-key","corr"))).getCode());verifyNoInteractions(provider);}
 private PaymentEntity payment(){return PaymentEntity.pending(UUID.randomUUID(),UUID.randomUUID(),"user-1",BigDecimal.TEN,"EUR","simulated","key");}
}
