package com.yeyamo_mobile.api.referral_service.application;
import java.time.Instant;import java.util.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.dao.DataIntegrityViolationException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import com.yeyamo_mobile.api.referral_service.application.ReferralDtos.*;import com.yeyamo_mobile.api.referral_service.application.port.*;import com.yeyamo_mobile.api.referral_service.domain.*;import com.yeyamo_mobile.api.referral_service.infrastructure.persistence.*;
@Service public class ReferralApplicationService{
 private final ReferralCodeRepository codes;private final ReferralInvitationRepository invitations;private final ReferralAttributionRepository attributions;private final ReferralRewardRepository rewards;private final ReferralHistoryRepository history;private final ReferralCodeGenerator generator;private final HashingService hashing;private final AntiFraudService fraud;private final FraudCounterPort counter;private final ReferralOutboxPort outbox;private final int referrerReward;private final int referredReward;
 public ReferralApplicationService(ReferralCodeRepository c,ReferralInvitationRepository i,ReferralAttributionRepository a,ReferralRewardRepository r,ReferralHistoryRepository h,ReferralCodeGenerator g,HashingService hashing,AntiFraudService f,FraudCounterPort counter,ReferralOutboxPort o,@Value("${referral.reward.referrer-amount:100}")int rr,@Value("${referral.reward.referred-amount:50}")int re){codes=c;invitations=i;attributions=a;rewards=r;history=h;generator=g;this.hashing=hashing;fraud=f;this.counter=counter;outbox=o;referrerReward=rr;referredReward=re;}
 @Transactional public CodeView createCode(String owner,int maxUses,Instant expires,String correlation){if(expires!=null&&!expires.isAfter(Instant.now()))throw new ReferralException("INVALID_EXPIRY","Expiration must be in the future");ReferralCodeEntity code=null;for(int attempt=0;attempt<5&&code==null;attempt++){String value=generator.next();if(codes.findByCodeIgnoreCase(value).isEmpty())code=codes.save(ReferralCodeEntity.create(value,owner,maxUses,expires));}if(code==null)throw new IllegalStateException("Unable to generate a unique referral code");outbox.append("referral.code.created",code.getId().toString(),correlation,Map.of("codeId",code.getId(),"code",code.getCode(),"ownerUserId",owner));return codeView(code);}
 @Transactional public InvitationView invite(String actor,String rawCode,String email,String correlation){var code=lockedCode(rawCode);if(!code.getOwnerUserId().equals(actor))throw new ReferralException("NOT_CODE_OWNER","Only the code owner can invite");if(!code.usableAt(Instant.now()))throw new ReferralException("CODE_UNAVAILABLE","Referral code is unavailable");String emailHash=hashing.email(email);if(invitations.existsByInviterUserIdAndEmailHash(actor,emailHash))throw new ReferralException("ALREADY_INVITED","This address was already invited");var invitation=invitations.save(ReferralInvitationEntity.create(code,actor,emailHash));outbox.append("referral.invitation.created",invitation.getId().toString(),correlation,Map.of("invitationId",invitation.getId(),"code",code.getCode(),"inviterUserId",actor,"emailHash",emailHash));return invitationView(invitation);}
 @Transactional public AttributionView redeem(String user,String rawCode,String deviceFingerprint,String correlation){var code=lockedCode(rawCode);return attributionView(attribute(code,null,user,AttributionSource.DIRECT_CODE,hashing.fingerprint(deviceFingerprint),correlation));}
 @Transactional public void onUserCreated(UUID eventId,String user,String email,String correlation){if(attributions.findByReferredUserId(user).isPresent())return;var invitation=invitations.findFirstByEmailHashAndStatusOrderByCreatedAtAsc(hashing.email(email),InvitationStatus.PENDING).orElse(null);if(invitation==null)return;var code=lockedCode(invitation.getCode().getCode());var attribution=attribute(code,invitation,user,AttributionSource.INVITATION,null,correlation);invitation.accept(user);invitations.save(invitation);history.save(new ReferralHistoryEntity(attribution.getId(),user,"INVITATION_ACCEPTED","Matched user.created event "+eventId));}
 @Transactional public void onMissionCompleted(UUID eventId,String user,String correlation){for(var attribution:attributions.findByReferredUserIdAndStatus(user,AttributionStatus.PENDING_QUALIFICATION)){attribution.qualify(eventId);history.save(new ReferralHistoryEntity(attribution.getId(),user,"QUALIFIED","Mission completion "+eventId));grant(attribution,BeneficiaryType.REFERRER,"REFERRAL_REFERRER","Récompense de parrainage",referrerReward,correlation);grant(attribution,BeneficiaryType.REFERRED,"REFERRAL_WELCOME","Récompense de bienvenue",referredReward,correlation);attribution.rewarded();attributions.save(attribution);outbox.append("referral.completed",attribution.getId().toString(),correlation,Map.of("attributionId",attribution.getId(),"referrerUserId",attribution.getReferrerUserId(),"referredUserId",user));}}
 private ReferralAttributionEntity attribute(ReferralCodeEntity code,ReferralInvitationEntity invitation,String user,AttributionSource source,String deviceHash,String correlation){fraud.validate(code,user,deviceHash);code.consume();codes.save(code);var attribution=attributions.save(ReferralAttributionEntity.create(code,invitation,user,source,deviceHash));history.save(new ReferralHistoryEntity(attribution.getId(),user,"ATTRIBUTED","source="+source+",code="+code.getCode()));counter.evictCode(code.getCode());outbox.append("referral.attributed",attribution.getId().toString(),correlation,Map.of("attributionId",attribution.getId(),"referrerUserId",code.getOwnerUserId(),"referredUserId",user,"source",source.name()));return attribution;}
 private void grant(ReferralAttributionEntity a,BeneficiaryType type,String rewardCode,String title,int amount,String correlation){if(rewards.existsByAttributionIdAndBeneficiaryType(a.getId(),type))return;var reward=rewards.save(ReferralRewardEntity.grant(a,type,rewardCode,title,amount));history.save(new ReferralHistoryEntity(a.getId(),reward.getBeneficiaryUserId(),"REWARD_GRANTED","type="+type+",amount="+amount));outbox.append("referral.reward.granted",reward.getId().toString(),correlation,Map.of("rewardId",reward.getId(),"attributionId",a.getId(),"userId",reward.getBeneficiaryUserId(),"beneficiaryType",type.name(),"rewardCode",rewardCode,"amount",amount));}
 @Transactional public void disable(String owner,UUID id,String correlation){var code=codes.findById(id).orElseThrow(()->new NoSuchElementException("Referral code not found"));if(!code.getOwnerUserId().equals(owner))throw new ReferralException("NOT_CODE_OWNER","Only the code owner can disable it");code.disable();codes.save(code);counter.evictCode(code.getCode());outbox.append("referral.code.disabled",id.toString(),correlation,Map.of("codeId",id,"ownerUserId",owner));}
 @Transactional(readOnly=true)public List<CodeView>codes(String user){return codes.findByOwnerUserIdOrderByCreatedAtDesc(user).stream().map(this::codeView).toList();}
 @Transactional(readOnly=true)public List<InvitationView>invitations(String user){return invitations.findByInviterUserIdOrderByCreatedAtDesc(user).stream().map(this::invitationView).toList();}
 @Transactional(readOnly=true)public List<AttributionView>attributions(String user){return attributions.findByReferrerUserIdOrReferredUserIdOrderByAttributedAtDesc(user,user).stream().map(this::attributionView).toList();}
 @Transactional(readOnly=true)public List<RewardView>rewards(String user){return rewards.findByBeneficiaryUserIdOrderByCreatedAtDesc(user).stream().map(this::rewardView).toList();}
 @Transactional(readOnly=true)public List<HistoryView>history(String user,UUID attributionId){var attribution=attributions.findById(attributionId).orElseThrow(()->new NoSuchElementException("Attribution not found"));if(!user.equals(attribution.getReferrerUserId())&&!user.equals(attribution.getReferredUserId()))throw new ReferralException("FORBIDDEN_HISTORY","History is not accessible");return history.findByAttributionIdOrderByOccurredAtAsc(attributionId).stream().map(h->new HistoryView(h.getId(),h.getAttributionId(),h.getAction(),h.getDetails(),h.getOccurredAt())).toList();}
 private ReferralCodeEntity lockedCode(String code){return codes.findLockedByCode(code.trim()).orElseThrow(()->new ReferralException("CODE_NOT_FOUND","Referral code not found"));}
 private CodeView codeView(ReferralCodeEntity c){return new CodeView(c.getId(),c.getCode(),c.getStatus(),c.getMaxUses(),c.getUsageCount(),c.getExpiresAt(),c.getCreatedAt());}
 private InvitationView invitationView(ReferralInvitationEntity i){return new InvitationView(i.getId(),i.getCode().getCode(),i.getStatus(),i.getInvitedUserId(),i.getCreatedAt());}
 private AttributionView attributionView(ReferralAttributionEntity a){return new AttributionView(a.getId(),a.getCode().getCode(),a.getReferrerUserId(),a.getReferredUserId(),a.getSource(),a.getStatus(),a.getAttributedAt(),a.getQualifiedAt(),a.getRewardedAt());}
 private RewardView rewardView(ReferralRewardEntity r){return new RewardView(r.getId(),r.getRewardCode(),r.getTitle(),r.getAmount(),r.getBeneficiaryType(),r.getStatus(),r.getCreatedAt());}
}
