package com.yeyamo_mobile.api.event_service.service;
import java.time.Instant;import java.util.UUID;import org.springframework.data.domain.*;import org.springframework.data.jpa.domain.Specification;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import com.yeyamo_mobile.api.event_service.dto.*;import com.yeyamo_mobile.api.event_service.enums.EventStatus;import com.yeyamo_mobile.api.event_service.event.EventPublisher;import com.yeyamo_mobile.api.event_service.exception.ApiException;import com.yeyamo_mobile.api.event_service.models.Event;import com.yeyamo_mobile.api.event_service.repository.EventRepository;
@Service public class AdminEventService{
 private final EventRepository repository;private final EventPublisher publisher;public AdminEventService(EventRepository repository,EventPublisher publisher){this.repository=repository;this.publisher=publisher;}
 @Transactional(readOnly=true)public Page<AdminEventResponse>search(String search,EventStatus status,Long regionId,Long cityId,UUID organizerId,UUID partnerId,UUID placeId,Long categoryId,Instant startFrom,Instant startTo,Pageable pageable){Specification<Event>s=(r,q,c)->c.conjunction();if(search!=null&&!search.isBlank())s=s.and((r,q,c)->c.like(c.lower(r.get("title")),"%"+search.trim().toLowerCase()+"%"));if(status!=null)s=s.and((r,q,c)->c.equal(r.get("status"),status));if(regionId!=null)s=s.and((r,q,c)->c.equal(r.get("regionId"),regionId));if(cityId!=null)s=s.and((r,q,c)->c.equal(r.get("cityId"),cityId));if(organizerId!=null)s=s.and((r,q,c)->c.equal(r.get("organizerId"),organizerId));if(partnerId!=null)s=s.and((r,q,c)->c.equal(r.get("partnerId"),partnerId));if(placeId!=null)s=s.and((r,q,c)->c.equal(r.get("placeId"),placeId));if(categoryId!=null)s=s.and((r,q,c)->c.equal(r.get("categoryId"),categoryId));if(startFrom!=null)s=s.and((r,q,c)->c.greaterThanOrEqualTo(r.get("startAt"),startFrom));if(startTo!=null)s=s.and((r,q,c)->c.lessThanOrEqualTo(r.get("startAt"),startTo));return repository.findAll(s,pageable).map(AdminEventResponse::from);}
 @Transactional(readOnly=true)public AdminEventResponse get(UUID id){return AdminEventResponse.from(required(id));}
 @Transactional public AdminEventResponse create(AdminEventRequest request,String correlation,String actor){validate(request);Event e=new Event();apply(e,request);e.setRegisteredCount(0);if(e.getStatus()==null)e.setStatus(EventStatus.DRAFT);Event saved=repository.save(e);publisher.publishCreated(saved,correlation,actor);return AdminEventResponse.from(saved);}
 @Transactional public AdminEventResponse update(UUID id,AdminEventRequest request,String correlation,String actor){Event e=required(id);if(java.util.Set.of(EventStatus.ARCHIVED,EventStatus.CANCELLED,EventStatus.COMPLETED).contains(e.getStatus()))throw conflict("EVENT_NOT_MODIFIABLE");validate(request);apply(e,request);Event saved=repository.save(e);publisher.publishUpdated(saved,correlation,actor);return AdminEventResponse.from(saved);}
 @Transactional public AdminEventResponse transition(UUID id,EventStatus target,String reason,String correlation,String actor){Event e=required(id);if(!allowed(e.getStatus(),target))throw conflict("INVALID_STATUS_TRANSITION");e.setStatus(target);Event saved=repository.save(e);if(target==EventStatus.CANCELLED)publisher.publishCancelled(saved,correlation,actor);else if(target==EventStatus.COMPLETED)publisher.publishCompleted(saved,correlation,actor);else publisher.publishUpdated(saved,correlation,actor);return AdminEventResponse.from(saved);}
 private boolean allowed(EventStatus current,EventStatus target){return switch(current){case DRAFT->target==EventStatus.PENDING_REVIEW||target==EventStatus.ARCHIVED;case PENDING,PENDING_REVIEW->java.util.Set.of(EventStatus.PUBLISHED,EventStatus.REJECTED,EventStatus.ARCHIVED).contains(target);case PUBLISHED->java.util.Set.of(EventStatus.SUSPENDED,EventStatus.CANCELLED,EventStatus.COMPLETED,EventStatus.ARCHIVED).contains(target);case SUSPENDED->java.util.Set.of(EventStatus.PUBLISHED,EventStatus.REJECTED,EventStatus.ARCHIVED).contains(target);case REJECTED->java.util.Set.of(EventStatus.DRAFT,EventStatus.ARCHIVED).contains(target);case ARCHIVED,CANCELLED,COMPLETED->false;};}
 private void validate(AdminEventRequest r){if(!r.endAt().isAfter(r.startAt()))throw new ApiException("INVALID_DATES","La date de fin doit etre posterieure au debut",HttpStatus.BAD_REQUEST);}
 private void apply(Event e,AdminEventRequest r){e.setPlaceId(r.placeId());e.setOrganizerId(r.organizerId());e.setPartnerId(r.partnerId());e.setRegionId(r.regionId());e.setCityId(r.cityId());e.setCategoryId(r.categoryId());e.setTitle(r.title());e.setDescription(r.description());e.setStartAt(r.startAt());e.setEndAt(r.endAt());e.setCapacity(r.capacity());if(r.status()!=null)e.setStatus(r.status());}
 private Event required(UUID id){return repository.findById(id).orElseThrow(()->new ApiException("EVENT_NOT_FOUND","Evenement introuvable",HttpStatus.NOT_FOUND));}private ApiException conflict(String code){return new ApiException(code,"Transition evenement non autorisee",HttpStatus.CONFLICT);}
}
