spring.application.name=commerce-service
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://config-server:8080}
spring.cloud.config.username=${CONFIG_SERVER_USERNAME}
spring.cloud.config.password=${CONFIG_SERVER_PASSWORD}
server.port=${SERVER_PORT:8113}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
