package com.yeyamo_mobile.api.payment_service.application;
import static com.yeyamo_mobile.api.payment_service.application.AdminPaymentDtos.*;import java.time.Instant;import java.util.*;import org.springframework.data.domain.*;import org.springframework.data.jpa.domain.Specification;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import com.yeyamo_mobile.api.payment_service.application.PaymentViews.RefundView;import com.yeyamo_mobile.api.payment_service.application.port.PaymentOutboxPort;import com.yeyamo_mobile.api.payment_service.domain.PaymentStatus;import com.yeyamo_mobile.api.payment_service.infrastructure.persistence.*;import jakarta.persistence.criteria.Predicate;
@Service public class AdminPaymentService{private final PaymentRepository payments;private final RefundRepository refunds;private final ReconciliationJobRepository jobs;private final PaymentOutboxPort outbox;public AdminPaymentService(PaymentRepository p,RefundRepository r,ReconciliationJobRepository j,PaymentOutboxPort o){payments=p;refunds=r;jobs=j;outbox=o;}
 @Transactional(readOnly=true)public Page<AdminPaymentSummary>list(String search,PaymentStatus status,String provider,String currency,String userId,String partnerId,UUID bookingId,String providerPaymentId,String idempotencyKey,Instant from,Instant to,Pageable pageable){Pageable safe=PageRequest.of(pageable.getPageNumber(),Math.min(pageable.getPageSize(),200),pageable.getSort());return payments.findAll(spec(search,status,provider,currency,userId,partnerId,bookingId,providerPaymentId,idempotencyKey,from,to),safe).map(this::summary);}
 @Transactional(readOnly=true)public AdminPaymentDetail detail(UUID id){PaymentEntity p=payments.findById(id).orElseThrow();List<RefundView>rs=refunds.findByPaymentIdOrderByCreatedAtDesc(id).stream().map(RefundView::from).toList();List<TimelineEntry>timeline=new ArrayList<>();timeline.add(new TimelineEntry("CREATED",p.getCreatedAt(),null));if(p.getAuthorizedAt()!=null)timeline.add(new TimelineEntry("AUTHORIZED",p.getAuthorizedAt(),null));if(p.getCancelledAt()!=null)timeline.add(new TimelineEntry("CANCELLED",p.getCancelledAt(),null));if(p.getRefundedAt()!=null)timeline.add(new TimelineEntry("REFUNDED",p.getRefundedAt(),null));return new AdminPaymentDetail(summary(p),null,null,null,rs,null,timeline,p.getIdempotencyKey(),p.getFailureReason(),null);}
 @Transactional(readOnly=true)public List<PaymentAnomaly>anomalies(){List<PaymentAnomaly>result=new ArrayList<>();for(String providerId:payments.duplicateProviderTransactions())result.add(new PaymentAnomaly("DUPLICATE_PROVIDER_TRANSACTION",null,"CRITICAL","Provider transaction duplicated: "+providerId));for(UUID id:refunds.inconsistentRefundPayments())result.add(new PaymentAnomaly("REFUND_INCONSISTENCY",id,"CRITICAL","Successful refunds exceed payment amount"));return result;}
 @Transactional public ReconciliationResponse reconcile(String actor,String correlation){ReconciliationJobEntity job=jobs.save(ReconciliationJobEntity.queued(actor,correlation));outbox.append("RECONCILIATION_STARTED",job.getId().toString(),correlation,Map.of("jobId",job.getId(),"actorId",actor));return new ReconciliationResponse(job.getId(),job.getStatus());}
 @Transactional public void processQueued(){for(ReconciliationJobEntity job:jobs.findTop10ByStatusOrderByCreatedAtAsc("QUEUED")){job.complete(anomalies().size());jobs.save(job);outbox.append("payment.reconciliation.completed",job.getId().toString(),job.getCorrelationId(),Map.of("jobId",job.getId()));}}
 private Specification<PaymentEntity>spec(String search,PaymentStatus status,String provider,String currency,String userId,String partnerId,UUID bookingId,String providerId,String key,Instant from,Instant to){return(root,q,b)->{List<Predicate>p=new ArrayList<>();if(text(search)){String l="%"+search.trim().toLowerCase()+"%";p.add(b.or(b.like(b.lower(root.get("userId")),l),b.like(b.lower(root.get("providerPaymentId")),l),b.like(b.lower(root.get("idempotencyKey")),l)));}if(status!=null)p.add(b.equal(root.get("status"),status));if(text(provider))p.add(b.equal(root.get("provider"),provider));if(text(currency))p.add(b.equal(root.get("currency"),currency.toUpperCase()));if(text(userId))p.add(b.equal(root.get("userId"),userId));if(text(partnerId))p.add(b.equal(root.get("partnerId"),partnerId));if(bookingId!=null)p.add(b.equal(root.get("bookingId"),bookingId));if(text(providerId))p.add(b.equal(root.get("providerPaymentId"),providerId));if(text(key))p.add(b.equal(root.get("idempotencyKey"),key));if(from!=null)p.add(b.greaterThanOrEqualTo(root.get("createdAt"),from));if(to!=null)p.add(b.lessThanOrEqualTo(root.get("createdAt"),to));return b.and(p.toArray(Predicate[]::new));};}
 private AdminPaymentSummary summary(PaymentEntity p){Instant completed=p.getAuthorizedAt()!=null?p.getAuthorizedAt():(p.getRefundedAt()!=null?p.getRefundedAt():p.getCancelledAt());return new AdminPaymentSummary(p.getId(),p.getBookingId(),p.getUserId(),p.getPartnerId(),p.getProvider(),p.getProviderPaymentId(),p.getAmount(),p.getCurrency(),p.getStatus(),p.getCreatedAt(),completed);}private boolean text(String v){return v!=null&&!v.isBlank();}}
