package com.yeyamo_mobile.api.partner_service.domain.model;
public enum BusinessType { INDIVIDUAL, COMPANY, ASSOCIATION, PUBLIC_ORGANIZATION, BUSINESS, ARTISAN, ARTIST, CULTURAL_ASSOCIATION, MUSEUM, CULTURAL_EXPERT, TOURISM_OPERATOR }
