package com.yeyamo_mobile.api.partner_service.domain.model;

import java.time.Instant;
import java.util.Set;
import java.util.UUID;

public class Partner {
 private static final Set<PartnerStatus> EDITABLE=Set.of(PartnerStatus.DRAFT,PartnerStatus.NEEDS_INFO,PartnerStatus.REQUIRES_CHANGES,PartnerStatus.REJECTED);
 private UUID id; private String ownerUserId; private String legalName; private String tradeName; private BusinessType businessType;
 private String registrationNumber; private String taxId; private String contactEmail; private String contactPhone;
 private String websiteUrl; private String description; private PartnerStatus status; private String reviewComment;
 private String primaryCountryCode; private Set<String> operatingCountries=new java.util.LinkedHashSet<>();
 private Integer riskScore; private Instant submittedAt; private Instant verifiedAt; private Instant createdAt;
 private Instant updatedAt; private Instant deletedAt; private long version;

 public static Partner create(String owner,String legalName,BusinessType type,String email){Partner p=new Partner();Instant now=Instant.now();p.id=UUID.randomUUID();p.ownerUserId=req(owner,"ownerUserId");p.legalName=req(legalName,"legalName");p.businessType=type==null?BusinessType.INDIVIDUAL:type;p.contactEmail=req(email,"contactEmail");p.status=PartnerStatus.DRAFT;p.createdAt=now;p.updatedAt=now;return p;}
 public void update(String legal,String trade,BusinessType type,String registration,String tax,String email,String phone,String website,String description){editable();legalName=req(legal,"legalName");tradeName=clean(trade);businessType=type==null?businessType:type;registrationNumber=clean(registration);taxId=clean(tax);contactEmail=req(email,"contactEmail");contactPhone=clean(phone);websiteUrl=clean(website);this.description=clean(description);reviewComment=null;status=PartnerStatus.DRAFT;updatedAt=Instant.now();}
 public void submit(int documents){editable();if(registrationNumber==null)throw new IllegalStateException("registrationNumber is required");if(documents<1)throw new IllegalStateException("At least one KYC document is required");status=PartnerStatus.SUBMITTED;submittedAt=Instant.now();updatedAt=submittedAt;reviewComment=null;}
 public void review(PartnerStatus decision,String comment,Integer risk){if(!Set.of(PartnerStatus.SUBMITTED,PartnerStatus.UNDER_REVIEW).contains(status))throw new IllegalStateException("Partner is not reviewable");if(!Set.of(PartnerStatus.UNDER_REVIEW,PartnerStatus.APPROVED,PartnerStatus.REJECTED,PartnerStatus.NEEDS_INFO,PartnerStatus.REQUIRES_CHANGES).contains(decision))throw new IllegalArgumentException("Unsupported decision");status=decision;reviewComment=clean(comment);riskScore=risk;updatedAt=Instant.now();if(decision==PartnerStatus.APPROVED)verifiedAt=updatedAt;}
 public void delete(){status=PartnerStatus.DELETED;deletedAt=Instant.now();updatedAt=deletedAt;} public boolean isPublic(){return status==PartnerStatus.APPROVED;} public boolean canEditDocuments(){return EDITABLE.contains(status);}
 private void editable(){if(!EDITABLE.contains(status))throw new IllegalStateException("Partner is not editable");} private static String req(String v,String n){String c=clean(v);if(c==null)throw new IllegalArgumentException(n+" is required");return c;}private static String clean(String v){return v==null||v.isBlank()?null:v.trim();}
 public UUID getId(){return id;}public void setId(UUID v){id=v;}public String getOwnerUserId(){return ownerUserId;}public void setOwnerUserId(String v){ownerUserId=v;}public String getLegalName(){return legalName;}public void setLegalName(String v){legalName=v;}public String getTradeName(){return tradeName;}public void setTradeName(String v){tradeName=v;}public BusinessType getBusinessType(){return businessType;}public void setBusinessType(BusinessType v){businessType=v;}public String getRegistrationNumber(){return registrationNumber;}public void setRegistrationNumber(String v){registrationNumber=v;}public String getTaxId(){return taxId;}public void setTaxId(String v){taxId=v;}public String getContactEmail(){return contactEmail;}public void setContactEmail(String v){contactEmail=v;}public String getContactPhone(){return contactPhone;}public void setContactPhone(String v){contactPhone=v;}public String getWebsiteUrl(){return websiteUrl;}public void setWebsiteUrl(String v){websiteUrl=v;}public String getDescription(){return description;}public void setDescription(String v){description=v;}public PartnerStatus getStatus(){return status;}public void setStatus(PartnerStatus v){status=v;}public String getReviewComment(){return reviewComment;}public void setReviewComment(String v){reviewComment=v;}public Integer getRiskScore(){return riskScore;}public void setRiskScore(Integer v){riskScore=v;}public Instant getSubmittedAt(){return submittedAt;}public void setSubmittedAt(Instant v){submittedAt=v;}public Instant getVerifiedAt(){return verifiedAt;}public void setVerifiedAt(Instant v){verifiedAt=v;}public Instant getCreatedAt(){return createdAt;}public void setCreatedAt(Instant v){createdAt=v;}public Instant getUpdatedAt(){return updatedAt;}public void setUpdatedAt(Instant v){updatedAt=v;}public Instant getDeletedAt(){return deletedAt;}public void setDeletedAt(Instant v){deletedAt=v;}public long getVersion(){return version;}public void setVersion(long v){version=v;}public String getPrimaryCountryCode(){return primaryCountryCode;}public void setPrimaryCountryCode(String v){primaryCountryCode=v==null?null:v.toUpperCase(java.util.Locale.ROOT);}public Set<String>getOperatingCountries(){return Set.copyOf(operatingCountries);}public void setOperatingCountries(Set<String> v){operatingCountries=v==null?new java.util.LinkedHashSet<>():new java.util.LinkedHashSet<>(v);}
}
