ALTER TABLE events ADD COLUMN IF NOT EXISTS publish_to_feed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE events ADD COLUMN IF NOT EXISTS publish_to_story BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE events ADD COLUMN IF NOT EXISTS feed_distribution_status VARCHAR(40) NOT NULL DEFAULT 'NOT_REQUESTED';
ALTER TABLE events ADD COLUMN IF NOT EXISTS story_distribution_status VARCHAR(40) NOT NULL DEFAULT 'NOT_REQUESTED';
ALTER TABLE events ADD COLUMN IF NOT EXISTS feed_post_id UUID;
ALTER TABLE events ADD COLUMN IF NOT EXISTS story_id UUID;
ALTER TABLE events ADD COLUMN IF NOT EXISTS feed_distribution_reason VARCHAR(1000);
ALTER TABLE events ADD COLUMN IF NOT EXISTS story_distribution_reason VARCHAR(1000);

CREATE TABLE IF NOT EXISTS event_social_distribution_receipts (
    event_id UUID PRIMARY KEY,
    event_type VARCHAR(120) NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL
);
