package com.yeyamo_mobile.api.notification_service.newsletter;
import static com.yeyamo_mobile.api.notification_service.newsletter.NewsletterDtos.*;
import java.time.Instant;import java.util.*;import com.fasterxml.jackson.databind.ObjectMapper;import org.springframework.beans.factory.annotation.Value;import org.springframework.data.domain.*;import org.springframework.kafka.core.KafkaTemplate;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service @Transactional public class NewsletterApplicationService {
 private final NewsletterCampaignRepository campaigns;private final NewsletterCampaignStatsRepository stats;private final ObjectMapper mapper;private final KafkaTemplate<String,String> kafka;private final String topic;
 public NewsletterApplicationService(NewsletterCampaignRepository c,NewsletterCampaignStatsRepository s,ObjectMapper m,KafkaTemplate<String,String> k,@Value("${yeyamo.kafka.topics.newsletter-dispatch:newsletter.dispatch}")String topic){campaigns=c;stats=s;mapper=m;kafka=k;this.topic=topic;}
 @Transactional(readOnly=true)public Page<CampaignResponse> list(NewsletterStatus status,String search,Pageable pageable){return campaigns.findAll((root,q,cb)->{var p=new ArrayList<jakarta.persistence.criteria.Predicate>();if(status!=null)p.add(cb.equal(root.get("status"),status));if(search!=null&&!search.isBlank()){String like="%"+search.trim().toLowerCase(Locale.ROOT)+"%";p.add(cb.or(cb.like(cb.lower(root.get("name")),like),cb.like(cb.lower(root.get("subject")),like)));}return cb.and(p.toArray(jakarta.persistence.criteria.Predicate[]::new));},pageable).map(this::response);}
 @Transactional(readOnly=true)public CampaignResponse get(UUID id){return response(find(id));}
 public CampaignResponse create(String actor,CampaignRequest r){Instant now=Instant.now();var c=new NewsletterCampaignEntity();c.id=UUID.randomUUID();apply(c,r);c.status=NewsletterStatus.DRAFT;c.createdBy=actor;c.createdAt=now;c.updatedAt=now;campaigns.save(c);var s=new NewsletterCampaignStatsEntity();s.campaignId=c.id;s.updatedAt=now;stats.save(s);return response(c);}
 public CampaignResponse update(UUID id,CampaignRequest r){var c=find(id);require(c,NewsletterStatus.DRAFT,NewsletterStatus.PAUSED);apply(c,r);c.updatedAt=Instant.now();return response(campaigns.save(c));}
 public CampaignResponse schedule(UUID id,ScheduleRequest r){var c=find(id);require(c,NewsletterStatus.DRAFT,NewsletterStatus.PAUSED);c.status=NewsletterStatus.SCHEDULED;c.scheduledAt=r.scheduledAt();c.updatedAt=Instant.now();return response(campaigns.save(c));}
 public CampaignResponse send(UUID id){var c=find(id);if(EnumSet.of(NewsletterStatus.QUEUED,NewsletterStatus.SENDING,NewsletterStatus.SENT).contains(c.status))return response(c);require(c,NewsletterStatus.DRAFT,NewsletterStatus.PAUSED,NewsletterStatus.SCHEDULED,NewsletterStatus.FAILED);queue(c);return response(c);}
 public CampaignResponse pause(UUID id){var c=find(id);require(c,NewsletterStatus.SCHEDULED);c.status=NewsletterStatus.PAUSED;c.updatedAt=Instant.now();return response(campaigns.save(c));}
 public CampaignResponse cancel(UUID id){var c=find(id);require(c,NewsletterStatus.DRAFT,NewsletterStatus.SCHEDULED,NewsletterStatus.PAUSED);c.status=NewsletterStatus.CANCELLED;c.updatedAt=Instant.now();return response(campaigns.save(c));}
 @Transactional(readOnly=true)public StatsResponse stats(UUID id){find(id);var s=stats.findById(id).orElseThrow();return new StatsResponse(id,s.delivered,s.failed,s.opened,s.clicked,s.unsubscribed,s.updatedAt);}
 @Scheduled(fixedDelayString="${newsletter.scheduler.delay-ms:30000}")public void dispatchDue(){campaigns.findDue(Instant.now()).forEach(this::queue);}
 private void queue(NewsletterCampaignEntity c){if(c.dispatchKey!=null||EnumSet.of(NewsletterStatus.QUEUED,NewsletterStatus.SENDING,NewsletterStatus.SENT).contains(c.status))return;c.dispatchKey=UUID.randomUUID();c.status=NewsletterStatus.QUEUED;c.updatedAt=Instant.now();campaigns.save(c);try{kafka.send(topic,c.id.toString(),mapper.writeValueAsString(Map.of("eventId",c.dispatchKey,"eventType","newsletter.dispatch.requested","campaignId",c.id,"segment",mapper.readTree(c.segmentJson),"occurredAt",c.updatedAt))).get();}catch(Exception e){c.dispatchKey=null;c.status=NewsletterStatus.FAILED;campaigns.save(c);throw new IllegalStateException("NEWSLETTER_DISPATCH_UNAVAILABLE",e);}}
 private void apply(NewsletterCampaignEntity c,CampaignRequest r){c.name=r.name().trim();c.subject=r.subject().trim();c.preheader=blank(r.preheader());c.content=sanitize(r.content());c.segmentJson=write(r.audience());}
 private String sanitize(String content){String value=content.trim();if(value.matches("(?is).*(<script|javascript:|onerror\\s*=|onload\\s*=).*"))throw new IllegalArgumentException("Unsafe newsletter content");return value;}
 private NewsletterCampaignEntity find(UUID id){return campaigns.findById(id).orElseThrow(()->new NoSuchElementException("Newsletter not found"));}
 private void require(NewsletterCampaignEntity c,NewsletterStatus...allowed){if(Arrays.stream(allowed).noneMatch(s->s==c.status))throw new IllegalStateException("Invalid newsletter transition from "+c.status);}
 private CampaignResponse response(NewsletterCampaignEntity c){return new CampaignResponse(c.id,c.name,c.subject,c.preheader,c.content,c.status,read(c.segmentJson),c.scheduledAt,c.createdBy,c.createdAt,c.updatedAt);}
 private String write(Object o){try{return mapper.writeValueAsString(o);}catch(Exception e){throw new IllegalArgumentException("Invalid audience",e);}}private Segment read(String s){try{return mapper.readValue(s,Segment.class);}catch(Exception e){throw new IllegalStateException(e);}}private String blank(String s){return s==null||s.isBlank()?null:s.trim();}
}
