package com.yeyamo_mobile.api.interaction_service.interfaces.rest;
import java.time.Instant;import java.util.*;import org.springframework.data.domain.*;import org.springframework.data.jpa.domain.Specification;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import com.yeyamo_mobile.api.interaction_service.application.port.InteractionOutboxPort;import com.yeyamo_mobile.api.interaction_service.domain.model.CommentStatus;import com.yeyamo_mobile.api.interaction_service.infrastructure.persistence.*;
@RestController@RequestMapping("/api/v1/admin")@PreAuthorize("hasAnyRole('MODERATOR','ADMIN','SUPER_ADMIN')")
public class AdminContentController{
 private final SpringReviewRepository reviews;private final SpringCommentRepository comments;private final ContentModerationAuditRepository audits;private final InteractionOutboxPort outbox;public AdminContentController(SpringReviewRepository r,SpringCommentRepository c,ContentModerationAuditRepository a,InteractionOutboxPort o){reviews=r;comments=c;audits=a;outbox=o;}
 public record ActionRequest(String reason){}public record History(String action,String actorId,String reason,String correlationId,Instant timestamp){}public record ReviewView(UUID id,String authorId,UUID targetId,short score,String content,String status,Instant createdAt,Instant deletedAt,String deletedBy,String deletionReason,Integer reportsCount,List<History>moderationHistory){}public record CommentView(UUID id,String authorId,UUID targetId,UUID parentId,String content,String status,boolean locked,Instant createdAt,Instant deletedAt,String deletedBy,String deletionReason,Integer reportsCount,List<History>moderationHistory){}
 @GetMapping("/reviews")public Page<ReviewView>reviews(@RequestParam(required=false)String search,@RequestParam(required=false)String authorId,@RequestParam(required=false)UUID targetId,@RequestParam(required=false)String status,@RequestParam(required=false)Short score,@RequestParam(required=false)Instant createdFrom,@RequestParam(required=false)Instant createdTo,Pageable p){Specification<ReviewEntity>s=(r,q,c)->c.conjunction();if(search!=null)s=s.and((r,q,c)->c.like(c.lower(r.get("comment")),"%"+search.toLowerCase()+"%"));if(authorId!=null)s=s.and((r,q,c)->c.equal(r.get("userId"),authorId));if(targetId!=null)s=s.and((r,q,c)->c.equal(r.get("placeId"),targetId));if(status!=null)s=s.and((r,q,c)->c.equal(r.get("status"),status));if(score!=null)s=s.and((r,q,c)->c.equal(r.get("rating"),score));if(createdFrom!=null)s=s.and((r,q,c)->c.greaterThanOrEqualTo(r.get("createdAt"),createdFrom));if(createdTo!=null)s=s.and((r,q,c)->c.lessThanOrEqualTo(r.get("createdAt"),createdTo));return reviews.findAll(s,p).map(this::view);}
 @GetMapping("/reviews/{id}")public ReviewView review(@PathVariable UUID id){return view(reviewEntity(id));}
 @PatchMapping("/reviews/{id}/hide")public ReviewView hideReview(@PathVariable UUID id,@RequestBody ActionRequest r,Authentication a,@RequestHeader(value="X-Correlation-ID",required=false)String c){return reviewState(id,"HIDDEN","REVIEW_HIDDEN",r.reason(),a.getName(),c);}
 @PatchMapping("/reviews/{id}/restore")public ReviewView restoreReview(@PathVariable UUID id,@RequestBody ActionRequest r,Authentication a,@RequestHeader(value="X-Correlation-ID",required=false)String c){return reviewState(id,"ACTIVE","REVIEW_RESTORED",r.reason(),a.getName(),c);}
 @DeleteMapping("/reviews/{id}")public ReviewView deleteReview(@PathVariable UUID id,@RequestBody ActionRequest r,Authentication a,@RequestHeader(value="X-Correlation-ID",required=false)String c){ReviewEntity e=reviewEntity(id);e.setDeletedAt(Instant.now());e.setDeletedBy(a.getName());e.setDeletionReason(r.reason());e.setStatus("DELETED");reviews.save(e);record("REVIEW",id,"REVIEW_DELETED",a.getName(),r.reason(),c);emit("interaction.review.deleted",id,a.getName(),c);return view(e);}
 @GetMapping("/comments")public Page<CommentView>comments(@RequestParam(required=false)String search,@RequestParam(required=false)String authorId,@RequestParam(required=false)UUID targetId,@RequestParam(required=false)CommentStatus status,@RequestParam(required=false)Instant createdFrom,@RequestParam(required=false)Instant createdTo,Pageable p){Specification<CommentEntity>s=(r,q,c)->c.conjunction();if(search!=null)s=s.and((r,q,c)->c.like(c.lower(r.get("body")),"%"+search.toLowerCase()+"%"));if(authorId!=null)s=s.and((r,q,c)->c.equal(r.get("authorId"),authorId));if(targetId!=null)s=s.and((r,q,c)->c.equal(r.get("postId"),targetId));if(status!=null)s=s.and((r,q,c)->c.equal(r.get("status"),status));if(createdFrom!=null)s=s.and((r,q,c)->c.greaterThanOrEqualTo(r.get("createdAt"),createdFrom));if(createdTo!=null)s=s.and((r,q,c)->c.lessThanOrEqualTo(r.get("createdAt"),createdTo));return comments.findAll(s,p).map(this::view);}
 @GetMapping("/comments/{id}")public CommentView comment(@PathVariable UUID id){return view(commentEntity(id));}
 @PatchMapping("/comments/{id}/hide")public CommentView hideComment(@PathVariable UUID id,@RequestBody ActionRequest r,Authentication a,@RequestHeader(value="X-Correlation-ID",required=false)String c){return commentState(id,CommentStatus.HIDDEN,"COMMENT_HIDDEN",r.reason(),a.getName(),c);}
 @PatchMapping("/comments/{id}/restore")public CommentView restoreComment(@PathVariable UUID id,@RequestBody ActionRequest r,Authentication a,@RequestHeader(value="X-Correlation-ID",required=false)String c){return commentState(id,CommentStatus.ACTIVE,"COMMENT_RESTORED",r.reason(),a.getName(),c);}
 @DeleteMapping("/comments/{id}")public CommentView deleteComment(@PathVariable UUID id,@RequestBody ActionRequest r,Authentication a,@RequestHeader(value="X-Correlation-ID",required=false)String c){CommentEntity e=commentEntity(id);e.setDeletedAt(Instant.now());e.setDeletedBy(a.getName());e.setDeletionReason(r.reason());e.setStatus(CommentStatus.DELETED);comments.save(e);record("COMMENT",id,"COMMENT_DELETED",a.getName(),r.reason(),c);emit("interaction.comment.deleted",id,a.getName(),c);return view(e);}
 @PostMapping("/comments/{id}/lock")public CommentView lock(@PathVariable UUID id,@RequestBody ActionRequest r,Authentication a,@RequestHeader(value="X-Correlation-ID",required=false)String c){CommentEntity e=commentEntity(id);e.setLocked(true);comments.save(e);record("COMMENT",id,"COMMENT_LOCKED",a.getName(),r.reason(),c);return view(e);}
 private ReviewView reviewState(UUID id,String state,String action,String reason,String actor,String c){ReviewEntity e=reviewEntity(id);e.setStatus(state);reviews.save(e);record("REVIEW",id,action,actor,reason,c);emit("interaction.review."+state.toLowerCase(),id,actor,c);return view(e);}private CommentView commentState(UUID id,CommentStatus state,String action,String reason,String actor,String c){CommentEntity e=commentEntity(id);e.setStatus(state);comments.save(e);record("COMMENT",id,action,actor,reason,c);emit("interaction.comment."+state.name().toLowerCase(),id,actor,c);return view(e);}
 private void record(String t,UUID id,String action,String actor,String reason,String c){audits.save(new ContentModerationAudit(t,id,action,actor,reason,c));}private void emit(String t,UUID id,String actor,String c){outbox.append(t,"CONTENT",id.toString(),actor,c,Map.of("contentId",id));}private ReviewEntity reviewEntity(UUID id){return reviews.findById(id).orElseThrow();}private CommentEntity commentEntity(UUID id){return comments.findById(id).orElseThrow();}private List<History>history(String t,UUID id){return audits.findByContentTypeAndContentIdOrderByCreatedAtDesc(t,id).stream().map(a->new History(a.getAction(),a.getActorId(),a.getReason(),a.getCorrelationId(),a.getCreatedAt())).toList();}private ReviewView view(ReviewEntity e){return new ReviewView(e.getId(),e.getUserId(),e.getPlaceId(),e.getRating(),e.getComment(),e.getStatus(),e.getCreatedAt(),e.getDeletedAt(),e.getDeletedBy(),e.getDeletionReason(),null,history("REVIEW",e.getId()));}private CommentView view(CommentEntity e){return new CommentView(e.getId(),e.getAuthorId(),e.getPostId(),e.getParentId(),e.getBody(),e.getStatus().name(),e.isLocked(),e.getCreatedAt(),e.getDeletedAt(),e.getDeletedBy(),e.getDeletionReason(),null,history("COMMENT",e.getId()));}
}
