package com.yeyamo_mobile.api.catalog_service.application;

import com.yeyamo_mobile.api.catalog_service.application.port.OutboxPort;
import com.yeyamo_mobile.api.catalog_service.domain.model.*;
import com.yeyamo_mobile.api.catalog_service.infrastructure.persistence.*;
import com.yeyamo_mobile.api.catalog_service.interfaces.rest.ArtworkDtos;
import jakarta.persistence.criteria.Predicate;
import org.springframework.data.domain.*;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;
import java.text.Normalizer;
import java.time.Instant;
import java.util.*;
import com.yeyamo_mobile.shared.country.CountryConfigClient;
import com.yeyamo_mobile.shared.country.CountryConfigClient.CountryFeature;

@Service
public class ArtworkService {
    private final ArtworkRepositories.Artworks artworks; private final SpringDataCatalogAssetRepository assets;
    private final ArtworkRepositories.Translations translations; private final ArtworkRepositories.Histories histories;
    private final ArtworkRepositories.Media media; private final OutboxPort outbox; private final CountryConfigClient countries;
    public ArtworkService(ArtworkRepositories.Artworks artworks,SpringDataCatalogAssetRepository assets,ArtworkRepositories.Translations translations,ArtworkRepositories.Histories histories,ArtworkRepositories.Media media,OutboxPort outbox){this(artworks,assets,translations,histories,media,outbox,null);}
    @Autowired public ArtworkService(ArtworkRepositories.Artworks artworks,SpringDataCatalogAssetRepository assets,ArtworkRepositories.Translations translations,ArtworkRepositories.Histories histories,ArtworkRepositories.Media media,OutboxPort outbox,CountryConfigClient countries){this.artworks=artworks;this.assets=assets;this.translations=translations;this.histories=histories;this.media=media;this.outbox=outbox;this.countries=countries;}

    @Transactional(readOnly=true) public Page<ArtworkEntity> search(String countryCode,UUID artisanId,ArtworkEntity.AvailabilityStatus availability,String query,Pageable pageable){
        return artworks.findAll((root,cq,cb)->{List<Predicate> p=new ArrayList<>();p.add(cb.isNull(root.get("deletedAt")));if(countryCode!=null)p.add(cb.equal(root.get("countryCode"),countryCode));if(artisanId!=null)p.add(cb.equal(root.get("artisanPartnerId"),artisanId));if(availability!=null)p.add(cb.equal(root.get("availabilityStatus"),availability));if(query!=null&&!query.isBlank())p.add(cb.or(cb.like(cb.lower(root.get("title")),"%"+query.toLowerCase(Locale.ROOT)+"%"),cb.like(cb.lower(root.get("story")),"%"+query.toLowerCase(Locale.ROOT)+"%")));return cb.and(p.toArray(Predicate[]::new));},pageable);
    }
    @Transactional(readOnly=true) public ArtworkDtos.Response detail(UUID id){ArtworkEntity a=find(id);return new ArtworkDtos.Response(a,translations.findByArtworkId(id),media.findByArtworkIdOrderByDisplayOrderAsc(id));}
    @Transactional public ArtworkDtos.Response create(ArtworkDtos.Request r,Jwt actor,String correlation){validateCountry(r.countryCode());requireOwner(r.artisanPartnerId(),actor);UUID id=UUID.randomUUID();String slug=slug(r.slug()==null?r.title():r.slug());if(artworks.existsBySlug(slug))throw new IllegalArgumentException("Artwork slug already exists");CatalogAssetEntity asset=new CatalogAssetEntity();asset.setId(id);asset.setType(AssetType.ARTWORK);asset.setOwnerId(r.artisanPartnerId());asset.setSource("catalog-service");asset.setExternalId(id.toString());asset.setName(r.title());asset.setSlug(slug);asset.setDescription(r.shortDescription());asset.setStatus(AssetStatus.DRAFT);asset.setCreatedAt(Instant.now());asset.setUpdatedAt(Instant.now());assets.save(asset);ArtworkEntity a=apply(new ArtworkEntity(),id,r,slug);artworks.save(a);replaceDetails(id,r);event("ArtworkCreated",a,actor.getSubject(),correlation);return detail(id);}
    @Transactional public ArtworkDtos.Response update(UUID id,ArtworkDtos.Request r,Jwt actor,String correlation){ArtworkEntity a=artworks.locked(id).orElseThrow();requireOwner(a.artisanPartnerId,actor);if(!a.artisanPartnerId.equals(r.artisanPartnerId()))throw new IllegalArgumentException("Artisan owner cannot be changed");apply(a,id,r,a.slug);artworks.save(a);replaceDetails(id,r);event("ArtworkUpdated",a,actor.getSubject(),correlation);return detail(id);}
    @Transactional public void delete(UUID id,Jwt actor,String correlation){ArtworkEntity a=artworks.locked(id).orElseThrow();requireOwner(a.artisanPartnerId,actor);a.deletedAt=Instant.now();a.availabilityStatus=ArtworkEntity.AvailabilityStatus.UNAVAILABLE;artworks.save(a);event("ArtworkArchived",a,actor.getSubject(),correlation);}
    @Transactional public ArtworkEntity availability(UUID id,ArtworkEntity.AvailabilityStatus status,Jwt actor,String correlation){ArtworkEntity a=artworks.locked(id).orElseThrow();requireOwner(a.artisanPartnerId,actor);if(a.availabilityStatus==ArtworkEntity.AvailabilityStatus.SOLD&&status!=ArtworkEntity.AvailabilityStatus.SOLD)throw new IllegalStateException("Sold artwork cannot be reopened manually");a.availabilityStatus=status;artworks.save(a);event(status==ArtworkEntity.AvailabilityStatus.SOLD?"ArtworkSold":"ArtworkAvailabilityChanged",a,actor.getSubject(),correlation);return a;}
    @Transactional public ArtworkDetails.History addHistory(UUID id,ArtworkDtos.HistoryRequest r,Jwt actor,String correlation){ArtworkEntity a=find(id);requireOwner(a.artisanPartnerId,actor);ArtworkDetails.History h=new ArtworkDetails.History();h.id=UUID.randomUUID();h.artworkId=id;copy(h,r);histories.save(h);event("ArtworkHistoryAdded",a,actor.getSubject(),correlation);return h;}
    @Transactional public ArtworkDetails.History updateHistory(UUID artworkId,UUID entryId,ArtworkDtos.HistoryRequest r,Jwt actor){ArtworkEntity a=find(artworkId);requireOwner(a.artisanPartnerId,actor);ArtworkDetails.History h=histories.findByIdAndArtworkId(entryId,artworkId).orElseThrow();copy(h,r);return histories.save(h);}
    @Transactional(readOnly=true) public List<ArtworkDetails.History> history(UUID id){find(id);return histories.findByArtworkIdOrderByCreatedAtAsc(id);}
    @Transactional(readOnly=true) public List<ArtworkDetails.Media> media(UUID id){find(id);return media.findByArtworkIdOrderByDisplayOrderAsc(id);}
    private ArtworkEntity find(UUID id){return artworks.findByAssetIdAndDeletedAtIsNull(id).orElseThrow();}
    private ArtworkEntity apply(ArtworkEntity a,UUID id,ArtworkDtos.Request r,String slug){a.assetId=id;a.artisanPartnerId=r.artisanPartnerId();a.title=r.title();a.slug=slug;a.shortDescription=r.shortDescription();a.story=r.story();a.countryCode=r.countryCode();a.adminLevel1Id=r.adminLevel1Id();a.cityId=r.cityId();a.localityId=r.localityId();a.cultureContentId=r.cultureContentId();a.culturalCommunity=r.culturalCommunity();a.yearCreated=r.yearCreated();a.productionTime=r.productionTime();a.width=r.width();a.height=r.height();a.depth=r.depth();a.weight=r.weight();a.editionType=r.editionType();a.editionSize=r.editionSize();a.availabilityStatus=r.availabilityStatus();if(a.authenticityStatus==null)a.authenticityStatus=ArtworkEntity.AuthenticityStatus.DECLARED;return a;}
    private void replaceDetails(UUID id,ArtworkDtos.Request r){translations.deleteAll(translations.findByArtworkId(id));if(r.translations()!=null)for(var x:r.translations()){var t=new ArtworkDetails.Translation();t.id=UUID.randomUUID();t.artworkId=id;t.languageCode=x.languageCode();t.title=x.title();t.shortDescription=x.shortDescription();t.story=x.story();t.status=x.status()==null?ArtworkDetails.TranslationStatus.DRAFT:x.status();t.translatorId=x.translatorId();translations.save(t);}media.deleteAll(media.findByArtworkIdOrderByDisplayOrderAsc(id));if(r.mediaIds()!=null)for(var x:r.mediaIds()){var m=new ArtworkDetails.Media();m.artworkId=id;m.mediaId=x.mediaId();m.mediaType=x.type();m.displayOrder=x.displayOrder();media.save(m);}}
    private void requireOwner(UUID partner,Jwt jwt){if(admin(jwt))return;Object claim=jwt.getClaims().get("partnerId");Collection<String> ids=jwt.getClaimAsStringList("partnerIds");if(!partner.toString().equals(String.valueOf(claim))&&(ids==null||!ids.contains(partner.toString())))throw new SecurityException("Artwork does not belong to actor partner");}
    private boolean admin(Jwt jwt){List<String> roles=jwt.getClaimAsStringList("roles");return roles!=null&&(roles.contains("ADMIN")||roles.contains("SUPER_ADMIN"));}
    private void event(String type,ArtworkEntity a,String actor,String correlation){outbox.append(type,a.assetId.toString(),actor,correlation,Map.of("artworkId",a.assetId.toString(),"artisanPartnerId",a.artisanPartnerId.toString(),"availability",a.availabilityStatus.name(),"countryCode",a.countryCode));}
    private void validateCountry(String countryCode){if(countries==null)return;try{countries.validateAnyFeature(countryCode,List.of(CountryFeature.ARTISAN_COMMERCE,CountryFeature.CULTURE_MODULE));}catch(CountryConfigClient.CountryConfigException e){throw new CatalogException("COUNTRY_CONFIGURATION_REJECTED",e.getMessage(),org.springframework.http.HttpStatus.SERVICE_UNAVAILABLE);}}
    private String slug(String value){return Normalizer.normalize(value,Normalizer.Form.NFD).replaceAll("\\p{M}","").toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+","-").replaceAll("(^-|-$)","");}
    private void copy(ArtworkDetails.History h,ArtworkDtos.HistoryRequest r){h.title=r.title();h.narrative=r.narrative();h.languageCode=r.languageCode();h.period=r.period();h.culturalMeaning=r.culturalMeaning();h.source=r.source();h.contributorId=r.contributorId();h.verificationStatus=r.verificationStatus()==null?ArtworkDetails.VerificationStatus.DECLARED:r.verificationStatus();}
}
