spring.cloud.config.server.git.uri=${CONFIG_GIT_URI}
spring.cloud.config.server.git.default-label=${CONFIG_GIT_BRANCH:daryl}
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.force-pull=true
spring.cloud.config.server.git.username=${CONFIG_GIT_USERNAME:}
spring.cloud.config.server.git.password=${CONFIG_GIT_PASSWORD:}
spring.cloud.config.server.accept-empty=false

encrypt.key-store.location=${CONFIG_ENCRYPT_KEYSTORE_LOCATION:}
encrypt.key-store.password=${CONFIG_ENCRYPT_KEYSTORE_PASSWORD:}
encrypt.key-store.alias=${CONFIG_ENCRYPT_KEYSTORE_ALIAS:}
encrypt.key-store.secret=${CONFIG_ENCRYPT_KEYSTORE_SECRET:}
spring.cloud.config.server.encrypt.enabled=${CONFIG_ENCRYPT_ENABLED:false}
server.forward-headers-strategy=framework
