CREATE TABLE culture_contents(id UUID PRIMARY KEY,type VARCHAR(40) NOT NULL,slug VARCHAR(180) NOT NULL UNIQUE,status VARCHAR(30) NOT NULL,visibility VARCHAR(20) NOT NULL,primary_language_code VARCHAR(35) NOT NULL,country_code VARCHAR(2) NOT NULL,admin_level_1_id VARCHAR(100),admin_level_2_id VARCHAR(100),city_id VARCHAR(100),locality_id VARCHAR(100),community_name VARCHAR(180),created_by VARCHAR(100) NOT NULL,contributor_type VARCHAR(30) NOT NULL,source_type VARCHAR(40) NOT NULL,verification_status VARCHAR(30) NOT NULL,sensitivity_level VARCHAR(40) NOT NULL,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL,published_at TIMESTAMPTZ,version BIGINT NOT NULL DEFAULT 0,CONSTRAINT ck_culture_country CHECK(country_code ~ '^[A-Z]{2}$'));
CREATE INDEX idx_culture_public ON culture_contents(status,visibility,published_at DESC);CREATE INDEX idx_culture_country_type ON culture_contents(country_code,type,status);CREATE INDEX idx_culture_language ON culture_contents(primary_language_code,status);CREATE INDEX idx_culture_creator ON culture_contents(created_by,status,created_at DESC);
CREATE TABLE culture_content_translations(id UUID PRIMARY KEY,content_id UUID NOT NULL REFERENCES culture_contents(id) ON DELETE CASCADE,language_code VARCHAR(35) NOT NULL,title VARCHAR(255) NOT NULL,summary TEXT,body TEXT,translator_id VARCHAR(100),status VARCHAR(30) NOT NULL,created_at TIMESTAMPTZ NOT NULL,UNIQUE(content_id,language_code));
CREATE TABLE culture_sources(id UUID PRIMARY KEY,content_id UUID NOT NULL REFERENCES culture_contents(id) ON DELETE CASCADE,source_type VARCHAR(40) NOT NULL,citation TEXT,source_person_name VARCHAR(180),relation VARCHAR(180),consent_status VARCHAR(30) NOT NULL,recording_date DATE,locality VARCHAR(180),contributor_id VARCHAR(100),created_at TIMESTAMPTZ NOT NULL);
CREATE TABLE languages(code VARCHAR(35) PRIMARY KEY,name VARCHAR(160) NOT NULL,native_name VARCHAR(160) NOT NULL,country_codes VARCHAR(255) NOT NULL,writing_system VARCHAR(100),status VARCHAR(20) NOT NULL,description TEXT,speaker_estimate BIGINT,verified BOOLEAN NOT NULL DEFAULT FALSE);
CREATE TABLE language_topics(id UUID PRIMARY KEY,code VARCHAR(80) NOT NULL UNIQUE,title VARCHAR(160) NOT NULL,description TEXT,display_order INT NOT NULL DEFAULT 0);
CREATE TABLE language_lessons(id UUID PRIMARY KEY,language_code VARCHAR(35) NOT NULL REFERENCES languages(code),topic_id UUID NOT NULL REFERENCES language_topics(id),title VARCHAR(255) NOT NULL,description TEXT,difficulty INT NOT NULL CHECK(difficulty BETWEEN 1 AND 5),estimated_minutes INT NOT NULL CHECK(estimated_minutes > 0),status VARCHAR(20) NOT NULL,display_order INT NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL);
CREATE TABLE language_lesson_items(id UUID PRIMARY KEY,lesson_id UUID NOT NULL REFERENCES language_lessons(id) ON DELETE CASCADE,phrase TEXT NOT NULL,translation TEXT NOT NULL,transcription TEXT,phonetic TEXT,audio_media_id UUID,image_media_id UUID,cultural_context TEXT,difficulty INT NOT NULL CHECK(difficulty BETWEEN 1 AND 5),examples TEXT,display_order INT NOT NULL DEFAULT 0);
CREATE TABLE language_exercises(id UUID PRIMARY KEY,lesson_id UUID NOT NULL REFERENCES language_lessons(id) ON DELETE CASCADE,item_id UUID REFERENCES language_lesson_items(id),type VARCHAR(40) NOT NULL,prompt TEXT NOT NULL,options_json TEXT,correct_answer TEXT,display_order INT NOT NULL DEFAULT 0);
CREATE TABLE language_user_progress(id UUID PRIMARY KEY,user_id VARCHAR(100) NOT NULL,language_code VARCHAR(35) NOT NULL REFERENCES languages(code),lesson_id UUID NOT NULL REFERENCES language_lessons(id),started_at TIMESTAMPTZ NOT NULL,completed_at TIMESTAMPTZ,score INT CHECK(score BETWEEN 0 AND 100),attempt_count INT NOT NULL DEFAULT 0,version BIGINT NOT NULL DEFAULT 0,UNIQUE(user_id,lesson_id));
CREATE INDEX idx_language_progress_user ON language_user_progress(user_id,language_code,started_at DESC);
CREATE TABLE language_attempts(id UUID PRIMARY KEY,user_id VARCHAR(100) NOT NULL,lesson_id UUID NOT NULL REFERENCES language_lessons(id),exercise_id UUID NOT NULL REFERENCES language_exercises(id),answer_text TEXT,media_id UUID,is_correct BOOLEAN,feedback TEXT,created_at TIMESTAMPTZ NOT NULL);
CREATE INDEX idx_language_attempt_user_lesson ON language_attempts(user_id,lesson_id,created_at DESC);
CREATE TABLE daily_word_selections(id BIGSERIAL PRIMARY KEY,selection_date DATE NOT NULL,country_code VARCHAR(2) NOT NULL,language_code VARCHAR(35),content_id UUID NOT NULL REFERENCES culture_contents(id),UNIQUE(selection_date,country_code,language_code));
CREATE TABLE culture_outbox(id UUID PRIMARY KEY,aggregate_id VARCHAR(100) NOT NULL,event_type VARCHAR(100) NOT NULL,payload TEXT NOT NULL,occurred_at TIMESTAMPTZ NOT NULL,published_at TIMESTAMPTZ,attempts INT NOT NULL DEFAULT 0,last_error VARCHAR(1000));CREATE INDEX idx_culture_outbox_pending ON culture_outbox(occurred_at) WHERE published_at IS NULL;
INSERT INTO language_topics(id,code,title,display_order) VALUES
('10000000-0000-0000-0000-000000000001','greetings','Salutations',1),('10000000-0000-0000-0000-000000000002','family','Famille',2),('10000000-0000-0000-0000-000000000003','food','Alimentation',3),('10000000-0000-0000-0000-000000000004','travel','Voyage',4),('10000000-0000-0000-0000-000000000005','everyday-expressions','Expressions quotidiennes',5),('10000000-0000-0000-0000-000000000006','culture','Culture',6),('10000000-0000-0000-0000-000000000007','customs','Coutumes',7) ON CONFLICT DO NOTHING;
