package com.yeyamo_mobile.api.commerce_service.application;
import com.yeyamo_mobile.api.commerce_service.messaging.OutboxService;import com.yeyamo_mobile.api.commerce_service.persistence.*;import org.junit.jupiter.api.*;import org.mockito.*;import java.math.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
class ArtworkCommerceServiceTest{
 @Mock ArtworkCommerceRepositories.Offers offers;@Mock ArtworkCommerceRepositories.Orders orders;@Mock ArtworkCommerceRepositories.History history;@Mock CommerceService commerce;@Mock OutboxService outbox;ArtworkCommerceService service;AutoCloseable mocks;
 @BeforeEach void setup(){mocks=MockitoAnnotations.openMocks(this);service=new ArtworkCommerceService(offers,orders,history,commerce,outbox);}@AfterEach void close()throws Exception{mocks.close();}
 @Test void idempotentOrderDoesNotReserveTwice(){ArtworkOrder existing=new ArtworkOrder();when(orders.findByIdempotencyKey("key")).thenReturn(Optional.of(existing));assertSame(existing,service.createOrder(new ArtworkCommerceService.OrderCommand(UUID.randomUUID(),1,ArtworkOrder.DeliveryType.PICKUP),"user","key"));verifyNoInteractions(offers,commerce);}
 @Test void uniqueArtworkCannotBeSoldTwice(){ArtworkOffer offer=new ArtworkOffer();offer.id=UUID.randomUUID();offer.status=ArtworkOffer.Status.ACTIVE;offer.saleType=ArtworkOffer.SaleType.FIXED_PRICE;offer.availableQuantity=1;offer.reservedQuantity=1;when(orders.findByIdempotencyKey("new")).thenReturn(Optional.empty());when(offers.locked(offer.id)).thenReturn(Optional.of(offer));assertThrows(IllegalStateException.class,()->service.createOrder(new ArtworkCommerceService.OrderCommand(offer.id,1,ArtworkOrder.DeliveryType.PICKUP),"user","new"));verifyNoInteractions(commerce);}
 @Test void paymentFailureReleasesReservation(){ArtworkOffer offer=new ArtworkOffer();offer.id=UUID.randomUUID();offer.reservedQuantity=1;ArtworkOrder order=new ArtworkOrder();order.id=UUID.randomUUID();order.offerId=offer.id;order.quantity=1;order.status=ArtworkOrder.Status.AWAITING_PAYMENT;UUID commerceId=UUID.randomUUID();when(orders.findByCommerceOrderId(commerceId)).thenReturn(Optional.of(order));when(offers.locked(offer.id)).thenReturn(Optional.of(offer));service.paymentFailed(commerceId);assertEquals(0,offer.reservedQuantity);assertEquals(ArtworkOrder.Status.CANCELLED,order.status);verify(offers).save(offer);}
}
