package com.yeyamo_mobile.api.commerce_service.domain;
public final class CommerceTypes{private CommerceTypes(){}
 public enum ProductType{TICKET_ORDER,BOOKING_ORDER,CAMPAIGN_CREDIT_ORDER,EXPERIENCE_ORDER,PARTNER_SUBSCRIPTION}
 public enum OrderStatus{CREATED,AWAITING_PAYMENT,PAID,COMPLETED,CANCELLED,PARTIALLY_REFUNDED,REFUNDED,PAYMENT_FAILED}
 public enum DiscountType{PERCENTAGE,FIXED_AMOUNT,FREE_SERVICE_FEE}
 public enum LedgerType{SALE_CREDIT,PLATFORM_COMMISSION,REFUND_DEBIT,ADJUSTMENT,PAYOUT,CHARGEBACK}
 public enum PromotionStatus{DRAFT,ACTIVE,INACTIVE,EXPIRED}
}
