package com.yeyamo_mobile.api.culture_service.domain;

public final class CultureEnums {
    private CultureEnums() {}
    public enum ContentType { LANGUAGE_LESSON, WORD, EXPRESSION, PROVERB, STORY, ORAL_HISTORY, TRADITION, RITUAL, FESTIVAL, HISTORICAL_EVENT, HISTORICAL_FIGURE, DANCE, SONG, RECIPE, SYMBOL, CUSTOM, OTHER }
    public enum ContentStatus { DRAFT, SUBMITTED, UNDER_REVIEW, APPROVED, CORRECTIONS_REQUIRED, REJECTED, PUBLISHED, ARCHIVED }
    public enum Visibility { PUBLIC, UNLISTED, PRIVATE }
    public enum ContributorType { USER, PARTNER, INSTITUTION, RESEARCHER, ADMIN }
    public enum SourceType { ORAL_TESTIMONY, BOOK, INSTITUTION, MUSEUM, RESEARCHER, COMMUNITY_ELDER, PERSONAL_CONTRIBUTION, ARCHIVE }
    public enum VerificationStatus { UNVERIFIED, PENDING, REVIEWED, VERIFIED, REJECTED }
    public enum SensitivityLevel { PUBLIC, CONTEXT_REQUIRED, COMMUNITY_RESTRICTED, SACRED, ARCHIVED }
    public enum TranslationStatus { DRAFT, COMMUNITY_PROPOSED, REVIEWED, VERIFIED, REJECTED }
    public enum ConsentStatus { NOT_REQUIRED, REQUESTED, GRANTED, RESTRICTED, REVOKED }
    public enum LanguageStatus { DISABLED, BETA, ACTIVE, ARCHIVED }
    public enum LessonStatus { DRAFT, PUBLISHED, ARCHIVED }
    public enum ExerciseType { MULTIPLE_CHOICE, AUDIO_CHOICE, MATCH_WORD_IMAGE, COMPLETE_PHRASE, IDENTIFY_LANGUAGE, PRONUNCIATION_SUBMISSION }
}
