package com.yeyamo_mobile.api.culture_service.domain;

import static com.yeyamo_mobile.api.culture_service.domain.CultureEnums.*;
import jakarta.persistence.*;
import java.time.Instant;
import java.util.UUID;

@Entity @Table(name="culture_contents")
public class CultureContent {
 @Id private UUID id; @Enumerated(EnumType.STRING) @Column(nullable=false) private ContentType type;
 @Column(nullable=false,unique=true,length=180) private String slug; @Enumerated(EnumType.STRING) @Column(nullable=false) private ContentStatus status;
 @Enumerated(EnumType.STRING) @Column(nullable=false) private Visibility visibility; @Column(name="primary_language_code",nullable=false,length=35) private String primaryLanguageCode;
 @Column(name="country_code",nullable=false,length=2) private String countryCode; @Column(name="admin_level_1_id") private String adminLevel1Id; @Column(name="admin_level_2_id") private String adminLevel2Id;
 @Column(name="city_id") private String cityId; @Column(name="locality_id") private String localityId; @Column(name="community_name") private String communityName;
 @Column(name="created_by",nullable=false) private String createdBy; @Enumerated(EnumType.STRING) @Column(name="contributor_type",nullable=false) private ContributorType contributorType;
 @Enumerated(EnumType.STRING) @Column(name="source_type",nullable=false) private SourceType sourceType; @Enumerated(EnumType.STRING) @Column(name="verification_status",nullable=false) private VerificationStatus verificationStatus;
 @Enumerated(EnumType.STRING) @Column(name="sensitivity_level",nullable=false) private SensitivityLevel sensitivityLevel; @Column(name="created_at",nullable=false) private Instant createdAt;
 @Column(name="updated_at",nullable=false) private Instant updatedAt; @Column(name="published_at") private Instant publishedAt; @Version private long version;
 protected CultureContent() {}
 public static CultureContent create(ContentType type,String slug,String language,String country,String actor,ContributorType contributor,SourceType source,SensitivityLevel sensitivity,Visibility visibility){CultureContent c=new CultureContent();c.id=UUID.randomUUID();c.type=type;c.slug=slug;c.primaryLanguageCode=language;c.countryCode=country;c.createdBy=actor;c.contributorType=contributor;c.sourceType=source;c.sensitivityLevel=sensitivity;c.visibility=visibility;c.status=ContentStatus.DRAFT;c.verificationStatus=VerificationStatus.UNVERIFIED;c.createdAt=Instant.now();c.updatedAt=c.createdAt;return c;}
 public void submit(String actor){owner(actor);transition(ContentStatus.SUBMITTED);} public void updateLocation(String a1,String a2,String city,String locality,String community){adminLevel1Id=a1;adminLevel2Id=a2;cityId=city;localityId=locality;communityName=community;updatedAt=Instant.now();}
 public void changeStatus(ContentStatus target){if(target==ContentStatus.PUBLISHED&&(sensitivityLevel==SensitivityLevel.SACRED||sensitivityLevel==SensitivityLevel.COMMUNITY_RESTRICTED)&&verificationStatus!=VerificationStatus.VERIFIED)throw new IllegalStateException("Sensitive content requires explicit verification");transition(target);if(target==ContentStatus.PUBLISHED)publishedAt=Instant.now();}
 public void markVerified(){verificationStatus=VerificationStatus.VERIFIED;updatedAt=Instant.now();} private void transition(ContentStatus target){boolean ok=switch(status){case DRAFT->target==ContentStatus.SUBMITTED||target==ContentStatus.ARCHIVED;case SUBMITTED->target==ContentStatus.UNDER_REVIEW||target==ContentStatus.DRAFT;case UNDER_REVIEW->target==ContentStatus.APPROVED||target==ContentStatus.CORRECTIONS_REQUIRED||target==ContentStatus.REJECTED;case APPROVED->target==ContentStatus.PUBLISHED||target==ContentStatus.ARCHIVED;case CORRECTIONS_REQUIRED->target==ContentStatus.DRAFT||target==ContentStatus.SUBMITTED;case REJECTED->target==ContentStatus.DRAFT||target==ContentStatus.ARCHIVED;case PUBLISHED->target==ContentStatus.ARCHIVED||target==ContentStatus.UNDER_REVIEW;case ARCHIVED->target==ContentStatus.DRAFT;};if(!ok)throw new IllegalStateException("Invalid culture status transition: "+status+" -> "+target);status=target;updatedAt=Instant.now();}
 private void owner(String actor){if(!createdBy.equals(actor))throw new SecurityException("Contribution owner mismatch");}
 public UUID getId(){return id;} public ContentType getType(){return type;} public String getSlug(){return slug;} public ContentStatus getStatus(){return status;} public Visibility getVisibility(){return visibility;} public String getPrimaryLanguageCode(){return primaryLanguageCode;} public String getCountryCode(){return countryCode;} public String getAdminLevel1Id(){return adminLevel1Id;} public String getAdminLevel2Id(){return adminLevel2Id;} public String getCityId(){return cityId;} public String getLocalityId(){return localityId;} public String getCommunityName(){return communityName;} public String getCreatedBy(){return createdBy;} public ContributorType getContributorType(){return contributorType;} public SourceType getSourceType(){return sourceType;} public VerificationStatus getVerificationStatus(){return verificationStatus;} public SensitivityLevel getSensitivityLevel(){return sensitivityLevel;} public Instant getCreatedAt(){return createdAt;} public Instant getUpdatedAt(){return updatedAt;} public Instant getPublishedAt(){return publishedAt;} public long getVersion(){return version;}
}
