package com.yeyamo_mobile.api.partner_service.application;

import java.io.IOException;import java.io.InputStream;import java.util.*;import org.springframework.data.domain.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import com.yeyamo_mobile.api.partner_service.application.port.*;import com.yeyamo_mobile.api.partner_service.domain.model.*;import com.yeyamo_mobile.api.partner_service.domain.port.*;
@Service public class PartnerService{
 private static final Set<String> TYPES=Set.of("application/pdf","image/jpeg","image/png");private final PartnerRepository partners;private final PartnerDocumentRepository documents;private final DocumentStoragePort storage;private final PartnerOutboxPort outbox;private final KycPolicy kycPolicy;private final long maxSize;
 public PartnerService(PartnerRepository p,PartnerDocumentRepository d,DocumentStoragePort s,PartnerOutboxPort o,KycPolicy policy,@org.springframework.beans.factory.annotation.Value("${yeyamo.documents.max-size-bytes:10485760}")long max){partners=p;documents=d;storage=s;outbox=o;kycPolicy=policy;maxSize=max;}
 @Transactional public Partner create(String owner,String legal,String trade,BusinessType type,String registration,String tax,String email,String phone,String website,String description,String correlation){if(partners.existsByOwnerUserId(owner))throw error("PARTNER_ALREADY_EXISTS","Un compte partenaire existe déjà",HttpStatus.CONFLICT);Partner p=Partner.create(owner,legal,type,email);p.update(legal,trade,type,registration,tax,email,phone,website,description);p=partners.save(p);event("partner.created",p,owner,correlation);return p;}
 @Transactional(readOnly=true)public Partner me(String owner){return owned(owner);}@Transactional(readOnly=true)public List<PartnerDocument>myDocuments(String owner){return documents.findByPartnerId(owned(owner).getId());}
 @Transactional(readOnly=true)public Partner publicPartner(UUID id){Partner p=partners.findById(id).orElseThrow(this::notFound);if(!p.isPublic())throw error("PARTNER_NOT_ACCESSIBLE","Partenaire non accessible",HttpStatus.NOT_FOUND);return p;}
 @Transactional(readOnly=true)public Page<Partner>search(String q,Pageable pageable){return partners.searchApproved(q,pageable);}
 @Transactional public Partner update(String owner,String legal,String trade,BusinessType type,String registration,String tax,String email,String phone,String website,String description,String correlation){Partner p=owned(owner);try{p.update(legal,trade,type,registration,tax,email,phone,website,description);}catch(IllegalStateException e){throw state(e);}Partner saved=partners.save(p);event("partner.updated",saved,owner,correlation);return saved;}
 @Transactional public PartnerDocument addDocument(String owner,DocumentType type,String filename,String contentType,long size,InputStream stream,String correlation)throws IOException{Partner p=owned(owner);if(!p.canEditDocuments())throw error("PARTNER_NOT_EDITABLE","Les documents ne peuvent plus être modifiés",HttpStatus.CONFLICT);if(size<=0||size>maxSize)throw error("DOCUMENT_SIZE_INVALID","Taille de document invalide",HttpStatus.BAD_REQUEST);if(!TYPES.contains(contentType))throw error("DOCUMENT_TYPE_INVALID","Format autorisé: PDF, JPEG ou PNG",HttpStatus.BAD_REQUEST);String safeName=filename==null||filename.isBlank()?"document":filename;String key=storage.store(p.getId().toString(),safeName,contentType,stream);PartnerDocument d=documents.save(PartnerDocument.create(p.getId(),type,key,safeName,contentType,size));event("partner.document_added",p,owner,correlation);return d;}
 @Transactional public void removeDocument(String owner,UUID documentId,String correlation)throws IOException{Partner p=owned(owner);if(!p.canEditDocuments())throw error("PARTNER_NOT_EDITABLE","Les documents ne peuvent plus être modifiés",HttpStatus.CONFLICT);PartnerDocument d=documents.findDocumentById(documentId).orElseThrow(()->error("DOCUMENT_NOT_FOUND","Document introuvable",HttpStatus.NOT_FOUND));if(!d.partnerId().equals(p.getId()))throw error("DOCUMENT_NOT_FOUND","Document introuvable",HttpStatus.NOT_FOUND);documents.delete(d);storage.delete(d.storageKey());event("partner.document_removed",p,owner,correlation);}
 @Transactional public Partner submit(String owner,String correlation){Partner p=owned(owner);List<PartnerDocument> docs=documents.findByPartnerId(p.getId());kycPolicy.validate(p,docs);try{p.submit(docs.size());}catch(IllegalStateException e){throw state(e);}Partner saved=partners.save(p);Map<String,Object> payload=new LinkedHashMap<>();payload.put("partnerId",p.getId());payload.put("requesterId",owner);payload.put("kycDocumentKeys",docs.stream().map(PartnerDocument::storageKey).toList());payload.put("kycDocumentTypes",docs.stream().map(d->d.documentType().name()).toList());outbox.append("partner.submitted",p.getId(),owner,correlation,payload);return saved;}
 @Transactional public Partner applyDecision(UUID id,PartnerStatus decision,String comment,Integer risk,String correlation){Partner p=partners.findById(id).orElseThrow(this::notFound);try{p.review(decision,comment,risk);}catch(IllegalStateException|IllegalArgumentException e){throw state(e);}Partner saved=partners.save(p);event("partner."+decision.name().toLowerCase(),saved,"admin-service",correlation);return saved;}
 private Partner owned(String owner){return partners.findByOwnerUserId(owner).orElseThrow(this::notFound);}private PartnerException notFound(){return error("PARTNER_NOT_FOUND","Partenaire introuvable",HttpStatus.NOT_FOUND);}private PartnerException state(Exception e){return error("INVALID_PARTNER_STATE",e.getMessage(),HttpStatus.CONFLICT);}private PartnerException error(String c,String m,HttpStatus s){return new PartnerException(c,m,s);}
 private void event(String type,Partner p,String actor,String correlation){outbox.append(type,p.getId(),actor,correlation,Map.of("partnerId",p.getId(),"ownerUserId",p.getOwnerUserId(),"status",p.getStatus().name(),"legalName",p.getLegalName()));}
}
