package com.yeyamo_mobile.api.graph_service.infrastructure;
import com.fasterxml.jackson.databind.*;import org.springframework.data.neo4j.core.Neo4jClient;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;
@Service public class GraphProjectionService{
 public static final Set<String> NODE_LABELS=Set.of("Country","AdministrativeArea","City","Culture","Community","Language","Tradition","Proverb","Story","HistoricalFigure","HistoricalEvent","Festival","Artwork","Artisan","Material","Technique","Place","Event");
 private static final Set<String> RELATIONS=Set.of("CREATED","ORIGINATES_FROM","ASSOCIATED_WITH","USES_MATERIAL","USES_TECHNIQUE","HAS_HISTORY","SPOKEN_IN","CELEBRATES","LOCATED_IN","EXHIBITED_AT");
 private final Neo4jClient neo;public GraphProjectionService(Neo4jClient n){neo=n;}
 @Transactional public boolean apply(JsonNode envelope){String eventId=required(envelope,"eventId");if(processed(eventId))return false;String type=required(envelope,"eventType");String correlationId=text(envelope,"correlationId",eventId);JsonNode p=envelope.path("payload");switch(type){case "ArtworkPublished","ArtworkUpdated"->artwork(p);case "ArtisanVerified"->node("Artisan",id(p,"artisanId","partnerId"),props(p,"displayName","countryCode"));case "CultureContentPublished","CultureContentUpdated"->culture(p);case "PlaceCreated"->place(p);case "EventPublished"->event(p);case "MaterialUpdated"->node("Material",id(p,"materialId"),props(p,"code"));case "TechniqueUpdated"->node("Technique",id(p,"techniqueId"),props(p,"code"));default->throw new IllegalArgumentException("Unsupported graph event: "+type);}neo.query("MERGE (e:ProcessedEvent {id:$id}) SET e.type=$type,e.correlationId=$correlationId,e.processedAt=$at").bindAll(Map.of("id",eventId,"type",type,"correlationId",correlationId,"at",Instant.now().toString())).run();return true;}
 private void artwork(JsonNode p){String artwork=id(p,"artworkId","assetId");node("Artwork",artwork,props(p,"title","countryCode","cultureContentId"));String artisan=text(p,"artisanPartnerId");if(artisan!=null){node("Artisan",artisan,Map.of());rel("Artisan",artisan,"CREATED","Artwork",artwork);}String country=text(p,"countryCode");if(country!=null){node("Country",country,Map.of("code",country));rel("Artwork",artwork,"ORIGINATES_FROM","Country",country);}String culture=text(p,"cultureContentId");if(culture!=null){node("Culture",culture,Map.of());rel("Artwork",artwork,"ASSOCIATED_WITH","Culture",culture);}arrayRelations(p,"materialIds","Material","USES_MATERIAL",artwork);arrayRelations(p,"techniqueIds","Technique","USES_TECHNIQUE",artwork);}
 private void culture(JsonNode p){String id=id(p,"contentId","cultureContentId");String label=switch(text(p,"type","Culture")){case "PROVERB"->"Proverb";case "STORY","ORAL_HISTORY"->"Story";case "TRADITION","RITUAL"->"Tradition";case "HISTORICAL_FIGURE"->"HistoricalFigure";case "HISTORICAL_EVENT"->"HistoricalEvent";case "FESTIVAL"->"Festival";default->"Culture";};node(label,id,props(p,"type","countryCode","primaryLanguageCode"));String country=text(p,"countryCode");if(country!=null){node("Country",country,Map.of("code",country));rel(label,id,"ORIGINATES_FROM","Country",country);}String lang=text(p,"primaryLanguageCode");if(lang!=null){node("Language",lang,Map.of("code",lang));if(country!=null)rel("Language",lang,"SPOKEN_IN","Country",country);}}
 private void place(JsonNode p){String id=id(p,"placeId");node("Place",id,props(p,"name","cityId"));String city=text(p,"cityId");if(city!=null){node("City",city,Map.of());rel("Place",id,"LOCATED_IN","City",city);}}
 private void event(JsonNode p){String id=id(p,"eventId");node("Event",id,props(p,"name"));String tradition=text(p,"traditionId");if(tradition!=null){node("Tradition",tradition,Map.of());rel("Event",id,"CELEBRATES","Tradition",tradition);}}
 private void arrayRelations(JsonNode p,String field,String target,String relation,String artwork){if(p.path(field).isArray())p.path(field).forEach(v->{String id=v.asText();node(target,id,Map.of());rel("Artwork",artwork,relation,target,id);});}
 private void node(String label,String id,Map<String,Object> properties){checkLabel(label);Map<String,Object> values=new LinkedHashMap<>(properties);values.put("id",id);neo.query("MERGE (n:"+label+" {id:$id}) SET n += $props").bind(id).to("id").bind(values).to("props").run();}
 private void rel(String from,String fromId,String type,String to,String toId){checkLabel(from);checkLabel(to);if(!RELATIONS.contains(type))throw new IllegalArgumentException("Invalid relation");neo.query("MATCH (a:"+from+" {id:$fromId}),(b:"+to+" {id:$toId}) MERGE (a)-[r:"+type+"]->(b)").bindAll(Map.of("fromId",fromId,"toId",toId)).run();}
 private boolean processed(String id){return neo.query("MATCH (e:ProcessedEvent {id:$id}) RETURN count(e)>0 AS found").bind(id).to("id").fetchAs(Boolean.class).mappedBy((t,r)->r.get("found").asBoolean()).one().orElse(false);}private void checkLabel(String l){if(!NODE_LABELS.contains(l))throw new IllegalArgumentException("Invalid node label");}private String required(JsonNode n,String f){String v=text(n,f);if(v==null)throw new IllegalArgumentException(f+" is required");return v;}private String id(JsonNode n,String...fields){for(String f:fields){String v=text(n,f);if(v!=null)return v;}throw new IllegalArgumentException("Projection identifier missing");}private String text(JsonNode n,String f){JsonNode v=n.get(f);return v==null||v.isNull()||v.asText().isBlank()?null:v.asText();}private String text(JsonNode n,String f,String d){String v=text(n,f);return v==null?d:v;}private Map<String,Object>props(JsonNode n,String...fields){Map<String,Object>m=new LinkedHashMap<>();for(String f:fields){String v=text(n,f);if(v!=null)m.put(f,v);}return m;}
}
