package com.yeyamo_mobile.api.moderation_trust_service.application;import static org.junit.jupiter.api.Assertions.*;import java.util.*;import org.junit.jupiter.api.Test;import com.fasterxml.jackson.databind.ObjectMapper;import com.yeyamo_mobile.api.moderation_trust_service.application.port.*;import com.yeyamo_mobile.api.moderation_trust_service.domain.model.*;import com.yeyamo_mobile.api.moderation_trust_service.domain.port.*;
class ModerationServiceTests{@Test void approvedReportUpdatesTargetAndReporterScoresAndEmitsEvents(){MemoryReports reports=new MemoryReports();MemoryScores scores=new MemoryScores();MemoryAudit audit=new MemoryAudit();List<String>events=new ArrayList<>();ModerationOutboxPort outbox=(t,a,i,actor,c,p)->events.add(t);ModerationService service=new ModerationService(reports,scores,audit,outbox,new ObjectMapper());
  ModerationReport report=service.report(TargetType.POST,"post-1","author-1","reporter-1",ReportReason.HARASSMENT,"evidence","corr");service.review(report.getId(),"moderator","corr");service.decide(report.getId(),ReportStatus.APPROVED,"moderator","confirmed","corr");
  assertEquals(40,scores.values.get("author-1").getScore());assertEquals(51,scores.values.get("reporter-1").getScore());assertTrue(events.contains("moderation.report.approved"));assertEquals(2,events.stream().filter(e->e.equals("trust.score.changed")).count());assertEquals(5,audit.values.size());}
 @Test void preventsDuplicateActiveReport(){MemoryReports reports=new MemoryReports();ModerationService service=new ModerationService(reports,new MemoryScores(),new MemoryAudit(),(a,b,c,d,e,f)->{},new ObjectMapper());service.report(TargetType.MEDIA,"m1",null,"u1",ReportReason.OTHER,null,null);assertThrows(ModerationException.class,()->service.report(TargetType.MEDIA,"m1",null,"u1",ReportReason.SPAM,null,null));}
 static class MemoryReports implements ModerationReportRepository{final Map<UUID,ModerationReport>values=new HashMap<>();public ModerationReport save(ModerationReport r){values.put(r.getId(),r);return r;}public Optional<ModerationReport>findById(UUID id){return Optional.ofNullable(values.get(id));}public List<ModerationReport>find(ReportStatus s,String reporter,int l){return values.values().stream().filter(r->s==null||r.getStatus()==s).filter(r->reporter==null||reporter.equals(r.getReporterId())).limit(l).toList();}public boolean existsOpen(TargetType t,String id,String reporter){return values.values().stream().anyMatch(r->r.getTargetType()==t&&r.getTargetId().equals(id)&&r.getReporterId().equals(reporter)&&(r.getStatus()==ReportStatus.OPEN||r.getStatus()==ReportStatus.REVIEW));}}
 static class MemoryScores implements TrustScoreRepository{final Map<String,TrustScore>values=new HashMap<>();public TrustScore save(TrustScore s){values.put(s.getSubjectId(),s);return s;}public Optional<TrustScore>findById(String id){return Optional.ofNullable(values.get(id));}}
 static class MemoryAudit implements ModerationAuditPort{final List<AuditEntry>values=new ArrayList<>();public void append(AuditEntry e){values.add(e);}public List<AuditEntry>latest(int l){return values.stream().limit(l).toList();}}
}
