package com.yeyamo_mobile.api.payment_service.infrastructure.web;
import static com.yeyamo_mobile.api.payment_service.application.PaymentCommands.*;import static com.yeyamo_mobile.api.payment_service.application.PaymentViews.*;import java.math.BigDecimal;import java.util.*;import org.springframework.http.HttpStatus;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import com.yeyamo_mobile.api.payment_service.application.PaymentApplicationService;import com.yeyamo_mobile.api.payment_service.domain.PaymentException;import jakarta.validation.Valid;import jakarta.validation.constraints.*;
@RestController @RequestMapping("/api/v1/payments")public class PaymentController{
 private final PaymentApplicationService service;public PaymentController(PaymentApplicationService s){service=s;}
 @GetMapping("/{id}")public PaymentView get(@PathVariable UUID id,Authentication auth){var payment=service.get(id);authorize(payment.getUserId(),auth);return PaymentView.from(payment);}
 @GetMapping("/mine")public List<PaymentView> mine(Authentication auth){return service.byUser(auth.getName()).stream().map(PaymentView::from).toList();}
 @GetMapping("/{id}/refunds")public List<RefundView> refunds(@PathVariable UUID id,Authentication auth){var payment=service.get(id);authorize(payment.getUserId(),auth);return service.refunds(id).stream().map(RefundView::from).toList();}
 @PostMapping("/{id}/refunds")@ResponseStatus(HttpStatus.ACCEPTED)public RefundView refund(@PathVariable UUID id,@Valid@RequestBody ManualRefundRequest request,@RequestHeader("Idempotency-Key")String key,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,Authentication auth){if(!admin(auth))throw new PaymentException("FORBIDDEN","Administrator role required");var p=service.get(id);return RefundView.from(service.refund(new Refund(p.getSagaId(),p.getBookingId(),p.getProviderPaymentId(),request.amount(),p.getCurrency(),key,correlation)));}
 private void authorize(String owner,Authentication auth){if(!owner.equals(auth.getName())&&!admin(auth))throw new PaymentException("FORBIDDEN","Payment does not belong to authenticated user");}private boolean admin(Authentication a){return a.getAuthorities().stream().anyMatch(x->x.getAuthority().equals("ROLE_ADMIN")||x.getAuthority().equals("ROLE_SUPER_ADMIN"));}
 public record ManualRefundRequest(@NotNull@DecimalMin("0.01")@Digits(integer=10,fraction=2)BigDecimal amount){}
}
