spring.application.name=ticket-service
spring.cloud.config.username=${CONFIG_SERVER_USERNAME}
spring.cloud.config.password=${CONFIG_SERVER_PASSWORD}
spring.config.import=configserver:${CONFIG_SERVER_URL:http://config-server:8080}
spring.cloud.config.fail-fast=true
yeyamo.tickets.qr.key-id=${TICKET_QR_KEY_ID:}
yeyamo.tickets.qr.private-key-base64=${TICKET_QR_PRIVATE_KEY_BASE64:}
yeyamo.tickets.qr.public-key-base64=${TICKET_QR_PUBLIC_KEY_BASE64:}
